// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// Authorize is the OCPP Authorize message (SentByCP).
var Authorize = ocppj.Message[
	messages.AuthorizeRequest,
	messages.AuthorizeResponse,
]{Action: "Authorize", Direction: ocppj.SentByCP}

// ClearCache is the OCPP ClearCache message (SentByCSMS).
var ClearCache = ocppj.Message[
	messages.ClearCacheRequest,
	messages.ClearCacheResponse,
]{Action: "ClearCache", Direction: ocppj.SentByCSMS}
