// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// NotifyEvent is the OCPP NotifyEvent message (SentByCP).
var NotifyEvent = ocppj.Message[
	messages.NotifyEventRequest,
	messages.NotifyEventResponse,
]{Action: "NotifyEvent", Direction: ocppj.SentByCP}

// NotifyMonitoringReport is the OCPP NotifyMonitoringReport message (SentByCP).
var NotifyMonitoringReport = ocppj.Message[
	messages.NotifyMonitoringReportRequest,
	messages.NotifyMonitoringReportResponse,
]{Action: "NotifyMonitoringReport", Direction: ocppj.SentByCP}

// GetMonitoringReport is the OCPP GetMonitoringReport message (SentByCSMS).
var GetMonitoringReport = ocppj.Message[
	messages.GetMonitoringReportRequest,
	messages.GetMonitoringReportResponse,
]{Action: "GetMonitoringReport", Direction: ocppj.SentByCSMS}

// SetMonitoringBase is the OCPP SetMonitoringBase message (SentByCSMS).
var SetMonitoringBase = ocppj.Message[
	messages.SetMonitoringBaseRequest,
	messages.SetMonitoringBaseResponse,
]{Action: "SetMonitoringBase", Direction: ocppj.SentByCSMS}

// SetVariableMonitoring is the OCPP SetVariableMonitoring message (SentByCSMS).
var SetVariableMonitoring = ocppj.Message[
	messages.SetVariableMonitoringRequest,
	messages.SetVariableMonitoringResponse,
]{Action: "SetVariableMonitoring", Direction: ocppj.SentByCSMS}

// ClearVariableMonitoring is the OCPP ClearVariableMonitoring message (SentByCSMS).
var ClearVariableMonitoring = ocppj.Message[
	messages.ClearVariableMonitoringRequest,
	messages.ClearVariableMonitoringResponse,
]{Action: "ClearVariableMonitoring", Direction: ocppj.SentByCSMS}

// SetMonitoringLevel is the OCPP SetMonitoringLevel message (SentByCSMS).
var SetMonitoringLevel = ocppj.Message[
	messages.SetMonitoringLevelRequest,
	messages.SetMonitoringLevelResponse,
]{Action: "SetMonitoringLevel", Direction: ocppj.SentByCSMS}

// GetLog is the OCPP GetLog message (SentByCSMS).
var GetLog = ocppj.Message[
	messages.GetLogRequest,
	messages.GetLogResponse,
]{Action: "GetLog", Direction: ocppj.SentByCSMS}

// LogStatusNotification is the OCPP LogStatusNotification message (SentByCP).
var LogStatusNotification = ocppj.Message[
	messages.LogStatusNotificationRequest,
	messages.LogStatusNotificationResponse,
]{Action: "LogStatusNotification", Direction: ocppj.SentByCP}

// CustomerInformation is the OCPP CustomerInformation message (SentByCSMS).
var CustomerInformation = ocppj.Message[
	messages.CustomerInformationRequest,
	messages.CustomerInformationResponse,
]{Action: "CustomerInformation", Direction: ocppj.SentByCSMS}

// NotifyCustomerInformation is the OCPP NotifyCustomerInformation message (SentByCP).
var NotifyCustomerInformation = ocppj.Message[
	messages.NotifyCustomerInformationRequest,
	messages.NotifyCustomerInformationResponse,
]{Action: "NotifyCustomerInformation", Direction: ocppj.SentByCP}
