// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// MeterValues is the OCPP MeterValues message (SentByCP).
var MeterValues = ocppj.Message[
	messages.MeterValuesRequest,
	messages.MeterValuesResponse,
]{Action: "MeterValues", Direction: ocppj.SentByCP}
