// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// RequestStartTransaction is the OCPP RequestStartTransaction message (SentByCSMS).
var RequestStartTransaction = ocppj.Message[
	messages.RequestStartTransactionRequest,
	messages.RequestStartTransactionResponse,
]{Action: "RequestStartTransaction", Direction: ocppj.SentByCSMS}

// RequestStopTransaction is the OCPP RequestStopTransaction message (SentByCSMS).
var RequestStopTransaction = ocppj.Message[
	messages.RequestStopTransactionRequest,
	messages.RequestStopTransactionResponse,
]{Action: "RequestStopTransaction", Direction: ocppj.SentByCSMS}

// UnlockConnector is the OCPP UnlockConnector message (SentByCSMS).
var UnlockConnector = ocppj.Message[
	messages.UnlockConnectorRequest,
	messages.UnlockConnectorResponse,
]{Action: "UnlockConnector", Direction: ocppj.SentByCSMS}

// TriggerMessage is the OCPP TriggerMessage message (SentByCSMS).
var TriggerMessage = ocppj.Message[
	messages.TriggerMessageRequest,
	messages.TriggerMessageResponse,
]{Action: "TriggerMessage", Direction: ocppj.SentByCSMS}
