// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// CostUpdated is the OCPP CostUpdated message (SentByCSMS).
var CostUpdated = ocppj.Message[
	messages.CostUpdatedRequest,
	messages.CostUpdatedResponse,
]{Action: "CostUpdated", Direction: ocppj.SentByCSMS}
