// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v201/messages"
)

// TransactionEvent is the OCPP TransactionEvent message (SentByCP).
var TransactionEvent = ocppj.Message[
	messages.TransactionEventRequest,
	messages.TransactionEventResponse,
]{Action: "TransactionEvent", Direction: ocppj.SentByCP}

// GetTransactionStatus is the OCPP GetTransactionStatus message (SentByCSMS).
var GetTransactionStatus = ocppj.Message[
	messages.GetTransactionStatusRequest,
	messages.GetTransactionStatusResponse,
]{Action: "GetTransactionStatus", Direction: ocppj.SentByCSMS}
