// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v16/messages"
)

// BootNotification is the OCPP BootNotification message (SentByCP).
var BootNotification = ocppj.Message[
	messages.BootNotificationRequest,
	messages.BootNotificationResponse,
]{Action: "BootNotification", Direction: ocppj.SentByCP}
