// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/schema"
	"github.com/shiv3/gocpp/v16/schemas"
)

// RegisterSchemas registers all v16 request/response schemas.
func RegisterSchemas(r *schema.Registry) error {
	type reg struct{ action, kind, file string }
	for _, e := range []reg{
		{"Authorize", "request", "Authorize.json"},
		{"Authorize", "response", "AuthorizeResponse.json"},
		{"BootNotification", "request", "BootNotification.json"},
		{"BootNotification", "response", "BootNotificationResponse.json"},
		{"ChangeAvailability", "request", "ChangeAvailability.json"},
		{"ChangeAvailability", "response", "ChangeAvailabilityResponse.json"},
		{"ChangeConfiguration", "request", "ChangeConfiguration.json"},
		{"ChangeConfiguration", "response", "ChangeConfigurationResponse.json"},
		{"ClearCache", "request", "ClearCache.json"},
		{"ClearCache", "response", "ClearCacheResponse.json"},
		{"DataTransfer", "request", "DataTransfer.json"},
		{"DataTransfer", "response", "DataTransferResponse.json"},
		{"GetConfiguration", "request", "GetConfiguration.json"},
		{"GetConfiguration", "response", "GetConfigurationResponse.json"},
		{"Heartbeat", "request", "Heartbeat.json"},
		{"Heartbeat", "response", "HeartbeatResponse.json"},
		{"MeterValues", "request", "MeterValues.json"},
		{"MeterValues", "response", "MeterValuesResponse.json"},
		{"RemoteStartTransaction", "request", "RemoteStartTransaction.json"},
		{"RemoteStartTransaction", "response", "RemoteStartTransactionResponse.json"},
		{"RemoteStopTransaction", "request", "RemoteStopTransaction.json"},
		{"RemoteStopTransaction", "response", "RemoteStopTransactionResponse.json"},
		{"Reset", "request", "Reset.json"},
		{"Reset", "response", "ResetResponse.json"},
		{"StartTransaction", "request", "StartTransaction.json"},
		{"StartTransaction", "response", "StartTransactionResponse.json"},
		{"StatusNotification", "request", "StatusNotification.json"},
		{"StatusNotification", "response", "StatusNotificationResponse.json"},
		{"StopTransaction", "request", "StopTransaction.json"},
		{"StopTransaction", "response", "StopTransactionResponse.json"},
		{"UnlockConnector", "request", "UnlockConnector.json"},
		{"UnlockConnector", "response", "UnlockConnectorResponse.json"},
		{"GetDiagnostics", "request", "GetDiagnostics.json"},
		{"GetDiagnostics", "response", "GetDiagnosticsResponse.json"},
		{"DiagnosticsStatusNotification", "request", "DiagnosticsStatusNotification.json"},
		{"DiagnosticsStatusNotification", "response", "DiagnosticsStatusNotificationResponse.json"},
		{"FirmwareStatusNotification", "request", "FirmwareStatusNotification.json"},
		{"FirmwareStatusNotification", "response", "FirmwareStatusNotificationResponse.json"},
		{"UpdateFirmware", "request", "UpdateFirmware.json"},
		{"UpdateFirmware", "response", "UpdateFirmwareResponse.json"},
		{"GetLocalListVersion", "request", "GetLocalListVersion.json"},
		{"GetLocalListVersion", "response", "GetLocalListVersionResponse.json"},
		{"SendLocalList", "request", "SendLocalList.json"},
		{"SendLocalList", "response", "SendLocalListResponse.json"},
		{"TriggerMessage", "request", "TriggerMessage.json"},
		{"TriggerMessage", "response", "TriggerMessageResponse.json"},
		{"CancelReservation", "request", "CancelReservation.json"},
		{"CancelReservation", "response", "CancelReservationResponse.json"},
		{"ReserveNow", "request", "ReserveNow.json"},
		{"ReserveNow", "response", "ReserveNowResponse.json"},
		{"CertificateSigned", "request", "CertificateSigned.json"},
		{"CertificateSigned", "response", "CertificateSignedResponse.json"},
		{"DeleteCertificate", "request", "DeleteCertificate.json"},
		{"DeleteCertificate", "response", "DeleteCertificateResponse.json"},
		{"ExtendedTriggerMessage", "request", "ExtendedTriggerMessage.json"},
		{"ExtendedTriggerMessage", "response", "ExtendedTriggerMessageResponse.json"},
		{"GetInstalledCertificateIds", "request", "GetInstalledCertificateIds.json"},
		{"GetInstalledCertificateIds", "response", "GetInstalledCertificateIdsResponse.json"},
		{"GetLog", "request", "GetLog.json"},
		{"GetLog", "response", "GetLogResponse.json"},
		{"InstallCertificate", "request", "InstallCertificate.json"},
		{"InstallCertificate", "response", "InstallCertificateResponse.json"},
		{"LogStatusNotification", "request", "LogStatusNotification.json"},
		{"LogStatusNotification", "response", "LogStatusNotificationResponse.json"},
		{"SecurityEventNotification", "request", "SecurityEventNotification.json"},
		{"SecurityEventNotification", "response", "SecurityEventNotificationResponse.json"},
		{"SignCertificate", "request", "SignCertificate.json"},
		{"SignCertificate", "response", "SignCertificateResponse.json"},
		{"SignedFirmwareStatusNotification", "request", "SignedFirmwareStatusNotification.json"},
		{"SignedFirmwareStatusNotification", "response", "SignedFirmwareStatusNotificationResponse.json"},
		{"SignedUpdateFirmware", "request", "SignedUpdateFirmware.json"},
		{"SignedUpdateFirmware", "response", "SignedUpdateFirmwareResponse.json"},
		{"ClearChargingProfile", "request", "ClearChargingProfile.json"},
		{"ClearChargingProfile", "response", "ClearChargingProfileResponse.json"},
		{"GetCompositeSchedule", "request", "GetCompositeSchedule.json"},
		{"GetCompositeSchedule", "response", "GetCompositeScheduleResponse.json"},
		{"SetChargingProfile", "request", "SetChargingProfile.json"},
		{"SetChargingProfile", "response", "SetChargingProfileResponse.json"},
	} {
		if err := r.Register("1.6", e.action, e.kind, schemas.FS, e.file); err != nil {
			return err
		}
	}
	return nil
}
