// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v16/messages"
)

// TriggerMessage is the OCPP TriggerMessage message (SentByCSMS).
var TriggerMessage = ocppj.Message[
	messages.TriggerMessageRequest,
	messages.TriggerMessageResponse,
]{Action: "TriggerMessage", Direction: ocppj.SentByCSMS}
