// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v16/messages"
)

// CancelReservation is the OCPP CancelReservation message (SentByCSMS).
var CancelReservation = ocppj.Message[
	messages.CancelReservationRequest,
	messages.CancelReservationResponse,
]{Action: "CancelReservation", Direction: ocppj.SentByCSMS}

// ReserveNow is the OCPP ReserveNow message (SentByCSMS).
var ReserveNow = ocppj.Message[
	messages.ReserveNowRequest,
	messages.ReserveNowResponse,
]{Action: "ReserveNow", Direction: ocppj.SentByCSMS}
