// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v16/messages"
)

// CertificateSigned is the OCPP CertificateSigned message (SentByCSMS).
var CertificateSigned = ocppj.Message[
	messages.CertificateSignedRequest,
	messages.CertificateSignedResponse,
]{Action: "CertificateSigned", Direction: ocppj.SentByCSMS}

// DeleteCertificate is the OCPP DeleteCertificate message (SentByCSMS).
var DeleteCertificate = ocppj.Message[
	messages.DeleteCertificateRequest,
	messages.DeleteCertificateResponse,
]{Action: "DeleteCertificate", Direction: ocppj.SentByCSMS}

// ExtendedTriggerMessage is the OCPP ExtendedTriggerMessage message (SentByCSMS).
var ExtendedTriggerMessage = ocppj.Message[
	messages.ExtendedTriggerMessageRequest,
	messages.ExtendedTriggerMessageResponse,
]{Action: "ExtendedTriggerMessage", Direction: ocppj.SentByCSMS}

// GetInstalledCertificateIds is the OCPP GetInstalledCertificateIds message (SentByCSMS).
var GetInstalledCertificateIds = ocppj.Message[
	messages.GetInstalledCertificateIdsRequest,
	messages.GetInstalledCertificateIdsResponse,
]{Action: "GetInstalledCertificateIds", Direction: ocppj.SentByCSMS}

// GetLog is the OCPP GetLog message (SentByCSMS).
var GetLog = ocppj.Message[
	messages.GetLogRequest,
	messages.GetLogResponse,
]{Action: "GetLog", Direction: ocppj.SentByCSMS}

// InstallCertificate is the OCPP InstallCertificate message (SentByCSMS).
var InstallCertificate = ocppj.Message[
	messages.InstallCertificateRequest,
	messages.InstallCertificateResponse,
]{Action: "InstallCertificate", Direction: ocppj.SentByCSMS}

// LogStatusNotification is the OCPP LogStatusNotification message (SentByCP).
var LogStatusNotification = ocppj.Message[
	messages.LogStatusNotificationRequest,
	messages.LogStatusNotificationResponse,
]{Action: "LogStatusNotification", Direction: ocppj.SentByCP}

// SecurityEventNotification is the OCPP SecurityEventNotification message (SentByCP).
var SecurityEventNotification = ocppj.Message[
	messages.SecurityEventNotificationRequest,
	messages.SecurityEventNotificationResponse,
]{Action: "SecurityEventNotification", Direction: ocppj.SentByCP}

// SignCertificate is the OCPP SignCertificate message (SentByCP).
var SignCertificate = ocppj.Message[
	messages.SignCertificateRequest,
	messages.SignCertificateResponse,
]{Action: "SignCertificate", Direction: ocppj.SentByCP}

// SignedFirmwareStatusNotification is the OCPP SignedFirmwareStatusNotification message (SentByCP).
var SignedFirmwareStatusNotification = ocppj.Message[
	messages.SignedFirmwareStatusNotificationRequest,
	messages.SignedFirmwareStatusNotificationResponse,
]{Action: "SignedFirmwareStatusNotification", Direction: ocppj.SentByCP}

// SignedUpdateFirmware is the OCPP SignedUpdateFirmware message (SentByCSMS).
var SignedUpdateFirmware = ocppj.Message[
	messages.SignedUpdateFirmwareRequest,
	messages.SignedUpdateFirmwareResponse,
]{Action: "SignedUpdateFirmware", Direction: ocppj.SentByCSMS}
