// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v16/messages"
)

// ClearChargingProfile is the OCPP ClearChargingProfile message (SentByCSMS).
var ClearChargingProfile = ocppj.Message[
	messages.ClearChargingProfileRequest,
	messages.ClearChargingProfileResponse,
]{Action: "ClearChargingProfile", Direction: ocppj.SentByCSMS}

// GetCompositeSchedule is the OCPP GetCompositeSchedule message (SentByCSMS).
var GetCompositeSchedule = ocppj.Message[
	messages.GetCompositeScheduleRequest,
	messages.GetCompositeScheduleResponse,
]{Action: "GetCompositeSchedule", Direction: ocppj.SentByCSMS}

// SetChargingProfile is the OCPP SetChargingProfile message (SentByCSMS).
var SetChargingProfile = ocppj.Message[
	messages.SetChargingProfileRequest,
	messages.SetChargingProfileResponse,
]{Action: "SetChargingProfile", Direction: ocppj.SentByCSMS}
