// Code generated by gocpp codegen. DO NOT EDIT.

package calls

import (
	"context"

	"github.com/shiv3/gocpp/cp"
	"github.com/shiv3/gocpp/csms"
	"github.com/shiv3/gocpp/v201/messages"
	"github.com/shiv3/gocpp/v201/profiles"
)

// CPAuthorize sends a Authorize request from the charge point to the CSMS.
func CPAuthorize(ctx context.Context, c *cp.Client, req messages.AuthorizeRequest) (messages.AuthorizeResponse, error) {
	return cp.Call(ctx, c, profiles.Authorize, req)
}

// CPStatusNotification sends a StatusNotification request from the charge point to the CSMS.
func CPStatusNotification(ctx context.Context, c *cp.Client, req messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.StatusNotification, req)
}

// CPDataTransfer sends a DataTransfer request from the charge point to the CSMS.
func CPDataTransfer(ctx context.Context, c *cp.Client, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return cp.Call(ctx, c, profiles.DataTransfer, req)
}

// CPNotifyEvent sends a NotifyEvent request from the charge point to the CSMS.
func CPNotifyEvent(ctx context.Context, c *cp.Client, req messages.NotifyEventRequest) (messages.NotifyEventResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyEvent, req)
}

// CPNotifyMonitoringReport sends a NotifyMonitoringReport request from the charge point to the CSMS.
func CPNotifyMonitoringReport(ctx context.Context, c *cp.Client, req messages.NotifyMonitoringReportRequest) (messages.NotifyMonitoringReportResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyMonitoringReport, req)
}

// CPLogStatusNotification sends a LogStatusNotification request from the charge point to the CSMS.
func CPLogStatusNotification(ctx context.Context, c *cp.Client, req messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.LogStatusNotification, req)
}

// CPNotifyCustomerInformation sends a NotifyCustomerInformation request from the charge point to the CSMS.
func CPNotifyCustomerInformation(ctx context.Context, c *cp.Client, req messages.NotifyCustomerInformationRequest) (messages.NotifyCustomerInformationResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyCustomerInformation, req)
}

// CPNotifyDisplayMessages sends a NotifyDisplayMessages request from the charge point to the CSMS.
func CPNotifyDisplayMessages(ctx context.Context, c *cp.Client, req messages.NotifyDisplayMessagesRequest) (messages.NotifyDisplayMessagesResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyDisplayMessages, req)
}

// CPFirmwareStatusNotification sends a FirmwareStatusNotification request from the charge point to the CSMS.
func CPFirmwareStatusNotification(ctx context.Context, c *cp.Client, req messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.FirmwareStatusNotification, req)
}

// CPPublishFirmwareStatusNotification sends a PublishFirmwareStatusNotification request from the charge point to the CSMS.
func CPPublishFirmwareStatusNotification(ctx context.Context, c *cp.Client, req messages.PublishFirmwareStatusNotificationRequest) (messages.PublishFirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.PublishFirmwareStatusNotification, req)
}

// CPSignCertificate sends a SignCertificate request from the charge point to the CSMS.
func CPSignCertificate(ctx context.Context, c *cp.Client, req messages.SignCertificateRequest) (messages.SignCertificateResponse, error) {
	return cp.Call(ctx, c, profiles.SignCertificate, req)
}

// CPGet15118EVCertificate sends a Get15118EVCertificate request from the charge point to the CSMS.
func CPGet15118EVCertificate(ctx context.Context, c *cp.Client, req messages.Get15118EVCertificateRequest) (messages.Get15118EVCertificateResponse, error) {
	return cp.Call(ctx, c, profiles.Get15118EVCertificate, req)
}

// CPGetCertificateStatus sends a GetCertificateStatus request from the charge point to the CSMS.
func CPGetCertificateStatus(ctx context.Context, c *cp.Client, req messages.GetCertificateStatusRequest) (messages.GetCertificateStatusResponse, error) {
	return cp.Call(ctx, c, profiles.GetCertificateStatus, req)
}

// CPMeterValues sends a MeterValues request from the charge point to the CSMS.
func CPMeterValues(ctx context.Context, c *cp.Client, req messages.MeterValuesRequest) (messages.MeterValuesResponse, error) {
	return cp.Call(ctx, c, profiles.MeterValues, req)
}

// CPBootNotification sends a BootNotification request from the charge point to the CSMS.
func CPBootNotification(ctx context.Context, c *cp.Client, req messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.BootNotification, req)
}

// CPHeartbeat sends a Heartbeat request from the charge point to the CSMS.
func CPHeartbeat(ctx context.Context, c *cp.Client, req messages.HeartbeatRequest) (messages.HeartbeatResponse, error) {
	return cp.Call(ctx, c, profiles.Heartbeat, req)
}

// CPNotifyReport sends a NotifyReport request from the charge point to the CSMS.
func CPNotifyReport(ctx context.Context, c *cp.Client, req messages.NotifyReportRequest) (messages.NotifyReportResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyReport, req)
}

// CPReservationStatusUpdate sends a ReservationStatusUpdate request from the charge point to the CSMS.
func CPReservationStatusUpdate(ctx context.Context, c *cp.Client, req messages.ReservationStatusUpdateRequest) (messages.ReservationStatusUpdateResponse, error) {
	return cp.Call(ctx, c, profiles.ReservationStatusUpdate, req)
}

// CPSecurityEventNotification sends a SecurityEventNotification request from the charge point to the CSMS.
func CPSecurityEventNotification(ctx context.Context, c *cp.Client, req messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.SecurityEventNotification, req)
}

// CPNotifyEVChargingNeeds sends a NotifyEVChargingNeeds request from the charge point to the CSMS.
func CPNotifyEVChargingNeeds(ctx context.Context, c *cp.Client, req messages.NotifyEVChargingNeedsRequest) (messages.NotifyEVChargingNeedsResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyEVChargingNeeds, req)
}

// CPNotifyEVChargingSchedule sends a NotifyEVChargingSchedule request from the charge point to the CSMS.
func CPNotifyEVChargingSchedule(ctx context.Context, c *cp.Client, req messages.NotifyEVChargingScheduleRequest) (messages.NotifyEVChargingScheduleResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyEVChargingSchedule, req)
}

// CPNotifyChargingLimit sends a NotifyChargingLimit request from the charge point to the CSMS.
func CPNotifyChargingLimit(ctx context.Context, c *cp.Client, req messages.NotifyChargingLimitRequest) (messages.NotifyChargingLimitResponse, error) {
	return cp.Call(ctx, c, profiles.NotifyChargingLimit, req)
}

// CPClearedChargingLimit sends a ClearedChargingLimit request from the charge point to the CSMS.
func CPClearedChargingLimit(ctx context.Context, c *cp.Client, req messages.ClearedChargingLimitRequest) (messages.ClearedChargingLimitResponse, error) {
	return cp.Call(ctx, c, profiles.ClearedChargingLimit, req)
}

// CPReportChargingProfiles sends a ReportChargingProfiles request from the charge point to the CSMS.
func CPReportChargingProfiles(ctx context.Context, c *cp.Client, req messages.ReportChargingProfilesRequest) (messages.ReportChargingProfilesResponse, error) {
	return cp.Call(ctx, c, profiles.ReportChargingProfiles, req)
}

// CPTransactionEvent sends a TransactionEvent request from the charge point to the CSMS.
func CPTransactionEvent(ctx context.Context, c *cp.Client, req messages.TransactionEventRequest) (messages.TransactionEventResponse, error) {
	return cp.Call(ctx, c, profiles.TransactionEvent, req)
}

// CSMSClearCache sends a ClearCache request from the CSMS to a connected charge point.
func CSMSClearCache(ctx context.Context, conn *csms.Conn, req messages.ClearCacheRequest) (messages.ClearCacheResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearCache, req)
}

// CSMSChangeAvailability sends a ChangeAvailability request from the CSMS to a connected charge point.
func CSMSChangeAvailability(ctx context.Context, conn *csms.Conn, req messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error) {
	return csms.Call(ctx, conn, profiles.ChangeAvailability, req)
}

// CSMSDataTransfer sends a DataTransfer request from the CSMS to a connected charge point.
func CSMSDataTransfer(ctx context.Context, conn *csms.Conn, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return csms.Call(ctx, conn, profiles.DataTransfer, req)
}

// CSMSGetMonitoringReport sends a GetMonitoringReport request from the CSMS to a connected charge point.
func CSMSGetMonitoringReport(ctx context.Context, conn *csms.Conn, req messages.GetMonitoringReportRequest) (messages.GetMonitoringReportResponse, error) {
	return csms.Call(ctx, conn, profiles.GetMonitoringReport, req)
}

// CSMSSetMonitoringBase sends a SetMonitoringBase request from the CSMS to a connected charge point.
func CSMSSetMonitoringBase(ctx context.Context, conn *csms.Conn, req messages.SetMonitoringBaseRequest) (messages.SetMonitoringBaseResponse, error) {
	return csms.Call(ctx, conn, profiles.SetMonitoringBase, req)
}

// CSMSSetVariableMonitoring sends a SetVariableMonitoring request from the CSMS to a connected charge point.
func CSMSSetVariableMonitoring(ctx context.Context, conn *csms.Conn, req messages.SetVariableMonitoringRequest) (messages.SetVariableMonitoringResponse, error) {
	return csms.Call(ctx, conn, profiles.SetVariableMonitoring, req)
}

// CSMSClearVariableMonitoring sends a ClearVariableMonitoring request from the CSMS to a connected charge point.
func CSMSClearVariableMonitoring(ctx context.Context, conn *csms.Conn, req messages.ClearVariableMonitoringRequest) (messages.ClearVariableMonitoringResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearVariableMonitoring, req)
}

// CSMSSetMonitoringLevel sends a SetMonitoringLevel request from the CSMS to a connected charge point.
func CSMSSetMonitoringLevel(ctx context.Context, conn *csms.Conn, req messages.SetMonitoringLevelRequest) (messages.SetMonitoringLevelResponse, error) {
	return csms.Call(ctx, conn, profiles.SetMonitoringLevel, req)
}

// CSMSGetLog sends a GetLog request from the CSMS to a connected charge point.
func CSMSGetLog(ctx context.Context, conn *csms.Conn, req messages.GetLogRequest) (messages.GetLogResponse, error) {
	return csms.Call(ctx, conn, profiles.GetLog, req)
}

// CSMSCustomerInformation sends a CustomerInformation request from the CSMS to a connected charge point.
func CSMSCustomerInformation(ctx context.Context, conn *csms.Conn, req messages.CustomerInformationRequest) (messages.CustomerInformationResponse, error) {
	return csms.Call(ctx, conn, profiles.CustomerInformation, req)
}

// CSMSSetDisplayMessage sends a SetDisplayMessage request from the CSMS to a connected charge point.
func CSMSSetDisplayMessage(ctx context.Context, conn *csms.Conn, req messages.SetDisplayMessageRequest) (messages.SetDisplayMessageResponse, error) {
	return csms.Call(ctx, conn, profiles.SetDisplayMessage, req)
}

// CSMSGetDisplayMessages sends a GetDisplayMessages request from the CSMS to a connected charge point.
func CSMSGetDisplayMessages(ctx context.Context, conn *csms.Conn, req messages.GetDisplayMessagesRequest) (messages.GetDisplayMessagesResponse, error) {
	return csms.Call(ctx, conn, profiles.GetDisplayMessages, req)
}

// CSMSClearDisplayMessage sends a ClearDisplayMessage request from the CSMS to a connected charge point.
func CSMSClearDisplayMessage(ctx context.Context, conn *csms.Conn, req messages.ClearDisplayMessageRequest) (messages.ClearDisplayMessageResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearDisplayMessage, req)
}

// CSMSUpdateFirmware sends a UpdateFirmware request from the CSMS to a connected charge point.
func CSMSUpdateFirmware(ctx context.Context, conn *csms.Conn, req messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error) {
	return csms.Call(ctx, conn, profiles.UpdateFirmware, req)
}

// CSMSPublishFirmware sends a PublishFirmware request from the CSMS to a connected charge point.
func CSMSPublishFirmware(ctx context.Context, conn *csms.Conn, req messages.PublishFirmwareRequest) (messages.PublishFirmwareResponse, error) {
	return csms.Call(ctx, conn, profiles.PublishFirmware, req)
}

// CSMSUnpublishFirmware sends a UnpublishFirmware request from the CSMS to a connected charge point.
func CSMSUnpublishFirmware(ctx context.Context, conn *csms.Conn, req messages.UnpublishFirmwareRequest) (messages.UnpublishFirmwareResponse, error) {
	return csms.Call(ctx, conn, profiles.UnpublishFirmware, req)
}

// CSMSGetInstalledCertificateIds sends a GetInstalledCertificateIds request from the CSMS to a connected charge point.
func CSMSGetInstalledCertificateIds(ctx context.Context, conn *csms.Conn, req messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error) {
	return csms.Call(ctx, conn, profiles.GetInstalledCertificateIds, req)
}

// CSMSInstallCertificate sends a InstallCertificate request from the CSMS to a connected charge point.
func CSMSInstallCertificate(ctx context.Context, conn *csms.Conn, req messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error) {
	return csms.Call(ctx, conn, profiles.InstallCertificate, req)
}

// CSMSDeleteCertificate sends a DeleteCertificate request from the CSMS to a connected charge point.
func CSMSDeleteCertificate(ctx context.Context, conn *csms.Conn, req messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error) {
	return csms.Call(ctx, conn, profiles.DeleteCertificate, req)
}

// CSMSCertificateSigned sends a CertificateSigned request from the CSMS to a connected charge point.
func CSMSCertificateSigned(ctx context.Context, conn *csms.Conn, req messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error) {
	return csms.Call(ctx, conn, profiles.CertificateSigned, req)
}

// CSMSGetLocalListVersion sends a GetLocalListVersion request from the CSMS to a connected charge point.
func CSMSGetLocalListVersion(ctx context.Context, conn *csms.Conn, req messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error) {
	return csms.Call(ctx, conn, profiles.GetLocalListVersion, req)
}

// CSMSSendLocalList sends a SendLocalList request from the CSMS to a connected charge point.
func CSMSSendLocalList(ctx context.Context, conn *csms.Conn, req messages.SendLocalListRequest) (messages.SendLocalListResponse, error) {
	return csms.Call(ctx, conn, profiles.SendLocalList, req)
}

// CSMSGetBaseReport sends a GetBaseReport request from the CSMS to a connected charge point.
func CSMSGetBaseReport(ctx context.Context, conn *csms.Conn, req messages.GetBaseReportRequest) (messages.GetBaseReportResponse, error) {
	return csms.Call(ctx, conn, profiles.GetBaseReport, req)
}

// CSMSGetReport sends a GetReport request from the CSMS to a connected charge point.
func CSMSGetReport(ctx context.Context, conn *csms.Conn, req messages.GetReportRequest) (messages.GetReportResponse, error) {
	return csms.Call(ctx, conn, profiles.GetReport, req)
}

// CSMSGetVariables sends a GetVariables request from the CSMS to a connected charge point.
func CSMSGetVariables(ctx context.Context, conn *csms.Conn, req messages.GetVariablesRequest) (messages.GetVariablesResponse, error) {
	return csms.Call(ctx, conn, profiles.GetVariables, req)
}

// CSMSSetVariables sends a SetVariables request from the CSMS to a connected charge point.
func CSMSSetVariables(ctx context.Context, conn *csms.Conn, req messages.SetVariablesRequest) (messages.SetVariablesResponse, error) {
	return csms.Call(ctx, conn, profiles.SetVariables, req)
}

// CSMSReset sends a Reset request from the CSMS to a connected charge point.
func CSMSReset(ctx context.Context, conn *csms.Conn, req messages.ResetRequest) (messages.ResetResponse, error) {
	return csms.Call(ctx, conn, profiles.Reset, req)
}

// CSMSSetNetworkProfile sends a SetNetworkProfile request from the CSMS to a connected charge point.
func CSMSSetNetworkProfile(ctx context.Context, conn *csms.Conn, req messages.SetNetworkProfileRequest) (messages.SetNetworkProfileResponse, error) {
	return csms.Call(ctx, conn, profiles.SetNetworkProfile, req)
}

// CSMSRequestStartTransaction sends a RequestStartTransaction request from the CSMS to a connected charge point.
func CSMSRequestStartTransaction(ctx context.Context, conn *csms.Conn, req messages.RequestStartTransactionRequest) (messages.RequestStartTransactionResponse, error) {
	return csms.Call(ctx, conn, profiles.RequestStartTransaction, req)
}

// CSMSRequestStopTransaction sends a RequestStopTransaction request from the CSMS to a connected charge point.
func CSMSRequestStopTransaction(ctx context.Context, conn *csms.Conn, req messages.RequestStopTransactionRequest) (messages.RequestStopTransactionResponse, error) {
	return csms.Call(ctx, conn, profiles.RequestStopTransaction, req)
}

// CSMSUnlockConnector sends a UnlockConnector request from the CSMS to a connected charge point.
func CSMSUnlockConnector(ctx context.Context, conn *csms.Conn, req messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error) {
	return csms.Call(ctx, conn, profiles.UnlockConnector, req)
}

// CSMSTriggerMessage sends a TriggerMessage request from the CSMS to a connected charge point.
func CSMSTriggerMessage(ctx context.Context, conn *csms.Conn, req messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error) {
	return csms.Call(ctx, conn, profiles.TriggerMessage, req)
}

// CSMSReserveNow sends a ReserveNow request from the CSMS to a connected charge point.
func CSMSReserveNow(ctx context.Context, conn *csms.Conn, req messages.ReserveNowRequest) (messages.ReserveNowResponse, error) {
	return csms.Call(ctx, conn, profiles.ReserveNow, req)
}

// CSMSCancelReservation sends a CancelReservation request from the CSMS to a connected charge point.
func CSMSCancelReservation(ctx context.Context, conn *csms.Conn, req messages.CancelReservationRequest) (messages.CancelReservationResponse, error) {
	return csms.Call(ctx, conn, profiles.CancelReservation, req)
}

// CSMSSetChargingProfile sends a SetChargingProfile request from the CSMS to a connected charge point.
func CSMSSetChargingProfile(ctx context.Context, conn *csms.Conn, req messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error) {
	return csms.Call(ctx, conn, profiles.SetChargingProfile, req)
}

// CSMSGetChargingProfiles sends a GetChargingProfiles request from the CSMS to a connected charge point.
func CSMSGetChargingProfiles(ctx context.Context, conn *csms.Conn, req messages.GetChargingProfilesRequest) (messages.GetChargingProfilesResponse, error) {
	return csms.Call(ctx, conn, profiles.GetChargingProfiles, req)
}

// CSMSClearChargingProfile sends a ClearChargingProfile request from the CSMS to a connected charge point.
func CSMSClearChargingProfile(ctx context.Context, conn *csms.Conn, req messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearChargingProfile, req)
}

// CSMSGetCompositeSchedule sends a GetCompositeSchedule request from the CSMS to a connected charge point.
func CSMSGetCompositeSchedule(ctx context.Context, conn *csms.Conn, req messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error) {
	return csms.Call(ctx, conn, profiles.GetCompositeSchedule, req)
}

// CSMSCostUpdated sends a CostUpdated request from the CSMS to a connected charge point.
func CSMSCostUpdated(ctx context.Context, conn *csms.Conn, req messages.CostUpdatedRequest) (messages.CostUpdatedResponse, error) {
	return csms.Call(ctx, conn, profiles.CostUpdated, req)
}

// CSMSGetTransactionStatus sends a GetTransactionStatus request from the CSMS to a connected charge point.
func CSMSGetTransactionStatus(ctx context.Context, conn *csms.Conn, req messages.GetTransactionStatusRequest) (messages.GetTransactionStatusResponse, error) {
	return csms.Call(ctx, conn, profiles.GetTransactionStatus, req)
}
