package storage

import (
	"context"
	"time"
)

// TransactionStatus is the lifecycle state of a charging transaction.
type TransactionStatus string

const (
	TransactionActive    TransactionStatus = "Active"
	TransactionCompleted TransactionStatus = "Completed"
	TransactionAborted   TransactionStatus = "Aborted"
)

// Transaction is a charging session record.
type Transaction struct {
	ID         string
	CPID       string
	EVSEID     int
	IDTag      string
	StartedAt  time.Time
	EndedAt    *time.Time
	MeterStart int
	MeterStop  *int
	Status     TransactionStatus
	Metadata   map[string]any
}

// TransactionMutation is a partial update applied during a session.
type TransactionMutation struct {
	MeterValue *int
	Status     *TransactionStatus
	Metadata   map[string]any
}

// TransactionEnd finalizes a session.
type TransactionEnd struct {
	EndedAt   time.Time
	MeterStop int
	Status    TransactionStatus
}

// TransactionStore persists charging transactions. The transaction ID is supplied
// by the caller (CP or CSMS depending on OCPP version), not generated by the store.
type TransactionStore interface {
	Begin(ctx context.Context, tx Transaction) error
	Update(ctx context.Context, txID string, mut TransactionMutation) error
	End(ctx context.Context, txID string, end TransactionEnd) error
	Get(ctx context.Context, txID string) (Transaction, error)
	ListActive(ctx context.Context, cpID string) ([]Transaction, error)
}
