// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type AuthorizeRequest struct {
	Certificate                 *string               `json:"certificate,omitempty" validate:"omitempty,max=5500"`
	CustomData                  *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	IDToken                     IdTokenType           `json:"idToken" validate:"required"`
	Iso15118CertificateHashData []OCSPRequestDataType `json:"iso15118CertificateHashData,omitempty" validate:"omitempty"`
}

type CustomDataType struct {
	VendorID string `json:"vendorId" validate:"required,max=255"`
}

type IdTokenType struct {
	AdditionalInfo []AdditionalInfoType `json:"additionalInfo,omitempty" validate:"omitempty"`
	CustomData     *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	IDToken        string               `json:"idToken" validate:"required,max=36"`
	Type           string               `json:"type" validate:"required"`
}

type AdditionalInfoType struct {
	AdditionalIDToken string          `json:"additionalIdToken" validate:"required,max=36"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Type              string          `json:"type" validate:"required,max=50"`
}

type OCSPRequestDataType struct {
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	HashAlgorithm  string          `json:"hashAlgorithm" validate:"required"`
	IssuerKeyHash  string          `json:"issuerKeyHash" validate:"required,max=128"`
	IssuerNameHash string          `json:"issuerNameHash" validate:"required,max=128"`
	ResponderURL   string          `json:"responderURL" validate:"required,max=512"`
	SerialNumber   string          `json:"serialNumber" validate:"required,max=40"`
}

type AuthorizeResponse struct {
	CertificateStatus *string         `json:"certificateStatus,omitempty" validate:"omitempty"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IDTokenInfo       IdTokenInfoType `json:"idTokenInfo" validate:"required"`
}

type IdTokenInfoType struct {
	CacheExpiryDateTime *time.Time          `json:"cacheExpiryDateTime,omitempty" validate:"omitempty"`
	ChargingPriority    *int32              `json:"chargingPriority,omitempty" validate:"omitempty"`
	CustomData          *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	EVSEID              []int32             `json:"evseId,omitempty" validate:"omitempty"`
	GroupIDToken        *IdTokenType        `json:"groupIdToken,omitempty" validate:"omitempty"`
	Language1           *string             `json:"language1,omitempty" validate:"omitempty,max=8"`
	Language2           *string             `json:"language2,omitempty" validate:"omitempty,max=8"`
	PersonalMessage     *MessageContentType `json:"personalMessage,omitempty" validate:"omitempty"`
	Status              string              `json:"status" validate:"required"`
}

type MessageContentType struct {
	Content    string          `json:"content" validate:"required,max=512"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Format     string          `json:"format" validate:"required"`
	Language   *string         `json:"language,omitempty" validate:"omitempty,max=8"`
}
