// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ChangeAvailabilityRequest struct {
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSE              *EVSEType       `json:"evse,omitempty" validate:"omitempty"`
	OperationalStatus string          `json:"operationalStatus" validate:"required"`
}

type EVSEType struct {
	ConnectorID *int32          `json:"connectorId,omitempty" validate:"omitempty"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID          int32           `json:"id" validate:"required"`
}

type ChangeAvailabilityResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
