// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearChargingProfileRequest struct {
	ChargingProfileCriteria *ClearChargingProfileType `json:"chargingProfileCriteria,omitempty" validate:"omitempty"`
	ChargingProfileID       *int32                    `json:"chargingProfileId,omitempty" validate:"omitempty"`
	CustomData              *CustomDataType           `json:"customData,omitempty" validate:"omitempty"`
}

type ClearChargingProfileType struct {
	ChargingProfilePurpose *string         `json:"chargingProfilePurpose,omitempty" validate:"omitempty"`
	CustomData             *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID                 *int32          `json:"evseId,omitempty" validate:"omitempty"`
	StackLevel             *int32          `json:"stackLevel,omitempty" validate:"omitempty"`
}

type ClearChargingProfileResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
