// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type FirmwareStatusNotificationRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	RequestID  *int32          `json:"requestId,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
}

type FirmwareStatusNotificationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
