// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type Get15118EVCertificateRequest struct {
	Action                string          `json:"action" validate:"required"`
	CustomData            *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ExiRequest            string          `json:"exiRequest" validate:"required,max=5600"`
	Iso15118SchemaVersion string          `json:"iso15118SchemaVersion" validate:"required,max=50"`
}

type Get15118EVCertificateResponse struct {
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ExiResponse string          `json:"exiResponse" validate:"required,max=7500"`
	Status      string          `json:"status" validate:"required"`
	StatusInfo  *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
