// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetCertificateStatusRequest struct {
	CustomData      *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	OcspRequestData OCSPRequestDataType `json:"ocspRequestData" validate:"required"`
}

type GetCertificateStatusResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	OcspResult *string         `json:"ocspResult,omitempty" validate:"omitempty,max=5500"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
