// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetDisplayMessagesRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         []int32         `json:"id,omitempty" validate:"omitempty"`
	Priority   *string         `json:"priority,omitempty" validate:"omitempty"`
	RequestID  int32           `json:"requestId" validate:"required"`
	State      *string         `json:"state,omitempty" validate:"omitempty"`
}

type GetDisplayMessagesResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
