// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type InstallCertificateRequest struct {
	Certificate     string          `json:"certificate" validate:"required,max=5500"`
	CertificateType string          `json:"certificateType" validate:"required"`
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type InstallCertificateResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
