// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type MeterValuesRequest struct {
	CustomData *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EVSEID     int32            `json:"evseId" validate:"required"`
	MeterValue []MeterValueType `json:"meterValue" validate:"required"`
}

type MeterValueType struct {
	CustomData   *CustomDataType    `json:"customData,omitempty" validate:"omitempty"`
	SampledValue []SampledValueType `json:"sampledValue" validate:"required"`
	Timestamp    time.Time          `json:"timestamp" validate:"required"`
}

type SampledValueType struct {
	Context          *string               `json:"context,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	Location         *string               `json:"location,omitempty" validate:"omitempty"`
	Measurand        *string               `json:"measurand,omitempty" validate:"omitempty"`
	Phase            *string               `json:"phase,omitempty" validate:"omitempty"`
	SignedMeterValue *SignedMeterValueType `json:"signedMeterValue,omitempty" validate:"omitempty"`
	UnitOfMeasure    *UnitOfMeasureType    `json:"unitOfMeasure,omitempty" validate:"omitempty"`
	Value            decimal.Decimal       `json:"value" validate:"required"`
}

type SignedMeterValueType struct {
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EncodingMethod  string          `json:"encodingMethod" validate:"required,max=50"`
	PublicKey       string          `json:"publicKey" validate:"required,max=2500"`
	SignedMeterData string          `json:"signedMeterData" validate:"required,max=2500"`
	SigningMethod   string          `json:"signingMethod" validate:"required,max=50"`
}

type UnitOfMeasureType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Multiplier *int32          `json:"multiplier,omitempty" validate:"omitempty"`
	Unit       *string         `json:"unit,omitempty" validate:"omitempty,max=20"`
}

type MeterValuesResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
