// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type NotifyChargingLimitRequest struct {
	ChargingLimit    ChargingLimitType      `json:"chargingLimit" validate:"required"`
	ChargingSchedule []ChargingScheduleType `json:"chargingSchedule,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	EVSEID           *int32                 `json:"evseId,omitempty" validate:"omitempty"`
}

type ChargingLimitType struct {
	ChargingLimitSource string          `json:"chargingLimitSource" validate:"required"`
	CustomData          *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IsGridCritical      *bool           `json:"isGridCritical,omitempty" validate:"omitempty"`
}

type NotifyChargingLimitResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
