// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type NotifyEVChargingNeedsRequest struct {
	ChargingNeeds     ChargingNeedsType `json:"chargingNeeds" validate:"required"`
	CustomData        *CustomDataType   `json:"customData,omitempty" validate:"omitempty"`
	EVSEID            int32             `json:"evseId" validate:"required"`
	MaxScheduleTuples *int32            `json:"maxScheduleTuples,omitempty" validate:"omitempty"`
}

type ChargingNeedsType struct {
	ACChargingParameters    *ACChargingParametersType `json:"acChargingParameters,omitempty" validate:"omitempty"`
	CustomData              *CustomDataType           `json:"customData,omitempty" validate:"omitempty"`
	DCChargingParameters    *DCChargingParametersType `json:"dcChargingParameters,omitempty" validate:"omitempty"`
	DepartureTime           *time.Time                `json:"departureTime,omitempty" validate:"omitempty"`
	RequestedEnergyTransfer string                    `json:"requestedEnergyTransfer" validate:"required"`
}

type ACChargingParametersType struct {
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EnergyAmount int32           `json:"energyAmount" validate:"required"`
	EVMaxCurrent int32           `json:"evMaxCurrent" validate:"required"`
	EVMaxVoltage int32           `json:"evMaxVoltage" validate:"required"`
	EVMinCurrent int32           `json:"evMinCurrent" validate:"required"`
}

type DCChargingParametersType struct {
	BulkSoC          *int32          `json:"bulkSoC,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EnergyAmount     *int32          `json:"energyAmount,omitempty" validate:"omitempty"`
	EVEnergyCapacity *int32          `json:"evEnergyCapacity,omitempty" validate:"omitempty"`
	EVMaxCurrent     int32           `json:"evMaxCurrent" validate:"required"`
	EVMaxPower       *int32          `json:"evMaxPower,omitempty" validate:"omitempty"`
	EVMaxVoltage     int32           `json:"evMaxVoltage" validate:"required"`
	FullSoC          *int32          `json:"fullSoC,omitempty" validate:"omitempty"`
	StateOfCharge    *int32          `json:"stateOfCharge,omitempty" validate:"omitempty"`
}

type NotifyEVChargingNeedsResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
