// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type NotifyReportRequest struct {
	CustomData  *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	GeneratedAt time.Time        `json:"generatedAt" validate:"required"`
	ReportData  []ReportDataType `json:"reportData,omitempty" validate:"omitempty"`
	RequestID   int32            `json:"requestId" validate:"required"`
	SeqNo       int32            `json:"seqNo" validate:"required"`
	Tbc         *bool            `json:"tbc,omitempty" validate:"omitempty"`
}

type ReportDataType struct {
	Component               ComponentType                `json:"component" validate:"required"`
	CustomData              *CustomDataType              `json:"customData,omitempty" validate:"omitempty"`
	Variable                VariableType                 `json:"variable" validate:"required"`
	VariableAttribute       []VariableAttributeType      `json:"variableAttribute" validate:"required"`
	VariableCharacteristics *VariableCharacteristicsType `json:"variableCharacteristics,omitempty" validate:"omitempty"`
}

type VariableAttributeType struct {
	Constant   *bool           `json:"constant,omitempty" validate:"omitempty"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Mutability *string         `json:"mutability,omitempty" validate:"omitempty"`
	Persistent *bool           `json:"persistent,omitempty" validate:"omitempty"`
	Type       *string         `json:"type,omitempty" validate:"omitempty"`
	Value      *string         `json:"value,omitempty" validate:"omitempty,max=2500"`
}

type VariableCharacteristicsType struct {
	CustomData         *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	DataType           string           `json:"dataType" validate:"required"`
	MaxLimit           *decimal.Decimal `json:"maxLimit,omitempty" validate:"omitempty"`
	MinLimit           *decimal.Decimal `json:"minLimit,omitempty" validate:"omitempty"`
	SupportsMonitoring bool             `json:"supportsMonitoring" validate:"required"`
	Unit               *string          `json:"unit,omitempty" validate:"omitempty,max=16"`
	ValuesList         *string          `json:"valuesList,omitempty" validate:"omitempty,max=1000"`
}

type NotifyReportResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
