// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type NotifyEVChargingScheduleRequest struct {
	ChargingSchedule ChargingScheduleType `json:"chargingSchedule" validate:"required"`
	CustomData       *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	EVSEID           int32                `json:"evseId" validate:"required"`
	TimeBase         time.Time            `json:"timeBase" validate:"required"`
}

type NotifyEVChargingScheduleResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
