// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type PublishFirmwareRequest struct {
	Checksum      string          `json:"checksum" validate:"required,max=32"`
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Location      string          `json:"location" validate:"required,max=512"`
	RequestID     int32           `json:"requestId" validate:"required"`
	Retries       *int32          `json:"retries,omitempty" validate:"omitempty"`
	RetryInterval *int32          `json:"retryInterval,omitempty" validate:"omitempty"`
}

type PublishFirmwareResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
