// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type PublishFirmwareStatusNotificationRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Location   []string        `json:"location,omitempty" validate:"omitempty"`
	RequestID  *int32          `json:"requestId,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
}

type PublishFirmwareStatusNotificationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
