// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ReportChargingProfilesRequest struct {
	ChargingLimitSource string                `json:"chargingLimitSource" validate:"required"`
	ChargingProfile     []ChargingProfileType `json:"chargingProfile" validate:"required"`
	CustomData          *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	EVSEID              int32                 `json:"evseId" validate:"required"`
	RequestID           int32                 `json:"requestId" validate:"required"`
	Tbc                 *bool                 `json:"tbc,omitempty" validate:"omitempty"`
}

type ReportChargingProfilesResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
