// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type RequestStopTransactionRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	TransactionID string          `json:"transactionId" validate:"required,max=36"`
}

type RequestStopTransactionResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
