// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type ReserveNowRequest struct {
	ConnectorType  *string         `json:"connectorType,omitempty" validate:"omitempty"`
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID         *int32          `json:"evseId,omitempty" validate:"omitempty"`
	ExpiryDateTime time.Time       `json:"expiryDateTime" validate:"required"`
	GroupIDToken   *IdTokenType    `json:"groupIdToken,omitempty" validate:"omitempty"`
	ID             int32           `json:"id" validate:"required"`
	IDToken        IdTokenType     `json:"idToken" validate:"required"`
}

type ReserveNowResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
