// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ResetRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID     *int32          `json:"evseId,omitempty" validate:"omitempty"`
	Type       string          `json:"type" validate:"required"`
}

type ResetResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
