// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SendLocalListRequest struct {
	CustomData             *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	LocalAuthorizationList []AuthorizationData `json:"localAuthorizationList,omitempty" validate:"omitempty"`
	UpdateType             string              `json:"updateType" validate:"required"`
	VersionNumber          int32               `json:"versionNumber" validate:"required"`
}

type AuthorizationData struct {
	CustomData  *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	IDToken     IdTokenType      `json:"idToken" validate:"required"`
	IDTokenInfo *IdTokenInfoType `json:"idTokenInfo,omitempty" validate:"omitempty"`
}

type SendLocalListResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
