// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetMonitoringLevelRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Severity   int32           `json:"severity" validate:"required"`
}

type SetMonitoringLevelResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
