// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
)

type SetVariableMonitoringRequest struct {
	CustomData        *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	SetMonitoringData []SetMonitoringDataType `json:"setMonitoringData" validate:"required"`
}

type SetMonitoringDataType struct {
	Component   ComponentType   `json:"component" validate:"required"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID          *int32          `json:"id,omitempty" validate:"omitempty"`
	Severity    int32           `json:"severity" validate:"required"`
	Transaction *bool           `json:"transaction,omitempty" validate:"omitempty"`
	Type        string          `json:"type" validate:"required"`
	Value       decimal.Decimal `json:"value" validate:"required"`
	Variable    VariableType    `json:"variable" validate:"required"`
}

type SetVariableMonitoringResponse struct {
	CustomData          *CustomDataType           `json:"customData,omitempty" validate:"omitempty"`
	SetMonitoringResult []SetMonitoringResultType `json:"setMonitoringResult" validate:"required"`
}

type SetMonitoringResultType struct {
	Component  ComponentType   `json:"component" validate:"required"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         *int32          `json:"id,omitempty" validate:"omitempty"`
	Severity   int32           `json:"severity" validate:"required"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
	Type       string          `json:"type" validate:"required"`
	Variable   VariableType    `json:"variable" validate:"required"`
}
