// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type SetDisplayMessageRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Message    MessageInfoType `json:"message" validate:"required"`
}

type MessageInfoType struct {
	CustomData    *CustomDataType    `json:"customData,omitempty" validate:"omitempty"`
	Display       *ComponentType     `json:"display,omitempty" validate:"omitempty"`
	EndDateTime   *time.Time         `json:"endDateTime,omitempty" validate:"omitempty"`
	ID            int32              `json:"id" validate:"required"`
	Message       MessageContentType `json:"message" validate:"required"`
	Priority      string             `json:"priority" validate:"required"`
	StartDateTime *time.Time         `json:"startDateTime,omitempty" validate:"omitempty"`
	State         *string            `json:"state,omitempty" validate:"omitempty"`
	TransactionID *string            `json:"transactionId,omitempty" validate:"omitempty,max=36"`
}

type SetDisplayMessageResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
