// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetVariablesRequest struct {
	CustomData      *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	SetVariableData []SetVariableDataType `json:"setVariableData" validate:"required"`
}

type SetVariableDataType struct {
	AttributeType  *string         `json:"attributeType,omitempty" validate:"omitempty"`
	AttributeValue string          `json:"attributeValue" validate:"required,max=1000"`
	Component      ComponentType   `json:"component" validate:"required"`
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Variable       VariableType    `json:"variable" validate:"required"`
}

type SetVariablesResponse struct {
	CustomData        *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	SetVariableResult []SetVariableResultType `json:"setVariableResult" validate:"required"`
}

type SetVariableResultType struct {
	AttributeStatus     string          `json:"attributeStatus" validate:"required"`
	AttributeStatusInfo *StatusInfoType `json:"attributeStatusInfo,omitempty" validate:"omitempty"`
	AttributeType       *string         `json:"attributeType,omitempty" validate:"omitempty"`
	Component           ComponentType   `json:"component" validate:"required"`
	CustomData          *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Variable            VariableType    `json:"variable" validate:"required"`
}
