// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SignCertificateRequest struct {
	CertificateType *string         `json:"certificateType,omitempty" validate:"omitempty"`
	Csr             string          `json:"csr" validate:"required,max=5500"`
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type SignCertificateResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
