// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type TransactionEventRequest struct {
	CableMaxCurrent    *int32           `json:"cableMaxCurrent,omitempty" validate:"omitempty"`
	CustomData         *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EventType          string           `json:"eventType" validate:"required"`
	EVSE               *EVSEType        `json:"evse,omitempty" validate:"omitempty"`
	IDToken            *IdTokenType     `json:"idToken,omitempty" validate:"omitempty"`
	MeterValue         []MeterValueType `json:"meterValue,omitempty" validate:"omitempty"`
	NumberOfPhasesUsed *int32           `json:"numberOfPhasesUsed,omitempty" validate:"omitempty"`
	Offline            *bool            `json:"offline,omitempty" validate:"omitempty"`
	ReservationID      *int32           `json:"reservationId,omitempty" validate:"omitempty"`
	SeqNo              int32            `json:"seqNo" validate:"required"`
	Timestamp          time.Time        `json:"timestamp" validate:"required"`
	TransactionInfo    TransactionType  `json:"transactionInfo" validate:"required"`
	TriggerReason      string           `json:"triggerReason" validate:"required"`
}

type TransactionType struct {
	ChargingState     *string         `json:"chargingState,omitempty" validate:"omitempty"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	RemoteStartID     *int32          `json:"remoteStartId,omitempty" validate:"omitempty"`
	StoppedReason     *string         `json:"stoppedReason,omitempty" validate:"omitempty"`
	TimeSpentCharging *int32          `json:"timeSpentCharging,omitempty" validate:"omitempty"`
	TransactionID     string          `json:"transactionId" validate:"required,max=36"`
}

type TransactionEventResponse struct {
	ChargingPriority       *int32              `json:"chargingPriority,omitempty" validate:"omitempty"`
	CustomData             *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	IDTokenInfo            *IdTokenInfoType    `json:"idTokenInfo,omitempty" validate:"omitempty"`
	TotalCost              *decimal.Decimal    `json:"totalCost,omitempty" validate:"omitempty"`
	UpdatedPersonalMessage *MessageContentType `json:"updatedPersonalMessage,omitempty" validate:"omitempty"`
}
