// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type UpdateFirmwareRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Firmware      FirmwareType    `json:"firmware" validate:"required"`
	RequestID     int32           `json:"requestId" validate:"required"`
	Retries       *int32          `json:"retries,omitempty" validate:"omitempty"`
	RetryInterval *int32          `json:"retryInterval,omitempty" validate:"omitempty"`
}

type FirmwareType struct {
	CustomData         *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	InstallDateTime    *time.Time      `json:"installDateTime,omitempty" validate:"omitempty"`
	Location           string          `json:"location" validate:"required,max=512"`
	RetrieveDateTime   time.Time       `json:"retrieveDateTime" validate:"required"`
	Signature          *string         `json:"signature,omitempty" validate:"omitempty,max=800"`
	SigningCertificate *string         `json:"signingCertificate,omitempty" validate:"omitempty,max=5500"`
}

type UpdateFirmwareResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
