// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type AuthorizeRequest struct {
	IDTag string `json:"idTag" validate:"required,max=20"`
}

type AuthorizeResponse struct {
	IDTagInfo IDTagInfo `json:"idTagInfo" validate:"required"`
}

type IDTagInfo struct {
	ExpiryDate  *time.Time      `json:"expiryDate,omitempty" validate:"omitempty"`
	ParentIDTag *string         `json:"parentIdTag,omitempty" validate:"omitempty,max=20"`
	Status      IDTagInfoStatus `json:"status" validate:"required"`
}
