// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type BootNotificationRequest struct {
	ChargeBoxSerialNumber   *string `json:"chargeBoxSerialNumber,omitempty" validate:"omitempty,max=25"`
	ChargePointModel        string  `json:"chargePointModel" validate:"required,max=20"`
	ChargePointSerialNumber *string `json:"chargePointSerialNumber,omitempty" validate:"omitempty,max=25"`
	ChargePointVendor       string  `json:"chargePointVendor" validate:"required,max=20"`
	FirmwareVersion         *string `json:"firmwareVersion,omitempty" validate:"omitempty,max=50"`
	ICCID                   *string `json:"iccid,omitempty" validate:"omitempty,max=20"`
	IMSI                    *string `json:"imsi,omitempty" validate:"omitempty,max=20"`
	MeterSerialNumber       *string `json:"meterSerialNumber,omitempty" validate:"omitempty,max=25"`
	MeterType               *string `json:"meterType,omitempty" validate:"omitempty,max=25"`
}

type BootNotificationResponse struct {
	CurrentTime time.Time          `json:"currentTime" validate:"required"`
	Interval    decimal.Decimal    `json:"interval" validate:"required"`
	Status      RegistrationStatus `json:"status" validate:"required"`
}
