// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type CancelReservationRequest struct {
	ReservationID int32 `json:"reservationId" validate:"required"`
}

type CancelReservationResponse struct {
	Status CancelReservationResponseStatus `json:"status" validate:"required"`
}
