// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type CertificateSignedRequest struct {
	CertificateChain string `json:"certificateChain" validate:"required,max=10000"`
}

type CertificateSignedResponse struct {
	Status string `json:"status" validate:"required"`
}
