// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ChangeAvailabilityRequest struct {
	ConnectorID int32                         `json:"connectorId" validate:"required"`
	Type        ChangeAvailabilityRequestType `json:"type" validate:"required"`
}

type ChangeAvailabilityResponse struct {
	Status ChangeAvailabilityResponseStatus `json:"status" validate:"required"`
}
