// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ChangeConfigurationRequest struct {
	Key   string `json:"key" validate:"required,max=50"`
	Value string `json:"value" validate:"required,max=500"`
}

type ChangeConfigurationResponse struct {
	Status ChangeConfigurationResponseStatus `json:"status" validate:"required"`
}
