// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearChargingProfileRequest struct {
	ChargingProfilePurpose *ClearChargingProfileRequestChargingProfilePurpose `json:"chargingProfilePurpose,omitempty" validate:"omitempty"`
	ConnectorID            *int32                                             `json:"connectorId,omitempty" validate:"omitempty"`
	ID                     *int32                                             `json:"id,omitempty" validate:"omitempty"`
	StackLevel             *int32                                             `json:"stackLevel,omitempty" validate:"omitempty"`
}

type ClearChargingProfileResponse struct {
	Status ClearChargingProfileResponseStatus `json:"status" validate:"required"`
}
