// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearCacheRequest struct {
}

type ClearCacheResponse struct {
	Status ClearCacheResponseStatus `json:"status" validate:"required"`
}
