// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type DataTransferRequest struct {
	Data      *string `json:"data,omitempty" validate:"omitempty"`
	MessageID *string `json:"messageId,omitempty" validate:"omitempty,max=50"`
	VendorID  string  `json:"vendorId" validate:"required,max=255"`
}

type DataTransferResponse struct {
	Data   *string                    `json:"data,omitempty" validate:"omitempty"`
	Status DataTransferResponseStatus `json:"status" validate:"required"`
}
