// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type DeleteCertificateRequest struct {
	CertificateHashData CertificateHashDataType `json:"certificateHashData" validate:"required"`
}

type CertificateHashDataType struct {
	HashAlgorithm  string `json:"hashAlgorithm" validate:"required"`
	IssuerKeyHash  string `json:"issuerKeyHash" validate:"required,max=128"`
	IssuerNameHash string `json:"issuerNameHash" validate:"required,max=128"`
	SerialNumber   string `json:"serialNumber" validate:"required,max=40"`
}

type DeleteCertificateResponse struct {
	Status string `json:"status" validate:"required"`
}
