// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type DiagnosticsStatusNotificationRequest struct {
	Status DiagnosticsStatusNotificationRequestStatus `json:"status" validate:"required"`
}

type DiagnosticsStatusNotificationResponse struct {
}
