// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ExtendedTriggerMessageRequest struct {
	ConnectorID      *int32 `json:"connectorId,omitempty" validate:"omitempty"`
	RequestedMessage string `json:"requestedMessage" validate:"required"`
}

type ExtendedTriggerMessageResponse struct {
	Status string `json:"status" validate:"required"`
}
