// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type FirmwareStatusNotificationRequest struct {
	Status FirmwareStatusNotificationRequestStatus `json:"status" validate:"required"`
}

type FirmwareStatusNotificationResponse struct {
}
