// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetInstalledCertificateIdsRequest struct {
	CertificateType string `json:"certificateType" validate:"required"`
}

type GetInstalledCertificateIdsResponse struct {
	CertificateHashData []CertificateHashDataType `json:"certificateHashData,omitempty" validate:"omitempty"`
	Status              string                    `json:"status" validate:"required"`
}
