// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetConfigurationRequest struct {
	Key []string `json:"key,omitempty" validate:"omitempty"`
}

type GetConfigurationResponse struct {
	ConfigurationKey []ConfigurationKey `json:"configurationKey,omitempty" validate:"omitempty"`
	UnknownKey       []string           `json:"unknownKey,omitempty" validate:"omitempty"`
}

type ConfigurationKey struct {
	Key      string  `json:"key" validate:"required,max=50"`
	Readonly bool    `json:"readonly" validate:"required"`
	Value    *string `json:"value,omitempty" validate:"omitempty,max=500"`
}
