// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetDiagnosticsRequest struct {
	Location      string     `json:"location" validate:"required"`
	Retries       *int32     `json:"retries,omitempty" validate:"omitempty"`
	RetryInterval *int32     `json:"retryInterval,omitempty" validate:"omitempty"`
	StartTime     *time.Time `json:"startTime,omitempty" validate:"omitempty"`
	StopTime      *time.Time `json:"stopTime,omitempty" validate:"omitempty"`
}

type GetDiagnosticsResponse struct {
	FileName *string `json:"fileName,omitempty" validate:"omitempty,max=255"`
}
