// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetLocalListVersionRequest struct {
}

type GetLocalListVersionResponse struct {
	ListVersion int32 `json:"listVersion" validate:"required"`
}
