// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetCompositeScheduleRequest struct {
	ChargingRateUnit *GetCompositeScheduleRequestChargingRateUnit `json:"chargingRateUnit,omitempty" validate:"omitempty"`
	ConnectorID      int32                                        `json:"connectorId" validate:"required"`
	Duration         int32                                        `json:"duration" validate:"required"`
}

type GetCompositeScheduleResponse struct {
	ChargingSchedule *ChargingSchedule                  `json:"chargingSchedule,omitempty" validate:"omitempty"`
	ConnectorID      *int32                             `json:"connectorId,omitempty" validate:"omitempty"`
	ScheduleStart    *time.Time                         `json:"scheduleStart,omitempty" validate:"omitempty"`
	Status           GetCompositeScheduleResponseStatus `json:"status" validate:"required"`
}
