// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type HeartbeatRequest struct {
}

type HeartbeatResponse struct {
	CurrentTime time.Time `json:"currentTime" validate:"required"`
}
