// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type InstallCertificateRequest struct {
	Certificate     string `json:"certificate" validate:"required,max=5500"`
	CertificateType string `json:"certificateType" validate:"required"`
}

type InstallCertificateResponse struct {
	Status string `json:"status" validate:"required"`
}
