// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type LogStatusNotificationRequest struct {
	RequestID *int32 `json:"requestId,omitempty" validate:"omitempty"`
	Status    string `json:"status" validate:"required"`
}

type LogStatusNotificationResponse struct {
}
