// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type MeterValuesRequest struct {
	ConnectorID   int32        `json:"connectorId" validate:"required"`
	MeterValue    []MeterValue `json:"meterValue" validate:"required"`
	TransactionID *int32       `json:"transactionId,omitempty" validate:"omitempty"`
}

type MeterValue struct {
	SampledValue []SampledValue `json:"sampledValue" validate:"required"`
	Timestamp    time.Time      `json:"timestamp" validate:"required"`
}

type SampledValue struct {
	Context   *SampledValueContext   `json:"context,omitempty" validate:"omitempty"`
	Format    *SampledValueFormat    `json:"format,omitempty" validate:"omitempty"`
	Location  *SampledValueLocation  `json:"location,omitempty" validate:"omitempty"`
	Measurand *SampledValueMeasurand `json:"measurand,omitempty" validate:"omitempty"`
	Phase     *SampledValuePhase     `json:"phase,omitempty" validate:"omitempty"`
	Unit      *SampledValueUnit      `json:"unit,omitempty" validate:"omitempty"`
	Value     string                 `json:"value" validate:"required"`
}

type MeterValuesResponse struct {
}
