// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type RemoteStopTransactionRequest struct {
	TransactionID int32 `json:"transactionId" validate:"required"`
}

type RemoteStopTransactionResponse struct {
	Status RemoteStopTransactionResponseStatus `json:"status" validate:"required"`
}
