// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ResetRequest struct {
	Type ResetRequestType `json:"type" validate:"required"`
}

type ResetResponse struct {
	Status ResetResponseStatus `json:"status" validate:"required"`
}
