// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type SecurityEventNotificationRequest struct {
	TechInfo  *string   `json:"techInfo,omitempty" validate:"omitempty,max=255"`
	Timestamp time.Time `json:"timestamp" validate:"required"`
	Type      string    `json:"type" validate:"required,max=50"`
}

type SecurityEventNotificationResponse struct {
}
