// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SendLocalListRequest struct {
	ListVersion            int32                          `json:"listVersion" validate:"required"`
	LocalAuthorizationList []LocalAuthorizationList       `json:"localAuthorizationList,omitempty" validate:"omitempty"`
	UpdateType             SendLocalListRequestUpdateType `json:"updateType" validate:"required"`
}

type LocalAuthorizationList struct {
	IDTag     string     `json:"idTag" validate:"required,max=20"`
	IDTagInfo *IDTagInfo `json:"idTagInfo,omitempty" validate:"omitempty"`
}

type SendLocalListResponse struct {
	Status SendLocalListResponseStatus `json:"status" validate:"required"`
}
