// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SignCertificateRequest struct {
	Csr string `json:"csr" validate:"required,max=5500"`
}

type SignCertificateResponse struct {
	Status string `json:"status" validate:"required"`
}
