// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type StopTransactionRequest struct {
	IDTag           *string                       `json:"idTag,omitempty" validate:"omitempty,max=20"`
	MeterStop       int32                         `json:"meterStop" validate:"required"`
	Reason          *StopTransactionRequestReason `json:"reason,omitempty" validate:"omitempty"`
	Timestamp       time.Time                     `json:"timestamp" validate:"required"`
	TransactionData []TransactionData             `json:"transactionData,omitempty" validate:"omitempty"`
	TransactionID   int32                         `json:"transactionId" validate:"required"`
}

type TransactionData struct {
	SampledValue []SampledValue `json:"sampledValue" validate:"required"`
	Timestamp    time.Time      `json:"timestamp" validate:"required"`
}

type StopTransactionResponse struct {
	IDTagInfo *IDTagInfo `json:"idTagInfo,omitempty" validate:"omitempty"`
}
