// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type TriggerMessageRequest struct {
	ConnectorID      *int32                                `json:"connectorId,omitempty" validate:"omitempty"`
	RequestedMessage TriggerMessageRequestRequestedMessage `json:"requestedMessage" validate:"required"`
}

type TriggerMessageResponse struct {
	Status TriggerMessageResponseStatus `json:"status" validate:"required"`
}
