// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type UnlockConnectorRequest struct {
	ConnectorID int32 `json:"connectorId" validate:"required"`
}

type UnlockConnectorResponse struct {
	Status UnlockConnectorResponseStatus `json:"status" validate:"required"`
}
