// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type UpdateFirmwareRequest struct {
	Location      string    `json:"location" validate:"required"`
	Retries       *int32    `json:"retries,omitempty" validate:"omitempty"`
	RetrieveDate  time.Time `json:"retrieveDate" validate:"required"`
	RetryInterval *int32    `json:"retryInterval,omitempty" validate:"omitempty"`
}

type UpdateFirmwareResponse struct {
}
