// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type AdjustPeriodicEventStreamRequest struct {
	CustomData *CustomDataType               `json:"customData,omitempty" validate:"omitempty"`
	ID         int32                         `json:"id" validate:"required"`
	Params     PeriodicEventStreamParamsType `json:"params" validate:"required"`
}

type AdjustPeriodicEventStreamResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
