// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type AuthorizeRequest struct {
	Certificate                 *string               `json:"certificate,omitempty" validate:"omitempty,max=10000"`
	CustomData                  *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	IDToken                     IdTokenType           `json:"idToken" validate:"required"`
	Iso15118CertificateHashData []OCSPRequestDataType `json:"iso15118CertificateHashData,omitempty" validate:"omitempty"`
}

type CustomDataType struct {
	VendorID string `json:"vendorId" validate:"required,max=255"`
}

type IdTokenType struct {
	AdditionalInfo []AdditionalInfoType `json:"additionalInfo,omitempty" validate:"omitempty"`
	CustomData     *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	IDToken        string               `json:"idToken" validate:"required,max=255"`
	Type           string               `json:"type" validate:"required,max=20"`
}

type AdditionalInfoType struct {
	AdditionalIDToken string          `json:"additionalIdToken" validate:"required,max=255"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Type              string          `json:"type" validate:"required,max=50"`
}

type OCSPRequestDataType struct {
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	HashAlgorithm  string          `json:"hashAlgorithm" validate:"required"`
	IssuerKeyHash  string          `json:"issuerKeyHash" validate:"required,max=128"`
	IssuerNameHash string          `json:"issuerNameHash" validate:"required,max=128"`
	ResponderURL   string          `json:"responderURL" validate:"required,max=2000"`
	SerialNumber   string          `json:"serialNumber" validate:"required,max=40"`
}

type AuthorizeResponse struct {
	AllowedEnergyTransfer []string        `json:"allowedEnergyTransfer,omitempty" validate:"omitempty"`
	CertificateStatus     *string         `json:"certificateStatus,omitempty" validate:"omitempty"`
	CustomData            *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IDTokenInfo           IdTokenInfoType `json:"idTokenInfo" validate:"required"`
	Tariff                *TariffType     `json:"tariff,omitempty" validate:"omitempty"`
}

type IdTokenInfoType struct {
	CacheExpiryDateTime *time.Time          `json:"cacheExpiryDateTime,omitempty" validate:"omitempty"`
	ChargingPriority    *int32              `json:"chargingPriority,omitempty" validate:"omitempty"`
	CustomData          *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	EVSEID              []int32             `json:"evseId,omitempty" validate:"omitempty"`
	GroupIDToken        *IdTokenType        `json:"groupIdToken,omitempty" validate:"omitempty"`
	Language1           *string             `json:"language1,omitempty" validate:"omitempty,max=8"`
	Language2           *string             `json:"language2,omitempty" validate:"omitempty,max=8"`
	PersonalMessage     *MessageContentType `json:"personalMessage,omitempty" validate:"omitempty"`
	Status              string              `json:"status" validate:"required"`
}

type MessageContentType struct {
	Content    string          `json:"content" validate:"required,max=1024"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Format     string          `json:"format" validate:"required"`
	Language   *string         `json:"language,omitempty" validate:"omitempty,max=8"`
}

type TariffType struct {
	ChargingTime     *TariffTimeType      `json:"chargingTime,omitempty" validate:"omitempty"`
	Currency         string               `json:"currency" validate:"required,max=3"`
	CustomData       *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	Description      []MessageContentType `json:"description,omitempty" validate:"omitempty"`
	Energy           *TariffEnergyType    `json:"energy,omitempty" validate:"omitempty"`
	FixedFee         *TariffFixedType     `json:"fixedFee,omitempty" validate:"omitempty"`
	IdleTime         *TariffTimeType      `json:"idleTime,omitempty" validate:"omitempty"`
	MaxCost          *PriceType           `json:"maxCost,omitempty" validate:"omitempty"`
	MinCost          *PriceType           `json:"minCost,omitempty" validate:"omitempty"`
	ReservationFixed *TariffFixedType     `json:"reservationFixed,omitempty" validate:"omitempty"`
	ReservationTime  *TariffTimeType      `json:"reservationTime,omitempty" validate:"omitempty"`
	TariffID         string               `json:"tariffId" validate:"required,max=60"`
	ValidFrom        *time.Time           `json:"validFrom,omitempty" validate:"omitempty"`
}

type TariffTimeType struct {
	CustomData *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	Prices     []TariffTimePriceType `json:"prices" validate:"required"`
	TaxRates   []TaxRateType         `json:"taxRates,omitempty" validate:"omitempty"`
}

type TariffTimePriceType struct {
	Conditions  *TariffConditionsType `json:"conditions,omitempty" validate:"omitempty"`
	CustomData  *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	PriceMinute decimal.Decimal       `json:"priceMinute" validate:"required"`
}

type TariffConditionsType struct {
	CustomData      *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	DayOfWeek       []string         `json:"dayOfWeek,omitempty" validate:"omitempty"`
	EndTimeOfDay    *string          `json:"endTimeOfDay,omitempty" validate:"omitempty"`
	EVSEKind        *string          `json:"evseKind,omitempty" validate:"omitempty"`
	MaxChargingTime *int32           `json:"maxChargingTime,omitempty" validate:"omitempty"`
	MaxCurrent      *decimal.Decimal `json:"maxCurrent,omitempty" validate:"omitempty"`
	MaxEnergy       *decimal.Decimal `json:"maxEnergy,omitempty" validate:"omitempty"`
	MaxIdleTime     *int32           `json:"maxIdleTime,omitempty" validate:"omitempty"`
	MaxPower        *decimal.Decimal `json:"maxPower,omitempty" validate:"omitempty"`
	MaxTime         *int32           `json:"maxTime,omitempty" validate:"omitempty"`
	MinChargingTime *int32           `json:"minChargingTime,omitempty" validate:"omitempty"`
	MinCurrent      *decimal.Decimal `json:"minCurrent,omitempty" validate:"omitempty"`
	MinEnergy       *decimal.Decimal `json:"minEnergy,omitempty" validate:"omitempty"`
	MinIdleTime     *int32           `json:"minIdleTime,omitempty" validate:"omitempty"`
	MinPower        *decimal.Decimal `json:"minPower,omitempty" validate:"omitempty"`
	MinTime         *int32           `json:"minTime,omitempty" validate:"omitempty"`
	StartTimeOfDay  *string          `json:"startTimeOfDay,omitempty" validate:"omitempty"`
	ValidFromDate   *string          `json:"validFromDate,omitempty" validate:"omitempty"`
	ValidToDate     *string          `json:"validToDate,omitempty" validate:"omitempty"`
}

type TaxRateType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Stack      *int32          `json:"stack,omitempty" validate:"omitempty"`
	Tax        decimal.Decimal `json:"tax" validate:"required"`
	Type       string          `json:"type" validate:"required,max=20"`
}

type TariffEnergyType struct {
	CustomData *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	Prices     []TariffEnergyPriceType `json:"prices" validate:"required"`
	TaxRates   []TaxRateType           `json:"taxRates,omitempty" validate:"omitempty"`
}

type TariffEnergyPriceType struct {
	Conditions *TariffConditionsType `json:"conditions,omitempty" validate:"omitempty"`
	CustomData *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	PriceKwh   decimal.Decimal       `json:"priceKwh" validate:"required"`
}

type TariffFixedType struct {
	CustomData *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	Prices     []TariffFixedPriceType `json:"prices" validate:"required"`
	TaxRates   []TaxRateType          `json:"taxRates,omitempty" validate:"omitempty"`
}

type TariffFixedPriceType struct {
	Conditions *TariffConditionsFixedType `json:"conditions,omitempty" validate:"omitempty"`
	CustomData *CustomDataType            `json:"customData,omitempty" validate:"omitempty"`
	PriceFixed decimal.Decimal            `json:"priceFixed" validate:"required"`
}

type TariffConditionsFixedType struct {
	CustomData         *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	DayOfWeek          []string        `json:"dayOfWeek,omitempty" validate:"omitempty"`
	EndTimeOfDay       *string         `json:"endTimeOfDay,omitempty" validate:"omitempty"`
	EVSEKind           *string         `json:"evseKind,omitempty" validate:"omitempty"`
	PaymentBrand       *string         `json:"paymentBrand,omitempty" validate:"omitempty,max=20"`
	PaymentRecognition *string         `json:"paymentRecognition,omitempty" validate:"omitempty,max=20"`
	StartTimeOfDay     *string         `json:"startTimeOfDay,omitempty" validate:"omitempty"`
	ValidFromDate      *string         `json:"validFromDate,omitempty" validate:"omitempty"`
	ValidToDate        *string         `json:"validToDate,omitempty" validate:"omitempty"`
}

type PriceType struct {
	CustomData *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	ExclTax    *decimal.Decimal `json:"exclTax,omitempty" validate:"omitempty"`
	InclTax    *decimal.Decimal `json:"inclTax,omitempty" validate:"omitempty"`
	TaxRates   []TaxRateType    `json:"taxRates,omitempty" validate:"omitempty"`
}
