// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type BatterySwapRequest struct {
	BatteryData []BatteryDataType `json:"batteryData" validate:"required"`
	CustomData  *CustomDataType   `json:"customData,omitempty" validate:"omitempty"`
	EventType   string            `json:"eventType" validate:"required"`
	IDToken     IdTokenType       `json:"idToken" validate:"required"`
	RequestID   int32             `json:"requestId" validate:"required"`
}

type BatteryDataType struct {
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID         int32           `json:"evseId" validate:"required"`
	ProductionDate *time.Time      `json:"productionDate,omitempty" validate:"omitempty"`
	SerialNumber   string          `json:"serialNumber" validate:"required,max=50"`
	SoC            decimal.Decimal `json:"soC" validate:"required"`
	SoH            decimal.Decimal `json:"soH" validate:"required"`
	VendorInfo     *string         `json:"vendorInfo,omitempty" validate:"omitempty,max=500"`
}

type BatterySwapResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
