// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type BootNotificationRequest struct {
	ChargingStation ChargingStationType `json:"chargingStation" validate:"required"`
	CustomData      *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	Reason          string              `json:"reason" validate:"required"`
}

type ChargingStationType struct {
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	FirmwareVersion *string         `json:"firmwareVersion,omitempty" validate:"omitempty,max=50"`
	Model           string          `json:"model" validate:"required,max=20"`
	Modem           *ModemType      `json:"modem,omitempty" validate:"omitempty"`
	SerialNumber    *string         `json:"serialNumber,omitempty" validate:"omitempty,max=25"`
	VendorName      string          `json:"vendorName" validate:"required,max=50"`
}

type ModemType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ICCID      *string         `json:"iccid,omitempty" validate:"omitempty,max=20"`
	IMSI       *string         `json:"imsi,omitempty" validate:"omitempty,max=20"`
}

type BootNotificationResponse struct {
	CurrentTime time.Time       `json:"currentTime" validate:"required"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Interval    int32           `json:"interval" validate:"required"`
	Status      string          `json:"status" validate:"required"`
	StatusInfo  *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
