// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type CancelReservationRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ReservationID int32           `json:"reservationId" validate:"required"`
}

type CancelReservationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
