// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type CertificateSignedRequest struct {
	CertificateChain string          `json:"certificateChain" validate:"required,max=10000"`
	CertificateType  *string         `json:"certificateType,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	RequestID        *int32          `json:"requestId,omitempty" validate:"omitempty"`
}

type CertificateSignedResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
