// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ChangeTransactionTariffRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Tariff        TariffType      `json:"tariff" validate:"required"`
	TransactionID string          `json:"transactionId" validate:"required,max=36"`
}

type ChangeTransactionTariffResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
