// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearTariffsRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID     *int32          `json:"evseId,omitempty" validate:"omitempty"`
	TariffIds  []string        `json:"tariffIds,omitempty" validate:"omitempty"`
}

type ClearTariffsResponse struct {
	ClearTariffsResult []ClearTariffsResultType `json:"clearTariffsResult" validate:"required"`
	CustomData         *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
}

type ClearTariffsResultType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
	TariffID   *string         `json:"tariffId,omitempty" validate:"omitempty,max=60"`
}
