// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearDisplayMessageRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         int32           `json:"id" validate:"required"`
}

type ClearDisplayMessageResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
