// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearDERControlRequest struct {
	ControlID   *string         `json:"controlId,omitempty" validate:"omitempty,max=36"`
	ControlType *string         `json:"controlType,omitempty" validate:"omitempty"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IsDefault   bool            `json:"isDefault"`
}

type ClearDERControlResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
