// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearedChargingLimitRequest struct {
	ChargingLimitSource string          `json:"chargingLimitSource" validate:"required,max=20"`
	CustomData          *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID              *int32          `json:"evseId,omitempty" validate:"omitempty"`
}

type ClearedChargingLimitResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
