// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClearVariableMonitoringRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         []int32         `json:"id" validate:"required"`
}

type ClearVariableMonitoringResponse struct {
	ClearMonitoringResult []ClearMonitoringResultType `json:"clearMonitoringResult" validate:"required"`
	CustomData            *CustomDataType             `json:"customData,omitempty" validate:"omitempty"`
}

type ClearMonitoringResultType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         int32           `json:"id" validate:"required"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
