// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ClosePeriodicEventStreamRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID         int32           `json:"id" validate:"required"`
}

type ClosePeriodicEventStreamResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
