// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
)

type CostUpdatedRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	TotalCost     decimal.Decimal `json:"totalCost" validate:"required"`
	TransactionID string          `json:"transactionId" validate:"required,max=36"`
}

type CostUpdatedResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
