// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type CustomerInformationRequest struct {
	Clear               bool                     `json:"clear" validate:"required"`
	CustomData          *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
	CustomerCertificate *CertificateHashDataType `json:"customerCertificate,omitempty" validate:"omitempty"`
	CustomerIdentifier  *string                  `json:"customerIdentifier,omitempty" validate:"omitempty,max=64"`
	IDToken             *IdTokenType             `json:"idToken,omitempty" validate:"omitempty"`
	Report              bool                     `json:"report" validate:"required"`
	RequestID           int32                    `json:"requestId" validate:"required"`
}

type CertificateHashDataType struct {
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	HashAlgorithm  string          `json:"hashAlgorithm" validate:"required"`
	IssuerKeyHash  string          `json:"issuerKeyHash" validate:"required,max=128"`
	IssuerNameHash string          `json:"issuerNameHash" validate:"required,max=128"`
	SerialNumber   string          `json:"serialNumber" validate:"required,max=40"`
}

type CustomerInformationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
