// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetMonitoringReportRequest struct {
	ComponentVariable  []ComponentVariableType `json:"componentVariable,omitempty" validate:"omitempty"`
	CustomData         *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	MonitoringCriteria []string                `json:"monitoringCriteria,omitempty" validate:"omitempty"`
	RequestID          int32                   `json:"requestId" validate:"required"`
}

type ComponentVariableType struct {
	Component  ComponentType   `json:"component" validate:"required"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Variable   *VariableType   `json:"variable,omitempty" validate:"omitempty"`
}

type GetMonitoringReportResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
