// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetCertificateChainStatusRequest struct {
	CertificateStatusRequests []CertificateStatusRequestInfoType `json:"certificateStatusRequests" validate:"required"`
	CustomData                *CustomDataType                    `json:"customData,omitempty" validate:"omitempty"`
}

type CertificateStatusRequestInfoType struct {
	CertificateHashData CertificateHashDataType `json:"certificateHashData" validate:"required"`
	CustomData          *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	Source              string                  `json:"source" validate:"required"`
	Urls                []string                `json:"urls" validate:"required"`
}

type GetCertificateChainStatusResponse struct {
	CertificateStatus []CertificateStatusType `json:"certificateStatus" validate:"required"`
	CustomData        *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
}

type CertificateStatusType struct {
	CertificateHashData CertificateHashDataType `json:"certificateHashData" validate:"required"`
	CustomData          *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	NextUpdate          time.Time               `json:"nextUpdate" validate:"required"`
	Source              string                  `json:"source" validate:"required"`
	Status              string                  `json:"status" validate:"required"`
}
