// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetTariffsRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID     int32           `json:"evseId" validate:"required"`
}

type GetTariffsResponse struct {
	CustomData        *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	Status            string                 `json:"status" validate:"required"`
	StatusInfo        *StatusInfoType        `json:"statusInfo,omitempty" validate:"omitempty"`
	TariffAssignments []TariffAssignmentType `json:"tariffAssignments,omitempty" validate:"omitempty"`
}

type TariffAssignmentType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEIds    []int32         `json:"evseIds,omitempty" validate:"omitempty"`
	IDTokens   []string        `json:"idTokens,omitempty" validate:"omitempty"`
	TariffID   string          `json:"tariffId" validate:"required,max=60"`
	TariffKind string          `json:"tariffKind" validate:"required"`
	ValidFrom  *time.Time      `json:"validFrom,omitempty" validate:"omitempty"`
}
