// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetLogRequest struct {
	CustomData    *CustomDataType   `json:"customData,omitempty" validate:"omitempty"`
	Log           LogParametersType `json:"log" validate:"required"`
	LogType       string            `json:"logType" validate:"required"`
	RequestID     int32             `json:"requestId" validate:"required"`
	Retries       *int32            `json:"retries,omitempty" validate:"omitempty"`
	RetryInterval *int32            `json:"retryInterval,omitempty" validate:"omitempty"`
}

type LogParametersType struct {
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	LatestTimestamp *time.Time      `json:"latestTimestamp,omitempty" validate:"omitempty"`
	OldestTimestamp *time.Time      `json:"oldestTimestamp,omitempty" validate:"omitempty"`
	RemoteLocation  string          `json:"remoteLocation" validate:"required,max=2000"`
}

type GetLogResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Filename   *string         `json:"filename,omitempty" validate:"omitempty,max=255"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
