// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetTransactionStatusRequest struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	TransactionID *string         `json:"transactionId,omitempty" validate:"omitempty,max=36"`
}

type GetTransactionStatusResponse struct {
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	MessagesInQueue  bool            `json:"messagesInQueue" validate:"required"`
	OngoingIndicator *bool           `json:"ongoingIndicator,omitempty" validate:"omitempty"`
}
