// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type GetCompositeScheduleRequest struct {
	ChargingRateUnit *string         `json:"chargingRateUnit,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Duration         int32           `json:"duration" validate:"required"`
	EVSEID           int32           `json:"evseId" validate:"required"`
}

type GetCompositeScheduleResponse struct {
	CustomData *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	Schedule   *CompositeScheduleType `json:"schedule,omitempty" validate:"omitempty"`
	Status     string                 `json:"status" validate:"required"`
	StatusInfo *StatusInfoType        `json:"statusInfo,omitempty" validate:"omitempty"`
}

type CompositeScheduleType struct {
	ChargingRateUnit       string                       `json:"chargingRateUnit" validate:"required"`
	ChargingSchedulePeriod []ChargingSchedulePeriodType `json:"chargingSchedulePeriod" validate:"required"`
	CustomData             *CustomDataType              `json:"customData,omitempty" validate:"omitempty"`
	Duration               int32                        `json:"duration" validate:"required"`
	EVSEID                 int32                        `json:"evseId" validate:"required"`
	ScheduleStart          time.Time                    `json:"scheduleStart" validate:"required"`
}
