// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetBaseReportRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ReportBase string          `json:"reportBase" validate:"required"`
	RequestID  int32           `json:"requestId" validate:"required"`
}

type GetBaseReportResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
