// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetVariablesRequest struct {
	CustomData      *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	GetVariableData []GetVariableDataType `json:"getVariableData" validate:"required"`
}

type GetVariableDataType struct {
	AttributeType *string         `json:"attributeType,omitempty" validate:"omitempty"`
	Component     ComponentType   `json:"component" validate:"required"`
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Variable      VariableType    `json:"variable" validate:"required"`
}

type GetVariablesResponse struct {
	CustomData        *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	GetVariableResult []GetVariableResultType `json:"getVariableResult" validate:"required"`
}

type GetVariableResultType struct {
	AttributeStatus     string          `json:"attributeStatus" validate:"required"`
	AttributeStatusInfo *StatusInfoType `json:"attributeStatusInfo,omitempty" validate:"omitempty"`
	AttributeType       *string         `json:"attributeType,omitempty" validate:"omitempty"`
	AttributeValue      *string         `json:"attributeValue,omitempty" validate:"omitempty,max=2500"`
	Component           ComponentType   `json:"component" validate:"required"`
	CustomData          *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Variable            VariableType    `json:"variable" validate:"required"`
}
