// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetPeriodicEventStreamRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type GetPeriodicEventStreamResponse struct {
	ConstantStreamData []ConstantStreamDataType `json:"constantStreamData,omitempty" validate:"omitempty"`
	CustomData         *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
}

type ConstantStreamDataType struct {
	CustomData           *CustomDataType               `json:"customData,omitempty" validate:"omitempty"`
	ID                   int32                         `json:"id" validate:"required"`
	Params               PeriodicEventStreamParamsType `json:"params" validate:"required"`
	VariableMonitoringID int32                         `json:"variableMonitoringId" validate:"required"`
}
