// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetInstalledCertificateIdsRequest struct {
	CertificateType []string        `json:"certificateType,omitempty" validate:"omitempty"`
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type GetInstalledCertificateIdsResponse struct {
	CertificateHashDataChain []CertificateHashDataChainType `json:"certificateHashDataChain,omitempty" validate:"omitempty"`
	CustomData               *CustomDataType                `json:"customData,omitempty" validate:"omitempty"`
	Status                   string                         `json:"status" validate:"required"`
	StatusInfo               *StatusInfoType                `json:"statusInfo,omitempty" validate:"omitempty"`
}

type CertificateHashDataChainType struct {
	CertificateHashData      CertificateHashDataType   `json:"certificateHashData" validate:"required"`
	CertificateType          string                    `json:"certificateType" validate:"required"`
	ChildCertificateHashData []CertificateHashDataType `json:"childCertificateHashData,omitempty" validate:"omitempty"`
	CustomData               *CustomDataType           `json:"customData,omitempty" validate:"omitempty"`
}
