// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetDERControlRequest struct {
	ControlID   *string         `json:"controlId,omitempty" validate:"omitempty,max=36"`
	ControlType *string         `json:"controlType,omitempty" validate:"omitempty"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IsDefault   *bool           `json:"isDefault,omitempty" validate:"omitempty"`
	RequestID   int32           `json:"requestId" validate:"required"`
}

type GetDERControlResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
