// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetLocalListVersionRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type GetLocalListVersionResponse struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	VersionNumber int32           `json:"versionNumber" validate:"required"`
}
