// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type GetReportRequest struct {
	ComponentCriteria []string                `json:"componentCriteria,omitempty" validate:"omitempty"`
	ComponentVariable []ComponentVariableType `json:"componentVariable,omitempty" validate:"omitempty"`
	CustomData        *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	RequestID         int32                   `json:"requestId" validate:"required"`
}

type GetReportResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
