// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type LogStatusNotificationRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	RequestID  *int32          `json:"requestId,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}

type LogStatusNotificationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
