// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type NotifyDERStartStopRequest struct {
	ControlID     string          `json:"controlId" validate:"required,max=36"`
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Started       bool            `json:"started" validate:"required"`
	SupersededIds []string        `json:"supersededIds,omitempty" validate:"omitempty"`
	Timestamp     time.Time       `json:"timestamp" validate:"required"`
}

type NotifyDERStartStopResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
