// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type NotifyPeriodicEventStream struct {
	Basetime   time.Time               `json:"basetime" validate:"required"`
	CustomData *CustomDataType         `json:"customData,omitempty" validate:"omitempty"`
	Data       []StreamDataElementType `json:"data" validate:"required"`
	ID         int32                   `json:"id" validate:"required"`
	Pending    int32                   `json:"pending" validate:"required"`
}

type StreamDataElementType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	T          decimal.Decimal `json:"t" validate:"required"`
	V          string          `json:"v" validate:"required,max=2500"`
}
