// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type NotifyMonitoringReportRequest struct {
	CustomData  *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	GeneratedAt time.Time            `json:"generatedAt" validate:"required"`
	Monitor     []MonitoringDataType `json:"monitor,omitempty" validate:"omitempty"`
	RequestID   int32                `json:"requestId" validate:"required"`
	SeqNo       int32                `json:"seqNo" validate:"required"`
	Tbc         *bool                `json:"tbc,omitempty" validate:"omitempty"`
}

type MonitoringDataType struct {
	Component          ComponentType            `json:"component" validate:"required"`
	CustomData         *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
	Variable           VariableType             `json:"variable" validate:"required"`
	VariableMonitoring []VariableMonitoringType `json:"variableMonitoring" validate:"required"`
}

type VariableMonitoringType struct {
	CustomData            *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EventNotificationType string          `json:"eventNotificationType" validate:"required"`
	ID                    int32           `json:"id" validate:"required"`
	Severity              int32           `json:"severity" validate:"required"`
	Transaction           bool            `json:"transaction" validate:"required"`
	Type                  string          `json:"type" validate:"required"`
	Value                 decimal.Decimal `json:"value" validate:"required"`
}

type NotifyMonitoringReportResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
