// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type NotifyEVChargingNeedsRequest struct {
	ChargingNeeds     ChargingNeedsType `json:"chargingNeeds" validate:"required"`
	CustomData        *CustomDataType   `json:"customData,omitempty" validate:"omitempty"`
	EVSEID            int32             `json:"evseId" validate:"required"`
	MaxScheduleTuples *int32            `json:"maxScheduleTuples,omitempty" validate:"omitempty"`
	Timestamp         *time.Time        `json:"timestamp,omitempty" validate:"omitempty"`
}

type ChargingNeedsType struct {
	ACChargingParameters    *ACChargingParametersType  `json:"acChargingParameters,omitempty" validate:"omitempty"`
	AvailableEnergyTransfer []string                   `json:"availableEnergyTransfer,omitempty" validate:"omitempty"`
	ControlMode             *string                    `json:"controlMode,omitempty" validate:"omitempty"`
	CustomData              *CustomDataType            `json:"customData,omitempty" validate:"omitempty"`
	DCChargingParameters    *DCChargingParametersType  `json:"dcChargingParameters,omitempty" validate:"omitempty"`
	DepartureTime           *time.Time                 `json:"departureTime,omitempty" validate:"omitempty"`
	DerChargingParameters   *DERChargingParametersType `json:"derChargingParameters,omitempty" validate:"omitempty"`
	EVEnergyOffer           *EVEnergyOfferType         `json:"evEnergyOffer,omitempty" validate:"omitempty"`
	MobilityNeedsMode       *string                    `json:"mobilityNeedsMode,omitempty" validate:"omitempty"`
	RequestedEnergyTransfer string                     `json:"requestedEnergyTransfer" validate:"required"`
	V2xChargingParameters   *V2XChargingParametersType `json:"v2xChargingParameters,omitempty" validate:"omitempty"`
}

type ACChargingParametersType struct {
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EnergyAmount decimal.Decimal `json:"energyAmount" validate:"required"`
	EVMaxCurrent decimal.Decimal `json:"evMaxCurrent" validate:"required"`
	EVMaxVoltage decimal.Decimal `json:"evMaxVoltage" validate:"required"`
	EVMinCurrent decimal.Decimal `json:"evMinCurrent" validate:"required"`
}

type DCChargingParametersType struct {
	BulkSoC          *int32           `json:"bulkSoC,omitempty" validate:"omitempty"`
	CustomData       *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EnergyAmount     *decimal.Decimal `json:"energyAmount,omitempty" validate:"omitempty"`
	EVEnergyCapacity *decimal.Decimal `json:"evEnergyCapacity,omitempty" validate:"omitempty"`
	EVMaxCurrent     decimal.Decimal  `json:"evMaxCurrent" validate:"required"`
	EVMaxPower       *decimal.Decimal `json:"evMaxPower,omitempty" validate:"omitempty"`
	EVMaxVoltage     decimal.Decimal  `json:"evMaxVoltage" validate:"required"`
	FullSoC          *int32           `json:"fullSoC,omitempty" validate:"omitempty"`
	StateOfCharge    *int32           `json:"stateOfCharge,omitempty" validate:"omitempty"`
}

type DERChargingParametersType struct {
	CustomData                             *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EVDurationLevel1DCInjection            *decimal.Decimal `json:"evDurationLevel1DCInjection,omitempty" validate:"omitempty"`
	EVDurationLevel2DCInjection            *decimal.Decimal `json:"evDurationLevel2DCInjection,omitempty" validate:"omitempty"`
	EVInverterHwVersion                    *string          `json:"evInverterHwVersion,omitempty" validate:"omitempty,max=50"`
	EVInverterManufacturer                 *string          `json:"evInverterManufacturer,omitempty" validate:"omitempty,max=50"`
	EVInverterModel                        *string          `json:"evInverterModel,omitempty" validate:"omitempty,max=50"`
	EVInverterSerialNumber                 *string          `json:"evInverterSerialNumber,omitempty" validate:"omitempty,max=50"`
	EVInverterSwVersion                    *string          `json:"evInverterSwVersion,omitempty" validate:"omitempty,max=50"`
	EVIslandingDetectionMethod             []string         `json:"evIslandingDetectionMethod,omitempty" validate:"omitempty"`
	EVIslandingTripTime                    *decimal.Decimal `json:"evIslandingTripTime,omitempty" validate:"omitempty"`
	EVMaximumLevel1DCInjection             *decimal.Decimal `json:"evMaximumLevel1DCInjection,omitempty" validate:"omitempty"`
	EVMaximumLevel2DCInjection             *decimal.Decimal `json:"evMaximumLevel2DCInjection,omitempty" validate:"omitempty"`
	EVOverExcitedMaxDischargePower         *decimal.Decimal `json:"evOverExcitedMaxDischargePower,omitempty" validate:"omitempty"`
	EVOverExcitedPowerFactor               *decimal.Decimal `json:"evOverExcitedPowerFactor,omitempty" validate:"omitempty"`
	EVReactiveSusceptance                  *decimal.Decimal `json:"evReactiveSusceptance,omitempty" validate:"omitempty"`
	EVSessionTotalDischargeEnergyAvailable *decimal.Decimal `json:"evSessionTotalDischargeEnergyAvailable,omitempty" validate:"omitempty"`
	EVSupportedDERControl                  []string         `json:"evSupportedDERControl,omitempty" validate:"omitempty"`
	EVUnderExcitedMaxDischargePower        *decimal.Decimal `json:"evUnderExcitedMaxDischargePower,omitempty" validate:"omitempty"`
	EVUnderExcitedPowerFactor              *decimal.Decimal `json:"evUnderExcitedPowerFactor,omitempty" validate:"omitempty"`
	MaxApparentPower                       *decimal.Decimal `json:"maxApparentPower,omitempty" validate:"omitempty"`
	MaxChargeApparentPower                 *decimal.Decimal `json:"maxChargeApparentPower,omitempty" validate:"omitempty"`
	MaxChargeApparentPower_L2              *decimal.Decimal `json:"maxChargeApparentPower_L2,omitempty" validate:"omitempty"`
	MaxChargeApparentPower_L3              *decimal.Decimal `json:"maxChargeApparentPower_L3,omitempty" validate:"omitempty"`
	MaxChargeReactivePower                 *decimal.Decimal `json:"maxChargeReactivePower,omitempty" validate:"omitempty"`
	MaxChargeReactivePower_L2              *decimal.Decimal `json:"maxChargeReactivePower_L2,omitempty" validate:"omitempty"`
	MaxChargeReactivePower_L3              *decimal.Decimal `json:"maxChargeReactivePower_L3,omitempty" validate:"omitempty"`
	MaxDischargeApparentPower              *decimal.Decimal `json:"maxDischargeApparentPower,omitempty" validate:"omitempty"`
	MaxDischargeApparentPower_L2           *decimal.Decimal `json:"maxDischargeApparentPower_L2,omitempty" validate:"omitempty"`
	MaxDischargeApparentPower_L3           *decimal.Decimal `json:"maxDischargeApparentPower_L3,omitempty" validate:"omitempty"`
	MaxDischargeReactivePower              *decimal.Decimal `json:"maxDischargeReactivePower,omitempty" validate:"omitempty"`
	MaxDischargeReactivePower_L2           *decimal.Decimal `json:"maxDischargeReactivePower_L2,omitempty" validate:"omitempty"`
	MaxDischargeReactivePower_L3           *decimal.Decimal `json:"maxDischargeReactivePower_L3,omitempty" validate:"omitempty"`
	MaxNominalVoltage                      *decimal.Decimal `json:"maxNominalVoltage,omitempty" validate:"omitempty"`
	MinChargeReactivePower                 *decimal.Decimal `json:"minChargeReactivePower,omitempty" validate:"omitempty"`
	MinChargeReactivePower_L2              *decimal.Decimal `json:"minChargeReactivePower_L2,omitempty" validate:"omitempty"`
	MinChargeReactivePower_L3              *decimal.Decimal `json:"minChargeReactivePower_L3,omitempty" validate:"omitempty"`
	MinDischargeReactivePower              *decimal.Decimal `json:"minDischargeReactivePower,omitempty" validate:"omitempty"`
	MinDischargeReactivePower_L2           *decimal.Decimal `json:"minDischargeReactivePower_L2,omitempty" validate:"omitempty"`
	MinDischargeReactivePower_L3           *decimal.Decimal `json:"minDischargeReactivePower_L3,omitempty" validate:"omitempty"`
	MinNominalVoltage                      *decimal.Decimal `json:"minNominalVoltage,omitempty" validate:"omitempty"`
	NominalVoltage                         *decimal.Decimal `json:"nominalVoltage,omitempty" validate:"omitempty"`
	NominalVoltageOffset                   *decimal.Decimal `json:"nominalVoltageOffset,omitempty" validate:"omitempty"`
}

type EVEnergyOfferType struct {
	CustomData              *CustomDataType              `json:"customData,omitempty" validate:"omitempty"`
	EVAbsolutePriceSchedule *EVAbsolutePriceScheduleType `json:"evAbsolutePriceSchedule,omitempty" validate:"omitempty"`
	EVPowerSchedule         EVPowerScheduleType          `json:"evPowerSchedule" validate:"required"`
}

type EVAbsolutePriceScheduleType struct {
	Currency                       string                             `json:"currency" validate:"required,max=3"`
	CustomData                     *CustomDataType                    `json:"customData,omitempty" validate:"omitempty"`
	EVAbsolutePriceScheduleEntries []EVAbsolutePriceScheduleEntryType `json:"evAbsolutePriceScheduleEntries" validate:"required"`
	PriceAlgorithm                 string                             `json:"priceAlgorithm" validate:"required,max=2000"`
	TimeAnchor                     time.Time                          `json:"timeAnchor" validate:"required"`
}

type EVAbsolutePriceScheduleEntryType struct {
	CustomData  *CustomDataType   `json:"customData,omitempty" validate:"omitempty"`
	Duration    int32             `json:"duration" validate:"required"`
	EVPriceRule []EVPriceRuleType `json:"evPriceRule" validate:"required"`
}

type EVPriceRuleType struct {
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EnergyFee       decimal.Decimal `json:"energyFee" validate:"required"`
	PowerRangeStart decimal.Decimal `json:"powerRangeStart" validate:"required"`
}

type EVPowerScheduleType struct {
	CustomData             *CustomDataType            `json:"customData,omitempty" validate:"omitempty"`
	EVPowerScheduleEntries []EVPowerScheduleEntryType `json:"evPowerScheduleEntries" validate:"required"`
	TimeAnchor             time.Time                  `json:"timeAnchor" validate:"required"`
}

type EVPowerScheduleEntryType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Duration   int32           `json:"duration" validate:"required"`
	Power      decimal.Decimal `json:"power" validate:"required"`
}

type V2XChargingParametersType struct {
	CustomData            *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EVMaxEnergyRequest    *decimal.Decimal `json:"evMaxEnergyRequest,omitempty" validate:"omitempty"`
	EVMaxV2XEnergyRequest *decimal.Decimal `json:"evMaxV2XEnergyRequest,omitempty" validate:"omitempty"`
	EVMinEnergyRequest    *decimal.Decimal `json:"evMinEnergyRequest,omitempty" validate:"omitempty"`
	EVMinV2XEnergyRequest *decimal.Decimal `json:"evMinV2XEnergyRequest,omitempty" validate:"omitempty"`
	EVTargetEnergyRequest *decimal.Decimal `json:"evTargetEnergyRequest,omitempty" validate:"omitempty"`
	MaxChargeCurrent      *decimal.Decimal `json:"maxChargeCurrent,omitempty" validate:"omitempty"`
	MaxChargePower        *decimal.Decimal `json:"maxChargePower,omitempty" validate:"omitempty"`
	MaxChargePower_L2     *decimal.Decimal `json:"maxChargePower_L2,omitempty" validate:"omitempty"`
	MaxChargePower_L3     *decimal.Decimal `json:"maxChargePower_L3,omitempty" validate:"omitempty"`
	MaxDischargeCurrent   *decimal.Decimal `json:"maxDischargeCurrent,omitempty" validate:"omitempty"`
	MaxDischargePower     *decimal.Decimal `json:"maxDischargePower,omitempty" validate:"omitempty"`
	MaxDischargePower_L2  *decimal.Decimal `json:"maxDischargePower_L2,omitempty" validate:"omitempty"`
	MaxDischargePower_L3  *decimal.Decimal `json:"maxDischargePower_L3,omitempty" validate:"omitempty"`
	MaxVoltage            *decimal.Decimal `json:"maxVoltage,omitempty" validate:"omitempty"`
	MinChargeCurrent      *decimal.Decimal `json:"minChargeCurrent,omitempty" validate:"omitempty"`
	MinChargePower        *decimal.Decimal `json:"minChargePower,omitempty" validate:"omitempty"`
	MinChargePower_L2     *decimal.Decimal `json:"minChargePower_L2,omitempty" validate:"omitempty"`
	MinChargePower_L3     *decimal.Decimal `json:"minChargePower_L3,omitempty" validate:"omitempty"`
	MinDischargeCurrent   *decimal.Decimal `json:"minDischargeCurrent,omitempty" validate:"omitempty"`
	MinDischargePower     *decimal.Decimal `json:"minDischargePower,omitempty" validate:"omitempty"`
	MinDischargePower_L2  *decimal.Decimal `json:"minDischargePower_L2,omitempty" validate:"omitempty"`
	MinDischargePower_L3  *decimal.Decimal `json:"minDischargePower_L3,omitempty" validate:"omitempty"`
	MinVoltage            *decimal.Decimal `json:"minVoltage,omitempty" validate:"omitempty"`
	TargetSoC             *int32           `json:"targetSoC,omitempty" validate:"omitempty"`
}

type NotifyEVChargingNeedsResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
