// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type NotifyCustomerInformationRequest struct {
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Data        string          `json:"data" validate:"required,max=512"`
	GeneratedAt time.Time       `json:"generatedAt" validate:"required"`
	RequestID   int32           `json:"requestId" validate:"required"`
	SeqNo       int32           `json:"seqNo" validate:"required"`
	Tbc         *bool           `json:"tbc,omitempty" validate:"omitempty"`
}

type NotifyCustomerInformationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
