// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type NotifyDERAlarmRequest struct {
	AlarmEnded     *bool           `json:"alarmEnded,omitempty" validate:"omitempty"`
	ControlType    string          `json:"controlType" validate:"required"`
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ExtraInfo      *string         `json:"extraInfo,omitempty" validate:"omitempty,max=200"`
	GridEventFault *string         `json:"gridEventFault,omitempty" validate:"omitempty"`
	Timestamp      time.Time       `json:"timestamp" validate:"required"`
}

type NotifyDERAlarmResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
