// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type NotifySettlementRequest struct {
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	PspRef           string          `json:"pspRef" validate:"required,max=255"`
	ReceiptID        *string         `json:"receiptId,omitempty" validate:"omitempty,max=50"`
	ReceiptURL       *string         `json:"receiptUrl,omitempty" validate:"omitempty,max=2000"`
	SettlementAmount decimal.Decimal `json:"settlementAmount" validate:"required"`
	SettlementTime   time.Time       `json:"settlementTime" validate:"required"`
	Status           string          `json:"status" validate:"required"`
	StatusInfo       *string         `json:"statusInfo,omitempty" validate:"omitempty,max=500"`
	TransactionID    *string         `json:"transactionId,omitempty" validate:"omitempty,max=36"`
	VatCompany       *AddressType    `json:"vatCompany,omitempty" validate:"omitempty"`
	VatNumber        *string         `json:"vatNumber,omitempty" validate:"omitempty,max=20"`
}

type AddressType struct {
	Address1   string          `json:"address1" validate:"required,max=100"`
	Address2   *string         `json:"address2,omitempty" validate:"omitempty,max=100"`
	City       string          `json:"city" validate:"required,max=100"`
	Country    string          `json:"country" validate:"required,max=50"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Name       string          `json:"name" validate:"required,max=50"`
	PostalCode *string         `json:"postalCode,omitempty" validate:"omitempty,max=20"`
}

type NotifySettlementResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ReceiptID  *string         `json:"receiptId,omitempty" validate:"omitempty,max=50"`
	ReceiptURL *string         `json:"receiptUrl,omitempty" validate:"omitempty,max=2000"`
}
