// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type NotifyPriorityChargingRequest struct {
	Activated     bool            `json:"activated" validate:"required"`
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	TransactionID string          `json:"transactionId" validate:"required,max=36"`
}

type NotifyPriorityChargingResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
