// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type OpenPeriodicEventStreamRequest struct {
	ConstantStreamData ConstantStreamDataType `json:"constantStreamData" validate:"required"`
	CustomData         *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
}

type OpenPeriodicEventStreamResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
