// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type PullDynamicScheduleUpdateRequest struct {
	ChargingProfileID int32           `json:"chargingProfileId" validate:"required"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type PullDynamicScheduleUpdateResponse struct {
	CustomData     *CustomDataType             `json:"customData,omitempty" validate:"omitempty"`
	ScheduleUpdate *ChargingScheduleUpdateType `json:"scheduleUpdate,omitempty" validate:"omitempty"`
	Status         string                      `json:"status" validate:"required"`
	StatusInfo     *StatusInfoType             `json:"statusInfo,omitempty" validate:"omitempty"`
}
