// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ReportDERControlRequest struct {
	Curve             []DERCurveGetType          `json:"curve,omitempty" validate:"omitempty"`
	CustomData        *CustomDataType            `json:"customData,omitempty" validate:"omitempty"`
	EnterService      []EnterServiceGetType      `json:"enterService,omitempty" validate:"omitempty"`
	FixedPFAbsorb     []FixedPFGetType           `json:"fixedPFAbsorb,omitempty" validate:"omitempty"`
	FixedPFInject     []FixedPFGetType           `json:"fixedPFInject,omitempty" validate:"omitempty"`
	FixedVar          []FixedVarGetType          `json:"fixedVar,omitempty" validate:"omitempty"`
	FreqDroop         []FreqDroopGetType         `json:"freqDroop,omitempty" validate:"omitempty"`
	Gradient          []GradientGetType          `json:"gradient,omitempty" validate:"omitempty"`
	LimitMaxDischarge []LimitMaxDischargeGetType `json:"limitMaxDischarge,omitempty" validate:"omitempty"`
	RequestID         int32                      `json:"requestId" validate:"required"`
	Tbc               *bool                      `json:"tbc,omitempty" validate:"omitempty"`
}

type DERCurveGetType struct {
	Curve        DERCurveType    `json:"curve" validate:"required"`
	CurveType    string          `json:"curveType" validate:"required"`
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ID           string          `json:"id" validate:"required,max=36"`
	IsDefault    bool            `json:"isDefault" validate:"required"`
	IsSuperseded bool            `json:"isSuperseded" validate:"required"`
}

type EnterServiceGetType struct {
	CustomData   *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EnterService EnterServiceType `json:"enterService" validate:"required"`
	ID           string           `json:"id" validate:"required,max=36"`
}

type FixedPFGetType struct {
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	FixedPF      FixedPFType     `json:"fixedPF" validate:"required"`
	ID           string          `json:"id" validate:"required,max=36"`
	IsDefault    bool            `json:"isDefault" validate:"required"`
	IsSuperseded bool            `json:"isSuperseded" validate:"required"`
}

type FixedVarGetType struct {
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	FixedVar     FixedVarType    `json:"fixedVar" validate:"required"`
	ID           string          `json:"id" validate:"required,max=36"`
	IsDefault    bool            `json:"isDefault" validate:"required"`
	IsSuperseded bool            `json:"isSuperseded" validate:"required"`
}

type FreqDroopGetType struct {
	CustomData   *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	FreqDroop    FreqDroopType   `json:"freqDroop" validate:"required"`
	ID           string          `json:"id" validate:"required,max=36"`
	IsDefault    bool            `json:"isDefault" validate:"required"`
	IsSuperseded bool            `json:"isSuperseded" validate:"required"`
}

type GradientGetType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Gradient   GradientType    `json:"gradient" validate:"required"`
	ID         string          `json:"id" validate:"required,max=36"`
}

type LimitMaxDischargeGetType struct {
	CustomData        *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	ID                string                `json:"id" validate:"required,max=36"`
	IsDefault         bool                  `json:"isDefault" validate:"required"`
	IsSuperseded      bool                  `json:"isSuperseded" validate:"required"`
	LimitMaxDischarge LimitMaxDischargeType `json:"limitMaxDischarge" validate:"required"`
}

type ReportDERControlResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
