// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type RequestBatterySwapRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	IDToken    IdTokenType     `json:"idToken" validate:"required"`
	RequestID  int32           `json:"requestId" validate:"required"`
}

type RequestBatterySwapResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
