// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type RequestStartTransactionRequest struct {
	ChargingProfile *ChargingProfileType `json:"chargingProfile,omitempty" validate:"omitempty"`
	CustomData      *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	EVSEID          *int32               `json:"evseId,omitempty" validate:"omitempty"`
	GroupIDToken    *IdTokenType         `json:"groupIdToken,omitempty" validate:"omitempty"`
	IDToken         IdTokenType          `json:"idToken" validate:"required"`
	RemoteStartID   int32                `json:"remoteStartId" validate:"required"`
}

type ChargingProfileType struct {
	ChargingProfileKind         string                 `json:"chargingProfileKind" validate:"required"`
	ChargingProfilePurpose      string                 `json:"chargingProfilePurpose" validate:"required"`
	ChargingSchedule            []ChargingScheduleType `json:"chargingSchedule" validate:"required"`
	CustomData                  *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	DynUpdateInterval           *int32                 `json:"dynUpdateInterval,omitempty" validate:"omitempty"`
	DynUpdateTime               *time.Time             `json:"dynUpdateTime,omitempty" validate:"omitempty"`
	ID                          int32                  `json:"id" validate:"required"`
	InvalidAfterOfflineDuration *bool                  `json:"invalidAfterOfflineDuration,omitempty" validate:"omitempty"`
	MaxOfflineDuration          *int32                 `json:"maxOfflineDuration,omitempty" validate:"omitempty"`
	PriceScheduleSignature      *string                `json:"priceScheduleSignature,omitempty" validate:"omitempty,max=256"`
	RecurrencyKind              *string                `json:"recurrencyKind,omitempty" validate:"omitempty"`
	StackLevel                  int32                  `json:"stackLevel" validate:"required"`
	TransactionID               *string                `json:"transactionId,omitempty" validate:"omitempty,max=36"`
	ValidFrom                   *time.Time             `json:"validFrom,omitempty" validate:"omitempty"`
	ValidTo                     *time.Time             `json:"validTo,omitempty" validate:"omitempty"`
}

type ChargingScheduleType struct {
	AbsolutePriceSchedule  *AbsolutePriceScheduleType   `json:"absolutePriceSchedule,omitempty" validate:"omitempty"`
	ChargingRateUnit       string                       `json:"chargingRateUnit" validate:"required"`
	ChargingSchedulePeriod []ChargingSchedulePeriodType `json:"chargingSchedulePeriod" validate:"required"`
	CustomData             *CustomDataType              `json:"customData,omitempty" validate:"omitempty"`
	DigestValue            *string                      `json:"digestValue,omitempty" validate:"omitempty,max=88"`
	Duration               *int32                       `json:"duration,omitempty" validate:"omitempty"`
	ID                     int32                        `json:"id" validate:"required"`
	LimitAtSoC             *LimitAtSoCType              `json:"limitAtSoC,omitempty" validate:"omitempty"`
	MinChargingRate        *decimal.Decimal             `json:"minChargingRate,omitempty" validate:"omitempty"`
	PowerTolerance         *decimal.Decimal             `json:"powerTolerance,omitempty" validate:"omitempty"`
	PriceLevelSchedule     *PriceLevelScheduleType      `json:"priceLevelSchedule,omitempty" validate:"omitempty"`
	RandomizedDelay        *int32                       `json:"randomizedDelay,omitempty" validate:"omitempty"`
	SalesTariff            *SalesTariffType             `json:"salesTariff,omitempty" validate:"omitempty"`
	SignatureID            *int32                       `json:"signatureId,omitempty" validate:"omitempty"`
	StartSchedule          *time.Time                   `json:"startSchedule,omitempty" validate:"omitempty"`
	UseLocalTime           *bool                        `json:"useLocalTime,omitempty" validate:"omitempty"`
}

type AbsolutePriceScheduleType struct {
	AdditionalSelectedServices []AdditionalSelectedServicesType `json:"additionalSelectedServices,omitempty" validate:"omitempty"`
	Currency                   string                           `json:"currency" validate:"required,max=3"`
	CustomData                 *CustomDataType                  `json:"customData,omitempty" validate:"omitempty"`
	Language                   string                           `json:"language" validate:"required,max=8"`
	MaximumCost                *RationalNumberType              `json:"maximumCost,omitempty" validate:"omitempty"`
	MinimumCost                *RationalNumberType              `json:"minimumCost,omitempty" validate:"omitempty"`
	OverstayRuleList           *OverstayRuleListType            `json:"overstayRuleList,omitempty" validate:"omitempty"`
	PriceAlgorithm             string                           `json:"priceAlgorithm" validate:"required,max=2000"`
	PriceRuleStacks            []PriceRuleStackType             `json:"priceRuleStacks" validate:"required"`
	PriceScheduleDescription   *string                          `json:"priceScheduleDescription,omitempty" validate:"omitempty,max=160"`
	PriceScheduleID            int32                            `json:"priceScheduleID" validate:"required"`
	TaxRules                   []TaxRuleType                    `json:"taxRules,omitempty" validate:"omitempty"`
	TimeAnchor                 time.Time                        `json:"timeAnchor" validate:"required"`
}

type AdditionalSelectedServicesType struct {
	CustomData  *CustomDataType    `json:"customData,omitempty" validate:"omitempty"`
	ServiceFee  RationalNumberType `json:"serviceFee" validate:"required"`
	ServiceName string             `json:"serviceName" validate:"required,max=80"`
}

type RationalNumberType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Exponent   int32           `json:"exponent" validate:"required"`
	Value      int32           `json:"value" validate:"required"`
}

type OverstayRuleListType struct {
	CustomData             *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	OverstayPowerThreshold *RationalNumberType `json:"overstayPowerThreshold,omitempty" validate:"omitempty"`
	OverstayRule           []OverstayRuleType  `json:"overstayRule" validate:"required"`
	OverstayTimeThreshold  *int32              `json:"overstayTimeThreshold,omitempty" validate:"omitempty"`
}

type OverstayRuleType struct {
	CustomData              *CustomDataType    `json:"customData,omitempty" validate:"omitempty"`
	OverstayFee             RationalNumberType `json:"overstayFee" validate:"required"`
	OverstayFeePeriod       int32              `json:"overstayFeePeriod" validate:"required"`
	OverstayRuleDescription *string            `json:"overstayRuleDescription,omitempty" validate:"omitempty,max=32"`
	StartTime               int32              `json:"startTime" validate:"required"`
}

type PriceRuleStackType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Duration   int32           `json:"duration" validate:"required"`
	PriceRule  []PriceRuleType `json:"priceRule" validate:"required"`
}

type PriceRuleType struct {
	CarbonDioxideEmission         *int32              `json:"carbonDioxideEmission,omitempty" validate:"omitempty"`
	CustomData                    *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	EnergyFee                     RationalNumberType  `json:"energyFee" validate:"required"`
	ParkingFee                    *RationalNumberType `json:"parkingFee,omitempty" validate:"omitempty"`
	ParkingFeePeriod              *int32              `json:"parkingFeePeriod,omitempty" validate:"omitempty"`
	PowerRangeStart               RationalNumberType  `json:"powerRangeStart" validate:"required"`
	RenewableGenerationPercentage *int32              `json:"renewableGenerationPercentage,omitempty" validate:"omitempty"`
}

type TaxRuleType struct {
	AppliesToEnergyFee          bool               `json:"appliesToEnergyFee"`
	AppliesToMinimumMaximumCost bool               `json:"appliesToMinimumMaximumCost"`
	AppliesToOverstayFee        bool               `json:"appliesToOverstayFee"`
	AppliesToParkingFee         bool               `json:"appliesToParkingFee"`
	CustomData                  *CustomDataType    `json:"customData,omitempty" validate:"omitempty"`
	TaxIncludedInPrice          *bool              `json:"taxIncludedInPrice,omitempty" validate:"omitempty"`
	TaxRate                     RationalNumberType `json:"taxRate" validate:"required"`
	TaxRuleID                   int32              `json:"taxRuleID" validate:"required"`
	TaxRuleName                 *string            `json:"taxRuleName,omitempty" validate:"omitempty,max=100"`
}

type ChargingSchedulePeriodType struct {
	CustomData             *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
	DischargeLimit         *decimal.Decimal         `json:"dischargeLimit,omitempty" validate:"omitempty"`
	DischargeLimit_L2      *decimal.Decimal         `json:"dischargeLimit_L2,omitempty" validate:"omitempty"`
	DischargeLimit_L3      *decimal.Decimal         `json:"dischargeLimit_L3,omitempty" validate:"omitempty"`
	EVSESleep              *bool                    `json:"evseSleep,omitempty" validate:"omitempty"`
	Limit                  *decimal.Decimal         `json:"limit,omitempty" validate:"omitempty"`
	Limit_L2               *decimal.Decimal         `json:"limit_L2,omitempty" validate:"omitempty"`
	Limit_L3               *decimal.Decimal         `json:"limit_L3,omitempty" validate:"omitempty"`
	NumberPhases           *int32                   `json:"numberPhases,omitempty" validate:"omitempty"`
	OperationMode          *string                  `json:"operationMode,omitempty" validate:"omitempty"`
	PhaseToUse             *int32                   `json:"phaseToUse,omitempty" validate:"omitempty"`
	PreconditioningRequest *bool                    `json:"preconditioningRequest,omitempty" validate:"omitempty"`
	Setpoint               *decimal.Decimal         `json:"setpoint,omitempty" validate:"omitempty"`
	SetpointReactive       *decimal.Decimal         `json:"setpointReactive,omitempty" validate:"omitempty"`
	SetpointReactive_L2    *decimal.Decimal         `json:"setpointReactive_L2,omitempty" validate:"omitempty"`
	SetpointReactive_L3    *decimal.Decimal         `json:"setpointReactive_L3,omitempty" validate:"omitempty"`
	Setpoint_L2            *decimal.Decimal         `json:"setpoint_L2,omitempty" validate:"omitempty"`
	Setpoint_L3            *decimal.Decimal         `json:"setpoint_L3,omitempty" validate:"omitempty"`
	StartPeriod            int32                    `json:"startPeriod" validate:"required"`
	V2xBaseline            *decimal.Decimal         `json:"v2xBaseline,omitempty" validate:"omitempty"`
	V2xFreqWattCurve       []V2XFreqWattPointType   `json:"v2xFreqWattCurve,omitempty" validate:"omitempty"`
	V2xSignalWattCurve     []V2XSignalWattPointType `json:"v2xSignalWattCurve,omitempty" validate:"omitempty"`
}

type V2XFreqWattPointType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Frequency  decimal.Decimal `json:"frequency" validate:"required"`
	Power      decimal.Decimal `json:"power" validate:"required"`
}

type V2XSignalWattPointType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Power      decimal.Decimal `json:"power" validate:"required"`
	Signal     int32           `json:"signal" validate:"required"`
}

type LimitAtSoCType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Limit      decimal.Decimal `json:"limit" validate:"required"`
	SOC        int32           `json:"soc" validate:"required"`
}

type PriceLevelScheduleType struct {
	CustomData                *CustomDataType               `json:"customData,omitempty" validate:"omitempty"`
	NumberOfPriceLevels       int32                         `json:"numberOfPriceLevels" validate:"required"`
	PriceLevelScheduleEntries []PriceLevelScheduleEntryType `json:"priceLevelScheduleEntries" validate:"required"`
	PriceScheduleDescription  *string                       `json:"priceScheduleDescription,omitempty" validate:"omitempty,max=32"`
	PriceScheduleID           int32                         `json:"priceScheduleId" validate:"required"`
	TimeAnchor                time.Time                     `json:"timeAnchor" validate:"required"`
}

type PriceLevelScheduleEntryType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Duration   int32           `json:"duration" validate:"required"`
	PriceLevel int32           `json:"priceLevel" validate:"required"`
}

type SalesTariffType struct {
	CustomData             *CustomDataType        `json:"customData,omitempty" validate:"omitempty"`
	ID                     int32                  `json:"id" validate:"required"`
	NumEPriceLevels        *int32                 `json:"numEPriceLevels,omitempty" validate:"omitempty"`
	SalesTariffDescription *string                `json:"salesTariffDescription,omitempty" validate:"omitempty,max=32"`
	SalesTariffEntry       []SalesTariffEntryType `json:"salesTariffEntry" validate:"required"`
}

type SalesTariffEntryType struct {
	ConsumptionCost      []ConsumptionCostType    `json:"consumptionCost,omitempty" validate:"omitempty"`
	CustomData           *CustomDataType          `json:"customData,omitempty" validate:"omitempty"`
	EPriceLevel          *int32                   `json:"ePriceLevel,omitempty" validate:"omitempty"`
	RelativeTimeInterval RelativeTimeIntervalType `json:"relativeTimeInterval" validate:"required"`
}

type ConsumptionCostType struct {
	Cost       []CostType      `json:"cost" validate:"required"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	StartValue decimal.Decimal `json:"startValue" validate:"required"`
}

type CostType struct {
	Amount           int32           `json:"amount" validate:"required"`
	AmountMultiplier *int32          `json:"amountMultiplier,omitempty" validate:"omitempty"`
	CostKind         string          `json:"costKind" validate:"required"`
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type RelativeTimeIntervalType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Duration   *int32          `json:"duration,omitempty" validate:"omitempty"`
	Start      int32           `json:"start" validate:"required"`
}

type RequestStartTransactionResponse struct {
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status        string          `json:"status" validate:"required"`
	StatusInfo    *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
	TransactionID *string         `json:"transactionId,omitempty" validate:"omitempty,max=36"`
}
