// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type ReservationStatusUpdateRequest struct {
	CustomData              *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	ReservationID           int32           `json:"reservationId" validate:"required"`
	ReservationUpdateStatus string          `json:"reservationUpdateStatus" validate:"required"`
}

type ReservationStatusUpdateResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
