// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetDefaultTariffRequest struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID     int32           `json:"evseId" validate:"required"`
	Tariff     TariffType      `json:"tariff" validate:"required"`
}

type SetDefaultTariffResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
