// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetChargingProfileRequest struct {
	ChargingProfile ChargingProfileType `json:"chargingProfile" validate:"required"`
	CustomData      *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	EVSEID          int32               `json:"evseId" validate:"required"`
}

type SetChargingProfileResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
