// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetMonitoringBaseRequest struct {
	CustomData     *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	MonitoringBase string          `json:"monitoringBase" validate:"required"`
}

type SetMonitoringBaseResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
