// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type SetNetworkProfileRequest struct {
	ConfigurationSlot int32                        `json:"configurationSlot" validate:"required"`
	ConnectionData    NetworkConnectionProfileType `json:"connectionData" validate:"required"`
	CustomData        *CustomDataType              `json:"customData,omitempty" validate:"omitempty"`
}

type NetworkConnectionProfileType struct {
	Apn               *APNType        `json:"apn,omitempty" validate:"omitempty"`
	BasicAuthPassword *string         `json:"basicAuthPassword,omitempty" validate:"omitempty,max=64"`
	CustomData        *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Identity          *string         `json:"identity,omitempty" validate:"omitempty,max=48"`
	MessageTimeout    int32           `json:"messageTimeout" validate:"required"`
	OCPPCsmsURL       string          `json:"ocppCsmsUrl" validate:"required,max=2000"`
	OCPPInterface     string          `json:"ocppInterface" validate:"required"`
	OCPPTransport     string          `json:"ocppTransport" validate:"required"`
	OCPPVersion       *string         `json:"ocppVersion,omitempty" validate:"omitempty"`
	SecurityProfile   int32           `json:"securityProfile" validate:"required"`
	Vpn               *VPNType        `json:"vpn,omitempty" validate:"omitempty"`
}

type APNType struct {
	Apn                     string          `json:"apn" validate:"required,max=2000"`
	ApnAuthentication       string          `json:"apnAuthentication" validate:"required"`
	ApnPassword             *string         `json:"apnPassword,omitempty" validate:"omitempty,max=64"`
	ApnUserName             *string         `json:"apnUserName,omitempty" validate:"omitempty,max=50"`
	CustomData              *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	PreferredNetwork        *string         `json:"preferredNetwork,omitempty" validate:"omitempty,max=6"`
	SimPin                  *int32          `json:"simPin,omitempty" validate:"omitempty"`
	UseOnlyPreferredNetwork *bool           `json:"useOnlyPreferredNetwork,omitempty" validate:"omitempty"`
}

type VPNType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Group      *string         `json:"group,omitempty" validate:"omitempty,max=50"`
	Key        string          `json:"key" validate:"required,max=255"`
	Password   string          `json:"password" validate:"required,max=64"`
	Server     string          `json:"server" validate:"required,max=2000"`
	Type       string          `json:"type" validate:"required"`
	User       string          `json:"user" validate:"required,max=50"`
}

type SetNetworkProfileResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
