// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"time"
)

type StatusNotificationRequest struct {
	ConnectorID     int32           `json:"connectorId" validate:"required"`
	ConnectorStatus string          `json:"connectorStatus" validate:"required"`
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID          int32           `json:"evseId" validate:"required"`
	Timestamp       time.Time       `json:"timestamp" validate:"required"`
}

type StatusNotificationResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}
