// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
	"time"
)

type TransactionEventRequest struct {
	CableMaxCurrent       *int32           `json:"cableMaxCurrent,omitempty" validate:"omitempty"`
	CostDetails           *CostDetailsType `json:"costDetails,omitempty" validate:"omitempty"`
	CustomData            *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	EventType             string           `json:"eventType" validate:"required"`
	EVSE                  *EVSEType        `json:"evse,omitempty" validate:"omitempty"`
	EVSESleep             *bool            `json:"evseSleep,omitempty" validate:"omitempty"`
	IDToken               *IdTokenType     `json:"idToken,omitempty" validate:"omitempty"`
	MeterValue            []MeterValueType `json:"meterValue,omitempty" validate:"omitempty"`
	NumberOfPhasesUsed    *int32           `json:"numberOfPhasesUsed,omitempty" validate:"omitempty"`
	Offline               *bool            `json:"offline,omitempty" validate:"omitempty"`
	PreconditioningStatus *string          `json:"preconditioningStatus,omitempty" validate:"omitempty"`
	ReservationID         *int32           `json:"reservationId,omitempty" validate:"omitempty"`
	SeqNo                 int32            `json:"seqNo" validate:"required"`
	Timestamp             time.Time        `json:"timestamp" validate:"required"`
	TransactionInfo       TransactionType  `json:"transactionInfo" validate:"required"`
	TriggerReason         string           `json:"triggerReason" validate:"required"`
}

type CostDetailsType struct {
	ChargingPeriods    []ChargingPeriodType `json:"chargingPeriods,omitempty" validate:"omitempty"`
	CustomData         *CustomDataType      `json:"customData,omitempty" validate:"omitempty"`
	FailureReason      *string              `json:"failureReason,omitempty" validate:"omitempty,max=500"`
	FailureToCalculate *bool                `json:"failureToCalculate,omitempty" validate:"omitempty"`
	TotalCost          TotalCostType        `json:"totalCost" validate:"required"`
	TotalUsage         TotalUsageType       `json:"totalUsage" validate:"required"`
}

type ChargingPeriodType struct {
	CustomData  *CustomDataType     `json:"customData,omitempty" validate:"omitempty"`
	Dimensions  []CostDimensionType `json:"dimensions,omitempty" validate:"omitempty"`
	StartPeriod time.Time           `json:"startPeriod" validate:"required"`
	TariffID    *string             `json:"tariffId,omitempty" validate:"omitempty,max=60"`
}

type CostDimensionType struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Type       string          `json:"type" validate:"required"`
	Volume     decimal.Decimal `json:"volume" validate:"required"`
}

type TotalCostType struct {
	ChargingTime     *PriceType      `json:"chargingTime,omitempty" validate:"omitempty"`
	Currency         string          `json:"currency" validate:"required,max=3"`
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Energy           *PriceType      `json:"energy,omitempty" validate:"omitempty"`
	Fixed            *PriceType      `json:"fixed,omitempty" validate:"omitempty"`
	IdleTime         *PriceType      `json:"idleTime,omitempty" validate:"omitempty"`
	ReservationFixed *PriceType      `json:"reservationFixed,omitempty" validate:"omitempty"`
	ReservationTime  *PriceType      `json:"reservationTime,omitempty" validate:"omitempty"`
	Total            TotalPriceType  `json:"total" validate:"required"`
	TypeOfCost       string          `json:"typeOfCost" validate:"required"`
}

type TotalPriceType struct {
	CustomData *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	ExclTax    *decimal.Decimal `json:"exclTax,omitempty" validate:"omitempty"`
	InclTax    *decimal.Decimal `json:"inclTax,omitempty" validate:"omitempty"`
}

type TotalUsageType struct {
	ChargingTime    int32           `json:"chargingTime" validate:"required"`
	CustomData      *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Energy          decimal.Decimal `json:"energy" validate:"required"`
	IdleTime        int32           `json:"idleTime" validate:"required"`
	ReservationTime *int32          `json:"reservationTime,omitempty" validate:"omitempty"`
}

type TransactionType struct {
	ChargingState     *string               `json:"chargingState,omitempty" validate:"omitempty"`
	CustomData        *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	OperationMode     *string               `json:"operationMode,omitempty" validate:"omitempty"`
	RemoteStartID     *int32                `json:"remoteStartId,omitempty" validate:"omitempty"`
	StoppedReason     *string               `json:"stoppedReason,omitempty" validate:"omitempty"`
	TariffID          *string               `json:"tariffId,omitempty" validate:"omitempty,max=60"`
	TimeSpentCharging *int32                `json:"timeSpentCharging,omitempty" validate:"omitempty"`
	TransactionID     string                `json:"transactionId" validate:"required,max=36"`
	TransactionLimit  *TransactionLimitType `json:"transactionLimit,omitempty" validate:"omitempty"`
}

type TransactionLimitType struct {
	CustomData *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	MaxCost    *decimal.Decimal `json:"maxCost,omitempty" validate:"omitempty"`
	MaxEnergy  *decimal.Decimal `json:"maxEnergy,omitempty" validate:"omitempty"`
	MaxSoC     *int32           `json:"maxSoC,omitempty" validate:"omitempty"`
	MaxTime    *int32           `json:"maxTime,omitempty" validate:"omitempty"`
}

type TransactionEventResponse struct {
	ChargingPriority            *int32                `json:"chargingPriority,omitempty" validate:"omitempty"`
	CustomData                  *CustomDataType       `json:"customData,omitempty" validate:"omitempty"`
	IDTokenInfo                 *IdTokenInfoType      `json:"idTokenInfo,omitempty" validate:"omitempty"`
	TotalCost                   *decimal.Decimal      `json:"totalCost,omitempty" validate:"omitempty"`
	TransactionLimit            *TransactionLimitType `json:"transactionLimit,omitempty" validate:"omitempty"`
	UpdatedPersonalMessage      *MessageContentType   `json:"updatedPersonalMessage,omitempty" validate:"omitempty"`
	UpdatedPersonalMessageExtra []MessageContentType  `json:"updatedPersonalMessageExtra,omitempty" validate:"omitempty"`
}
