// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type TriggerMessageRequest struct {
	CustomData       *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	CustomTrigger    *string         `json:"customTrigger,omitempty" validate:"omitempty,max=50"`
	EVSE             *EVSEType       `json:"evse,omitempty" validate:"omitempty"`
	RequestedMessage string          `json:"requestedMessage" validate:"required"`
}

type TriggerMessageResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
