// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type UnlockConnectorRequest struct {
	ConnectorID int32           `json:"connectorId" validate:"required"`
	CustomData  *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	EVSEID      int32           `json:"evseId" validate:"required"`
}

type UnlockConnectorResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
