// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type UnpublishFirmwareRequest struct {
	Checksum   string          `json:"checksum" validate:"required,max=32"`
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
}

type UnpublishFirmwareResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
}
