// Code generated by gocpp codegen. DO NOT EDIT.

package messages

import (
	"github.com/shopspring/decimal"
)

type UpdateDynamicScheduleRequest struct {
	ChargingProfileID int32                      `json:"chargingProfileId" validate:"required"`
	CustomData        *CustomDataType            `json:"customData,omitempty" validate:"omitempty"`
	ScheduleUpdate    ChargingScheduleUpdateType `json:"scheduleUpdate" validate:"required"`
}

type ChargingScheduleUpdateType struct {
	CustomData          *CustomDataType  `json:"customData,omitempty" validate:"omitempty"`
	DischargeLimit      *decimal.Decimal `json:"dischargeLimit,omitempty" validate:"omitempty"`
	DischargeLimit_L2   *decimal.Decimal `json:"dischargeLimit_L2,omitempty" validate:"omitempty"`
	DischargeLimit_L3   *decimal.Decimal `json:"dischargeLimit_L3,omitempty" validate:"omitempty"`
	Limit               *decimal.Decimal `json:"limit,omitempty" validate:"omitempty"`
	Limit_L2            *decimal.Decimal `json:"limit_L2,omitempty" validate:"omitempty"`
	Limit_L3            *decimal.Decimal `json:"limit_L3,omitempty" validate:"omitempty"`
	Setpoint            *decimal.Decimal `json:"setpoint,omitempty" validate:"omitempty"`
	SetpointReactive    *decimal.Decimal `json:"setpointReactive,omitempty" validate:"omitempty"`
	SetpointReactive_L2 *decimal.Decimal `json:"setpointReactive_L2,omitempty" validate:"omitempty"`
	SetpointReactive_L3 *decimal.Decimal `json:"setpointReactive_L3,omitempty" validate:"omitempty"`
	Setpoint_L2         *decimal.Decimal `json:"setpoint_L2,omitempty" validate:"omitempty"`
	Setpoint_L3         *decimal.Decimal `json:"setpoint_L3,omitempty" validate:"omitempty"`
}

type UpdateDynamicScheduleResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
