// Code generated by gocpp codegen. DO NOT EDIT.

package messages

type UsePriorityChargingRequest struct {
	Activate      bool            `json:"activate" validate:"required"`
	CustomData    *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	TransactionID string          `json:"transactionId" validate:"required,max=36"`
}

type UsePriorityChargingResponse struct {
	CustomData *CustomDataType `json:"customData,omitempty" validate:"omitempty"`
	Status     string          `json:"status" validate:"required"`
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" validate:"omitempty"`
}
