// Code generated by gocpp codegen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/shiv3/gocpp/cp"
	"github.com/shiv3/gocpp/csms"
	"github.com/shiv3/gocpp/v21/messages"
	"github.com/shiv3/gocpp/v21/profiles"
)

// CP wraps *cp.Client with typed send methods for messages a charge point
// sends to the CSMS.
type CP struct{ *cp.Client }

// NewCP wraps c so its CP->CSMS messages can be sent as methods.
func NewCP(c *cp.Client) CP { return CP{c} }

// Authorize sends a Authorize request from the charge point to the CSMS.
func (c CP) Authorize(ctx context.Context, req messages.AuthorizeRequest) (messages.AuthorizeResponse, error) {
	return cp.Call(ctx, c.Client, profiles.Authorize, req)
}

// AuthorizeAsync sends a Authorize request without blocking, delivering the response to cb.
func (c CP) AuthorizeAsync(ctx context.Context, req messages.AuthorizeRequest, cb func(messages.AuthorizeResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.Authorize, req, cb)
}

// NotifySettlement sends a NotifySettlement request from the charge point to the CSMS.
func (c CP) NotifySettlement(ctx context.Context, req messages.NotifySettlementRequest) (messages.NotifySettlementResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifySettlement, req)
}

// NotifySettlementAsync sends a NotifySettlement request without blocking, delivering the response to cb.
func (c CP) NotifySettlementAsync(ctx context.Context, req messages.NotifySettlementRequest, cb func(messages.NotifySettlementResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifySettlement, req, cb)
}

// VatNumberValidation sends a VatNumberValidation request from the charge point to the CSMS.
func (c CP) VatNumberValidation(ctx context.Context, req messages.VatNumberValidationRequest) (messages.VatNumberValidationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.VatNumberValidation, req)
}

// VatNumberValidationAsync sends a VatNumberValidation request without blocking, delivering the response to cb.
func (c CP) VatNumberValidationAsync(ctx context.Context, req messages.VatNumberValidationRequest, cb func(messages.VatNumberValidationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.VatNumberValidation, req, cb)
}

// StatusNotification sends a StatusNotification request from the charge point to the CSMS.
func (c CP) StatusNotification(ctx context.Context, req messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.StatusNotification, req)
}

// StatusNotificationAsync sends a StatusNotification request without blocking, delivering the response to cb.
func (c CP) StatusNotificationAsync(ctx context.Context, req messages.StatusNotificationRequest, cb func(messages.StatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.StatusNotification, req, cb)
}

// RequestBatterySwap sends a RequestBatterySwap request from the charge point to the CSMS.
func (c CP) RequestBatterySwap(ctx context.Context, req messages.RequestBatterySwapRequest) (messages.RequestBatterySwapResponse, error) {
	return cp.Call(ctx, c.Client, profiles.RequestBatterySwap, req)
}

// RequestBatterySwapAsync sends a RequestBatterySwap request without blocking, delivering the response to cb.
func (c CP) RequestBatterySwapAsync(ctx context.Context, req messages.RequestBatterySwapRequest, cb func(messages.RequestBatterySwapResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.RequestBatterySwap, req, cb)
}

// NotifyDERAlarm sends a NotifyDERAlarm request from the charge point to the CSMS.
func (c CP) NotifyDERAlarm(ctx context.Context, req messages.NotifyDERAlarmRequest) (messages.NotifyDERAlarmResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyDERAlarm, req)
}

// NotifyDERAlarmAsync sends a NotifyDERAlarm request without blocking, delivering the response to cb.
func (c CP) NotifyDERAlarmAsync(ctx context.Context, req messages.NotifyDERAlarmRequest, cb func(messages.NotifyDERAlarmResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyDERAlarm, req, cb)
}

// NotifyDERStartStop sends a NotifyDERStartStop request from the charge point to the CSMS.
func (c CP) NotifyDERStartStop(ctx context.Context, req messages.NotifyDERStartStopRequest) (messages.NotifyDERStartStopResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyDERStartStop, req)
}

// NotifyDERStartStopAsync sends a NotifyDERStartStop request without blocking, delivering the response to cb.
func (c CP) NotifyDERStartStopAsync(ctx context.Context, req messages.NotifyDERStartStopRequest, cb func(messages.NotifyDERStartStopResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyDERStartStop, req, cb)
}

// ReportDERControl sends a ReportDERControl request from the charge point to the CSMS.
func (c CP) ReportDERControl(ctx context.Context, req messages.ReportDERControlRequest) (messages.ReportDERControlResponse, error) {
	return cp.Call(ctx, c.Client, profiles.ReportDERControl, req)
}

// ReportDERControlAsync sends a ReportDERControl request without blocking, delivering the response to cb.
func (c CP) ReportDERControlAsync(ctx context.Context, req messages.ReportDERControlRequest, cb func(messages.ReportDERControlResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.ReportDERControl, req, cb)
}

// DataTransfer sends a DataTransfer request from the charge point to the CSMS.
func (c CP) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return cp.Call(ctx, c.Client, profiles.DataTransfer, req)
}

// DataTransferAsync sends a DataTransfer request without blocking, delivering the response to cb.
func (c CP) DataTransferAsync(ctx context.Context, req messages.DataTransferRequest, cb func(messages.DataTransferResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.DataTransfer, req, cb)
}

// NotifyEvent sends a NotifyEvent request from the charge point to the CSMS.
func (c CP) NotifyEvent(ctx context.Context, req messages.NotifyEventRequest) (messages.NotifyEventResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyEvent, req)
}

// NotifyEventAsync sends a NotifyEvent request without blocking, delivering the response to cb.
func (c CP) NotifyEventAsync(ctx context.Context, req messages.NotifyEventRequest, cb func(messages.NotifyEventResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyEvent, req, cb)
}

// NotifyMonitoringReport sends a NotifyMonitoringReport request from the charge point to the CSMS.
func (c CP) NotifyMonitoringReport(ctx context.Context, req messages.NotifyMonitoringReportRequest) (messages.NotifyMonitoringReportResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyMonitoringReport, req)
}

// NotifyMonitoringReportAsync sends a NotifyMonitoringReport request without blocking, delivering the response to cb.
func (c CP) NotifyMonitoringReportAsync(ctx context.Context, req messages.NotifyMonitoringReportRequest, cb func(messages.NotifyMonitoringReportResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyMonitoringReport, req, cb)
}

// LogStatusNotification sends a LogStatusNotification request from the charge point to the CSMS.
func (c CP) LogStatusNotification(ctx context.Context, req messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.LogStatusNotification, req)
}

// LogStatusNotificationAsync sends a LogStatusNotification request without blocking, delivering the response to cb.
func (c CP) LogStatusNotificationAsync(ctx context.Context, req messages.LogStatusNotificationRequest, cb func(messages.LogStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.LogStatusNotification, req, cb)
}

// NotifyCustomerInformation sends a NotifyCustomerInformation request from the charge point to the CSMS.
func (c CP) NotifyCustomerInformation(ctx context.Context, req messages.NotifyCustomerInformationRequest) (messages.NotifyCustomerInformationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyCustomerInformation, req)
}

// NotifyCustomerInformationAsync sends a NotifyCustomerInformation request without blocking, delivering the response to cb.
func (c CP) NotifyCustomerInformationAsync(ctx context.Context, req messages.NotifyCustomerInformationRequest, cb func(messages.NotifyCustomerInformationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyCustomerInformation, req, cb)
}

// NotifyPeriodicEventStream sends a NotifyPeriodicEventStream SEND from the charge point to the CSMS (no response).
func (c CP) NotifyPeriodicEventStream(ctx context.Context, req messages.NotifyPeriodicEventStream) error {
	return cp.Send(ctx, c.Client, profiles.NotifyPeriodicEventStream, req)
}

// NotifyDisplayMessages sends a NotifyDisplayMessages request from the charge point to the CSMS.
func (c CP) NotifyDisplayMessages(ctx context.Context, req messages.NotifyDisplayMessagesRequest) (messages.NotifyDisplayMessagesResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyDisplayMessages, req)
}

// NotifyDisplayMessagesAsync sends a NotifyDisplayMessages request without blocking, delivering the response to cb.
func (c CP) NotifyDisplayMessagesAsync(ctx context.Context, req messages.NotifyDisplayMessagesRequest, cb func(messages.NotifyDisplayMessagesResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyDisplayMessages, req, cb)
}

// FirmwareStatusNotification sends a FirmwareStatusNotification request from the charge point to the CSMS.
func (c CP) FirmwareStatusNotification(ctx context.Context, req messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.FirmwareStatusNotification, req)
}

// FirmwareStatusNotificationAsync sends a FirmwareStatusNotification request without blocking, delivering the response to cb.
func (c CP) FirmwareStatusNotificationAsync(ctx context.Context, req messages.FirmwareStatusNotificationRequest, cb func(messages.FirmwareStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.FirmwareStatusNotification, req, cb)
}

// PublishFirmwareStatusNotification sends a PublishFirmwareStatusNotification request from the charge point to the CSMS.
func (c CP) PublishFirmwareStatusNotification(ctx context.Context, req messages.PublishFirmwareStatusNotificationRequest) (messages.PublishFirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.PublishFirmwareStatusNotification, req)
}

// PublishFirmwareStatusNotificationAsync sends a PublishFirmwareStatusNotification request without blocking, delivering the response to cb.
func (c CP) PublishFirmwareStatusNotificationAsync(ctx context.Context, req messages.PublishFirmwareStatusNotificationRequest, cb func(messages.PublishFirmwareStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.PublishFirmwareStatusNotification, req, cb)
}

// SignCertificate sends a SignCertificate request from the charge point to the CSMS.
func (c CP) SignCertificate(ctx context.Context, req messages.SignCertificateRequest) (messages.SignCertificateResponse, error) {
	return cp.Call(ctx, c.Client, profiles.SignCertificate, req)
}

// SignCertificateAsync sends a SignCertificate request without blocking, delivering the response to cb.
func (c CP) SignCertificateAsync(ctx context.Context, req messages.SignCertificateRequest, cb func(messages.SignCertificateResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.SignCertificate, req, cb)
}

// Get15118EVCertificate sends a Get15118EVCertificate request from the charge point to the CSMS.
func (c CP) Get15118EVCertificate(ctx context.Context, req messages.Get15118EVCertificateRequest) (messages.Get15118EVCertificateResponse, error) {
	return cp.Call(ctx, c.Client, profiles.Get15118EVCertificate, req)
}

// Get15118EVCertificateAsync sends a Get15118EVCertificate request without blocking, delivering the response to cb.
func (c CP) Get15118EVCertificateAsync(ctx context.Context, req messages.Get15118EVCertificateRequest, cb func(messages.Get15118EVCertificateResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.Get15118EVCertificate, req, cb)
}

// GetCertificateStatus sends a GetCertificateStatus request from the charge point to the CSMS.
func (c CP) GetCertificateStatus(ctx context.Context, req messages.GetCertificateStatusRequest) (messages.GetCertificateStatusResponse, error) {
	return cp.Call(ctx, c.Client, profiles.GetCertificateStatus, req)
}

// GetCertificateStatusAsync sends a GetCertificateStatus request without blocking, delivering the response to cb.
func (c CP) GetCertificateStatusAsync(ctx context.Context, req messages.GetCertificateStatusRequest, cb func(messages.GetCertificateStatusResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.GetCertificateStatus, req, cb)
}

// GetCertificateChainStatus sends a GetCertificateChainStatus request from the charge point to the CSMS.
func (c CP) GetCertificateChainStatus(ctx context.Context, req messages.GetCertificateChainStatusRequest) (messages.GetCertificateChainStatusResponse, error) {
	return cp.Call(ctx, c.Client, profiles.GetCertificateChainStatus, req)
}

// GetCertificateChainStatusAsync sends a GetCertificateChainStatus request without blocking, delivering the response to cb.
func (c CP) GetCertificateChainStatusAsync(ctx context.Context, req messages.GetCertificateChainStatusRequest, cb func(messages.GetCertificateChainStatusResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.GetCertificateChainStatus, req, cb)
}

// MeterValues sends a MeterValues request from the charge point to the CSMS.
func (c CP) MeterValues(ctx context.Context, req messages.MeterValuesRequest) (messages.MeterValuesResponse, error) {
	return cp.Call(ctx, c.Client, profiles.MeterValues, req)
}

// MeterValuesAsync sends a MeterValues request without blocking, delivering the response to cb.
func (c CP) MeterValuesAsync(ctx context.Context, req messages.MeterValuesRequest, cb func(messages.MeterValuesResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.MeterValues, req, cb)
}

// BootNotification sends a BootNotification request from the charge point to the CSMS.
func (c CP) BootNotification(ctx context.Context, req messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.BootNotification, req)
}

// BootNotificationAsync sends a BootNotification request without blocking, delivering the response to cb.
func (c CP) BootNotificationAsync(ctx context.Context, req messages.BootNotificationRequest, cb func(messages.BootNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.BootNotification, req, cb)
}

// Heartbeat sends a Heartbeat request from the charge point to the CSMS.
func (c CP) Heartbeat(ctx context.Context, req messages.HeartbeatRequest) (messages.HeartbeatResponse, error) {
	return cp.Call(ctx, c.Client, profiles.Heartbeat, req)
}

// HeartbeatAsync sends a Heartbeat request without blocking, delivering the response to cb.
func (c CP) HeartbeatAsync(ctx context.Context, req messages.HeartbeatRequest, cb func(messages.HeartbeatResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.Heartbeat, req, cb)
}

// NotifyReport sends a NotifyReport request from the charge point to the CSMS.
func (c CP) NotifyReport(ctx context.Context, req messages.NotifyReportRequest) (messages.NotifyReportResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyReport, req)
}

// NotifyReportAsync sends a NotifyReport request without blocking, delivering the response to cb.
func (c CP) NotifyReportAsync(ctx context.Context, req messages.NotifyReportRequest, cb func(messages.NotifyReportResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyReport, req, cb)
}

// ReservationStatusUpdate sends a ReservationStatusUpdate request from the charge point to the CSMS.
func (c CP) ReservationStatusUpdate(ctx context.Context, req messages.ReservationStatusUpdateRequest) (messages.ReservationStatusUpdateResponse, error) {
	return cp.Call(ctx, c.Client, profiles.ReservationStatusUpdate, req)
}

// ReservationStatusUpdateAsync sends a ReservationStatusUpdate request without blocking, delivering the response to cb.
func (c CP) ReservationStatusUpdateAsync(ctx context.Context, req messages.ReservationStatusUpdateRequest, cb func(messages.ReservationStatusUpdateResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.ReservationStatusUpdate, req, cb)
}

// SecurityEventNotification sends a SecurityEventNotification request from the charge point to the CSMS.
func (c CP) SecurityEventNotification(ctx context.Context, req messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.SecurityEventNotification, req)
}

// SecurityEventNotificationAsync sends a SecurityEventNotification request without blocking, delivering the response to cb.
func (c CP) SecurityEventNotificationAsync(ctx context.Context, req messages.SecurityEventNotificationRequest, cb func(messages.SecurityEventNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.SecurityEventNotification, req, cb)
}

// NotifyEVChargingNeeds sends a NotifyEVChargingNeeds request from the charge point to the CSMS.
func (c CP) NotifyEVChargingNeeds(ctx context.Context, req messages.NotifyEVChargingNeedsRequest) (messages.NotifyEVChargingNeedsResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyEVChargingNeeds, req)
}

// NotifyEVChargingNeedsAsync sends a NotifyEVChargingNeeds request without blocking, delivering the response to cb.
func (c CP) NotifyEVChargingNeedsAsync(ctx context.Context, req messages.NotifyEVChargingNeedsRequest, cb func(messages.NotifyEVChargingNeedsResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyEVChargingNeeds, req, cb)
}

// NotifyEVChargingSchedule sends a NotifyEVChargingSchedule request from the charge point to the CSMS.
func (c CP) NotifyEVChargingSchedule(ctx context.Context, req messages.NotifyEVChargingScheduleRequest) (messages.NotifyEVChargingScheduleResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyEVChargingSchedule, req)
}

// NotifyEVChargingScheduleAsync sends a NotifyEVChargingSchedule request without blocking, delivering the response to cb.
func (c CP) NotifyEVChargingScheduleAsync(ctx context.Context, req messages.NotifyEVChargingScheduleRequest, cb func(messages.NotifyEVChargingScheduleResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyEVChargingSchedule, req, cb)
}

// NotifyChargingLimit sends a NotifyChargingLimit request from the charge point to the CSMS.
func (c CP) NotifyChargingLimit(ctx context.Context, req messages.NotifyChargingLimitRequest) (messages.NotifyChargingLimitResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyChargingLimit, req)
}

// NotifyChargingLimitAsync sends a NotifyChargingLimit request without blocking, delivering the response to cb.
func (c CP) NotifyChargingLimitAsync(ctx context.Context, req messages.NotifyChargingLimitRequest, cb func(messages.NotifyChargingLimitResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyChargingLimit, req, cb)
}

// ClearedChargingLimit sends a ClearedChargingLimit request from the charge point to the CSMS.
func (c CP) ClearedChargingLimit(ctx context.Context, req messages.ClearedChargingLimitRequest) (messages.ClearedChargingLimitResponse, error) {
	return cp.Call(ctx, c.Client, profiles.ClearedChargingLimit, req)
}

// ClearedChargingLimitAsync sends a ClearedChargingLimit request without blocking, delivering the response to cb.
func (c CP) ClearedChargingLimitAsync(ctx context.Context, req messages.ClearedChargingLimitRequest, cb func(messages.ClearedChargingLimitResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.ClearedChargingLimit, req, cb)
}

// ReportChargingProfiles sends a ReportChargingProfiles request from the charge point to the CSMS.
func (c CP) ReportChargingProfiles(ctx context.Context, req messages.ReportChargingProfilesRequest) (messages.ReportChargingProfilesResponse, error) {
	return cp.Call(ctx, c.Client, profiles.ReportChargingProfiles, req)
}

// ReportChargingProfilesAsync sends a ReportChargingProfiles request without blocking, delivering the response to cb.
func (c CP) ReportChargingProfilesAsync(ctx context.Context, req messages.ReportChargingProfilesRequest, cb func(messages.ReportChargingProfilesResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.ReportChargingProfiles, req, cb)
}

// NotifyPriorityCharging sends a NotifyPriorityCharging request from the charge point to the CSMS.
func (c CP) NotifyPriorityCharging(ctx context.Context, req messages.NotifyPriorityChargingRequest) (messages.NotifyPriorityChargingResponse, error) {
	return cp.Call(ctx, c.Client, profiles.NotifyPriorityCharging, req)
}

// NotifyPriorityChargingAsync sends a NotifyPriorityCharging request without blocking, delivering the response to cb.
func (c CP) NotifyPriorityChargingAsync(ctx context.Context, req messages.NotifyPriorityChargingRequest, cb func(messages.NotifyPriorityChargingResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.NotifyPriorityCharging, req, cb)
}

// PullDynamicScheduleUpdate sends a PullDynamicScheduleUpdate request from the charge point to the CSMS.
func (c CP) PullDynamicScheduleUpdate(ctx context.Context, req messages.PullDynamicScheduleUpdateRequest) (messages.PullDynamicScheduleUpdateResponse, error) {
	return cp.Call(ctx, c.Client, profiles.PullDynamicScheduleUpdate, req)
}

// PullDynamicScheduleUpdateAsync sends a PullDynamicScheduleUpdate request without blocking, delivering the response to cb.
func (c CP) PullDynamicScheduleUpdateAsync(ctx context.Context, req messages.PullDynamicScheduleUpdateRequest, cb func(messages.PullDynamicScheduleUpdateResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.PullDynamicScheduleUpdate, req, cb)
}

// TransactionEvent sends a TransactionEvent request from the charge point to the CSMS.
func (c CP) TransactionEvent(ctx context.Context, req messages.TransactionEventRequest) (messages.TransactionEventResponse, error) {
	return cp.Call(ctx, c.Client, profiles.TransactionEvent, req)
}

// TransactionEventAsync sends a TransactionEvent request without blocking, delivering the response to cb.
func (c CP) TransactionEventAsync(ctx context.Context, req messages.TransactionEventRequest, cb func(messages.TransactionEventResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.TransactionEvent, req, cb)
}

// CSMS wraps *csms.Conn with typed send methods for messages a CSMS sends to
// a connected charge point.
type CSMS struct{ *csms.Conn }

// NewCSMS wraps c so its CSMS->CP messages can be sent as methods.
func NewCSMS(c *csms.Conn) CSMS { return CSMS{c} }

// ClearCache sends a ClearCache request from the CSMS to the charge point.
func (c CSMS) ClearCache(ctx context.Context, req messages.ClearCacheRequest) (messages.ClearCacheResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearCache, req)
}

// ClearCacheAsync sends a ClearCache request without blocking, delivering the response to cb.
func (c CSMS) ClearCacheAsync(ctx context.Context, req messages.ClearCacheRequest, cb func(messages.ClearCacheResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearCache, req, cb)
}

// NotifyWebPaymentStarted sends a NotifyWebPaymentStarted request from the CSMS to the charge point.
func (c CSMS) NotifyWebPaymentStarted(ctx context.Context, req messages.NotifyWebPaymentStartedRequest) (messages.NotifyWebPaymentStartedResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.NotifyWebPaymentStarted, req)
}

// NotifyWebPaymentStartedAsync sends a NotifyWebPaymentStarted request without blocking, delivering the response to cb.
func (c CSMS) NotifyWebPaymentStartedAsync(ctx context.Context, req messages.NotifyWebPaymentStartedRequest, cb func(messages.NotifyWebPaymentStartedResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.NotifyWebPaymentStarted, req, cb)
}

// ChangeAvailability sends a ChangeAvailability request from the CSMS to the charge point.
func (c CSMS) ChangeAvailability(ctx context.Context, req messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ChangeAvailability, req)
}

// ChangeAvailabilityAsync sends a ChangeAvailability request without blocking, delivering the response to cb.
func (c CSMS) ChangeAvailabilityAsync(ctx context.Context, req messages.ChangeAvailabilityRequest, cb func(messages.ChangeAvailabilityResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ChangeAvailability, req, cb)
}

// BatterySwap sends a BatterySwap request from the CSMS to the charge point.
func (c CSMS) BatterySwap(ctx context.Context, req messages.BatterySwapRequest) (messages.BatterySwapResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.BatterySwap, req)
}

// BatterySwapAsync sends a BatterySwap request without blocking, delivering the response to cb.
func (c CSMS) BatterySwapAsync(ctx context.Context, req messages.BatterySwapRequest, cb func(messages.BatterySwapResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.BatterySwap, req, cb)
}

// SetDERControl sends a SetDERControl request from the CSMS to the charge point.
func (c CSMS) SetDERControl(ctx context.Context, req messages.SetDERControlRequest) (messages.SetDERControlResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetDERControl, req)
}

// SetDERControlAsync sends a SetDERControl request without blocking, delivering the response to cb.
func (c CSMS) SetDERControlAsync(ctx context.Context, req messages.SetDERControlRequest, cb func(messages.SetDERControlResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetDERControl, req, cb)
}

// GetDERControl sends a GetDERControl request from the CSMS to the charge point.
func (c CSMS) GetDERControl(ctx context.Context, req messages.GetDERControlRequest) (messages.GetDERControlResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetDERControl, req)
}

// GetDERControlAsync sends a GetDERControl request without blocking, delivering the response to cb.
func (c CSMS) GetDERControlAsync(ctx context.Context, req messages.GetDERControlRequest, cb func(messages.GetDERControlResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetDERControl, req, cb)
}

// ClearDERControl sends a ClearDERControl request from the CSMS to the charge point.
func (c CSMS) ClearDERControl(ctx context.Context, req messages.ClearDERControlRequest) (messages.ClearDERControlResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearDERControl, req)
}

// ClearDERControlAsync sends a ClearDERControl request without blocking, delivering the response to cb.
func (c CSMS) ClearDERControlAsync(ctx context.Context, req messages.ClearDERControlRequest, cb func(messages.ClearDERControlResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearDERControl, req, cb)
}

// DataTransfer sends a DataTransfer request from the CSMS to the charge point.
func (c CSMS) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.DataTransfer, req)
}

// DataTransferAsync sends a DataTransfer request without blocking, delivering the response to cb.
func (c CSMS) DataTransferAsync(ctx context.Context, req messages.DataTransferRequest, cb func(messages.DataTransferResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.DataTransfer, req, cb)
}

// GetMonitoringReport sends a GetMonitoringReport request from the CSMS to the charge point.
func (c CSMS) GetMonitoringReport(ctx context.Context, req messages.GetMonitoringReportRequest) (messages.GetMonitoringReportResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetMonitoringReport, req)
}

// GetMonitoringReportAsync sends a GetMonitoringReport request without blocking, delivering the response to cb.
func (c CSMS) GetMonitoringReportAsync(ctx context.Context, req messages.GetMonitoringReportRequest, cb func(messages.GetMonitoringReportResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetMonitoringReport, req, cb)
}

// SetMonitoringBase sends a SetMonitoringBase request from the CSMS to the charge point.
func (c CSMS) SetMonitoringBase(ctx context.Context, req messages.SetMonitoringBaseRequest) (messages.SetMonitoringBaseResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetMonitoringBase, req)
}

// SetMonitoringBaseAsync sends a SetMonitoringBase request without blocking, delivering the response to cb.
func (c CSMS) SetMonitoringBaseAsync(ctx context.Context, req messages.SetMonitoringBaseRequest, cb func(messages.SetMonitoringBaseResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetMonitoringBase, req, cb)
}

// SetVariableMonitoring sends a SetVariableMonitoring request from the CSMS to the charge point.
func (c CSMS) SetVariableMonitoring(ctx context.Context, req messages.SetVariableMonitoringRequest) (messages.SetVariableMonitoringResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetVariableMonitoring, req)
}

// SetVariableMonitoringAsync sends a SetVariableMonitoring request without blocking, delivering the response to cb.
func (c CSMS) SetVariableMonitoringAsync(ctx context.Context, req messages.SetVariableMonitoringRequest, cb func(messages.SetVariableMonitoringResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetVariableMonitoring, req, cb)
}

// ClearVariableMonitoring sends a ClearVariableMonitoring request from the CSMS to the charge point.
func (c CSMS) ClearVariableMonitoring(ctx context.Context, req messages.ClearVariableMonitoringRequest) (messages.ClearVariableMonitoringResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearVariableMonitoring, req)
}

// ClearVariableMonitoringAsync sends a ClearVariableMonitoring request without blocking, delivering the response to cb.
func (c CSMS) ClearVariableMonitoringAsync(ctx context.Context, req messages.ClearVariableMonitoringRequest, cb func(messages.ClearVariableMonitoringResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearVariableMonitoring, req, cb)
}

// SetMonitoringLevel sends a SetMonitoringLevel request from the CSMS to the charge point.
func (c CSMS) SetMonitoringLevel(ctx context.Context, req messages.SetMonitoringLevelRequest) (messages.SetMonitoringLevelResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetMonitoringLevel, req)
}

// SetMonitoringLevelAsync sends a SetMonitoringLevel request without blocking, delivering the response to cb.
func (c CSMS) SetMonitoringLevelAsync(ctx context.Context, req messages.SetMonitoringLevelRequest, cb func(messages.SetMonitoringLevelResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetMonitoringLevel, req, cb)
}

// GetLog sends a GetLog request from the CSMS to the charge point.
func (c CSMS) GetLog(ctx context.Context, req messages.GetLogRequest) (messages.GetLogResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetLog, req)
}

// GetLogAsync sends a GetLog request without blocking, delivering the response to cb.
func (c CSMS) GetLogAsync(ctx context.Context, req messages.GetLogRequest, cb func(messages.GetLogResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetLog, req, cb)
}

// CustomerInformation sends a CustomerInformation request from the CSMS to the charge point.
func (c CSMS) CustomerInformation(ctx context.Context, req messages.CustomerInformationRequest) (messages.CustomerInformationResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CustomerInformation, req)
}

// CustomerInformationAsync sends a CustomerInformation request without blocking, delivering the response to cb.
func (c CSMS) CustomerInformationAsync(ctx context.Context, req messages.CustomerInformationRequest, cb func(messages.CustomerInformationResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CustomerInformation, req, cb)
}

// AdjustPeriodicEventStream sends a AdjustPeriodicEventStream request from the CSMS to the charge point.
func (c CSMS) AdjustPeriodicEventStream(ctx context.Context, req messages.AdjustPeriodicEventStreamRequest) (messages.AdjustPeriodicEventStreamResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.AdjustPeriodicEventStream, req)
}

// AdjustPeriodicEventStreamAsync sends a AdjustPeriodicEventStream request without blocking, delivering the response to cb.
func (c CSMS) AdjustPeriodicEventStreamAsync(ctx context.Context, req messages.AdjustPeriodicEventStreamRequest, cb func(messages.AdjustPeriodicEventStreamResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.AdjustPeriodicEventStream, req, cb)
}

// ClosePeriodicEventStream sends a ClosePeriodicEventStream request from the CSMS to the charge point.
func (c CSMS) ClosePeriodicEventStream(ctx context.Context, req messages.ClosePeriodicEventStreamRequest) (messages.ClosePeriodicEventStreamResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClosePeriodicEventStream, req)
}

// ClosePeriodicEventStreamAsync sends a ClosePeriodicEventStream request without blocking, delivering the response to cb.
func (c CSMS) ClosePeriodicEventStreamAsync(ctx context.Context, req messages.ClosePeriodicEventStreamRequest, cb func(messages.ClosePeriodicEventStreamResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClosePeriodicEventStream, req, cb)
}

// GetPeriodicEventStream sends a GetPeriodicEventStream request from the CSMS to the charge point.
func (c CSMS) GetPeriodicEventStream(ctx context.Context, req messages.GetPeriodicEventStreamRequest) (messages.GetPeriodicEventStreamResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetPeriodicEventStream, req)
}

// GetPeriodicEventStreamAsync sends a GetPeriodicEventStream request without blocking, delivering the response to cb.
func (c CSMS) GetPeriodicEventStreamAsync(ctx context.Context, req messages.GetPeriodicEventStreamRequest, cb func(messages.GetPeriodicEventStreamResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetPeriodicEventStream, req, cb)
}

// OpenPeriodicEventStream sends a OpenPeriodicEventStream request from the CSMS to the charge point.
func (c CSMS) OpenPeriodicEventStream(ctx context.Context, req messages.OpenPeriodicEventStreamRequest) (messages.OpenPeriodicEventStreamResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.OpenPeriodicEventStream, req)
}

// OpenPeriodicEventStreamAsync sends a OpenPeriodicEventStream request without blocking, delivering the response to cb.
func (c CSMS) OpenPeriodicEventStreamAsync(ctx context.Context, req messages.OpenPeriodicEventStreamRequest, cb func(messages.OpenPeriodicEventStreamResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.OpenPeriodicEventStream, req, cb)
}

// SetDisplayMessage sends a SetDisplayMessage request from the CSMS to the charge point.
func (c CSMS) SetDisplayMessage(ctx context.Context, req messages.SetDisplayMessageRequest) (messages.SetDisplayMessageResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetDisplayMessage, req)
}

// SetDisplayMessageAsync sends a SetDisplayMessage request without blocking, delivering the response to cb.
func (c CSMS) SetDisplayMessageAsync(ctx context.Context, req messages.SetDisplayMessageRequest, cb func(messages.SetDisplayMessageResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetDisplayMessage, req, cb)
}

// GetDisplayMessages sends a GetDisplayMessages request from the CSMS to the charge point.
func (c CSMS) GetDisplayMessages(ctx context.Context, req messages.GetDisplayMessagesRequest) (messages.GetDisplayMessagesResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetDisplayMessages, req)
}

// GetDisplayMessagesAsync sends a GetDisplayMessages request without blocking, delivering the response to cb.
func (c CSMS) GetDisplayMessagesAsync(ctx context.Context, req messages.GetDisplayMessagesRequest, cb func(messages.GetDisplayMessagesResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetDisplayMessages, req, cb)
}

// ClearDisplayMessage sends a ClearDisplayMessage request from the CSMS to the charge point.
func (c CSMS) ClearDisplayMessage(ctx context.Context, req messages.ClearDisplayMessageRequest) (messages.ClearDisplayMessageResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearDisplayMessage, req)
}

// ClearDisplayMessageAsync sends a ClearDisplayMessage request without blocking, delivering the response to cb.
func (c CSMS) ClearDisplayMessageAsync(ctx context.Context, req messages.ClearDisplayMessageRequest, cb func(messages.ClearDisplayMessageResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearDisplayMessage, req, cb)
}

// UpdateFirmware sends a UpdateFirmware request from the CSMS to the charge point.
func (c CSMS) UpdateFirmware(ctx context.Context, req messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UpdateFirmware, req)
}

// UpdateFirmwareAsync sends a UpdateFirmware request without blocking, delivering the response to cb.
func (c CSMS) UpdateFirmwareAsync(ctx context.Context, req messages.UpdateFirmwareRequest, cb func(messages.UpdateFirmwareResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UpdateFirmware, req, cb)
}

// PublishFirmware sends a PublishFirmware request from the CSMS to the charge point.
func (c CSMS) PublishFirmware(ctx context.Context, req messages.PublishFirmwareRequest) (messages.PublishFirmwareResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.PublishFirmware, req)
}

// PublishFirmwareAsync sends a PublishFirmware request without blocking, delivering the response to cb.
func (c CSMS) PublishFirmwareAsync(ctx context.Context, req messages.PublishFirmwareRequest, cb func(messages.PublishFirmwareResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.PublishFirmware, req, cb)
}

// UnpublishFirmware sends a UnpublishFirmware request from the CSMS to the charge point.
func (c CSMS) UnpublishFirmware(ctx context.Context, req messages.UnpublishFirmwareRequest) (messages.UnpublishFirmwareResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UnpublishFirmware, req)
}

// UnpublishFirmwareAsync sends a UnpublishFirmware request without blocking, delivering the response to cb.
func (c CSMS) UnpublishFirmwareAsync(ctx context.Context, req messages.UnpublishFirmwareRequest, cb func(messages.UnpublishFirmwareResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UnpublishFirmware, req, cb)
}

// GetInstalledCertificateIds sends a GetInstalledCertificateIds request from the CSMS to the charge point.
func (c CSMS) GetInstalledCertificateIds(ctx context.Context, req messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetInstalledCertificateIds, req)
}

// GetInstalledCertificateIdsAsync sends a GetInstalledCertificateIds request without blocking, delivering the response to cb.
func (c CSMS) GetInstalledCertificateIdsAsync(ctx context.Context, req messages.GetInstalledCertificateIdsRequest, cb func(messages.GetInstalledCertificateIdsResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetInstalledCertificateIds, req, cb)
}

// InstallCertificate sends a InstallCertificate request from the CSMS to the charge point.
func (c CSMS) InstallCertificate(ctx context.Context, req messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.InstallCertificate, req)
}

// InstallCertificateAsync sends a InstallCertificate request without blocking, delivering the response to cb.
func (c CSMS) InstallCertificateAsync(ctx context.Context, req messages.InstallCertificateRequest, cb func(messages.InstallCertificateResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.InstallCertificate, req, cb)
}

// DeleteCertificate sends a DeleteCertificate request from the CSMS to the charge point.
func (c CSMS) DeleteCertificate(ctx context.Context, req messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.DeleteCertificate, req)
}

// DeleteCertificateAsync sends a DeleteCertificate request without blocking, delivering the response to cb.
func (c CSMS) DeleteCertificateAsync(ctx context.Context, req messages.DeleteCertificateRequest, cb func(messages.DeleteCertificateResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.DeleteCertificate, req, cb)
}

// CertificateSigned sends a CertificateSigned request from the CSMS to the charge point.
func (c CSMS) CertificateSigned(ctx context.Context, req messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CertificateSigned, req)
}

// CertificateSignedAsync sends a CertificateSigned request without blocking, delivering the response to cb.
func (c CSMS) CertificateSignedAsync(ctx context.Context, req messages.CertificateSignedRequest, cb func(messages.CertificateSignedResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CertificateSigned, req, cb)
}

// GetLocalListVersion sends a GetLocalListVersion request from the CSMS to the charge point.
func (c CSMS) GetLocalListVersion(ctx context.Context, req messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetLocalListVersion, req)
}

// GetLocalListVersionAsync sends a GetLocalListVersion request without blocking, delivering the response to cb.
func (c CSMS) GetLocalListVersionAsync(ctx context.Context, req messages.GetLocalListVersionRequest, cb func(messages.GetLocalListVersionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetLocalListVersion, req, cb)
}

// SendLocalList sends a SendLocalList request from the CSMS to the charge point.
func (c CSMS) SendLocalList(ctx context.Context, req messages.SendLocalListRequest) (messages.SendLocalListResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SendLocalList, req)
}

// SendLocalListAsync sends a SendLocalList request without blocking, delivering the response to cb.
func (c CSMS) SendLocalListAsync(ctx context.Context, req messages.SendLocalListRequest, cb func(messages.SendLocalListResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SendLocalList, req, cb)
}

// GetBaseReport sends a GetBaseReport request from the CSMS to the charge point.
func (c CSMS) GetBaseReport(ctx context.Context, req messages.GetBaseReportRequest) (messages.GetBaseReportResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetBaseReport, req)
}

// GetBaseReportAsync sends a GetBaseReport request without blocking, delivering the response to cb.
func (c CSMS) GetBaseReportAsync(ctx context.Context, req messages.GetBaseReportRequest, cb func(messages.GetBaseReportResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetBaseReport, req, cb)
}

// GetReport sends a GetReport request from the CSMS to the charge point.
func (c CSMS) GetReport(ctx context.Context, req messages.GetReportRequest) (messages.GetReportResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetReport, req)
}

// GetReportAsync sends a GetReport request without blocking, delivering the response to cb.
func (c CSMS) GetReportAsync(ctx context.Context, req messages.GetReportRequest, cb func(messages.GetReportResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetReport, req, cb)
}

// GetVariables sends a GetVariables request from the CSMS to the charge point.
func (c CSMS) GetVariables(ctx context.Context, req messages.GetVariablesRequest) (messages.GetVariablesResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetVariables, req)
}

// GetVariablesAsync sends a GetVariables request without blocking, delivering the response to cb.
func (c CSMS) GetVariablesAsync(ctx context.Context, req messages.GetVariablesRequest, cb func(messages.GetVariablesResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetVariables, req, cb)
}

// SetVariables sends a SetVariables request from the CSMS to the charge point.
func (c CSMS) SetVariables(ctx context.Context, req messages.SetVariablesRequest) (messages.SetVariablesResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetVariables, req)
}

// SetVariablesAsync sends a SetVariables request without blocking, delivering the response to cb.
func (c CSMS) SetVariablesAsync(ctx context.Context, req messages.SetVariablesRequest, cb func(messages.SetVariablesResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetVariables, req, cb)
}

// Reset sends a Reset request from the CSMS to the charge point.
func (c CSMS) Reset(ctx context.Context, req messages.ResetRequest) (messages.ResetResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.Reset, req)
}

// ResetAsync sends a Reset request without blocking, delivering the response to cb.
func (c CSMS) ResetAsync(ctx context.Context, req messages.ResetRequest, cb func(messages.ResetResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.Reset, req, cb)
}

// SetNetworkProfile sends a SetNetworkProfile request from the CSMS to the charge point.
func (c CSMS) SetNetworkProfile(ctx context.Context, req messages.SetNetworkProfileRequest) (messages.SetNetworkProfileResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetNetworkProfile, req)
}

// SetNetworkProfileAsync sends a SetNetworkProfile request without blocking, delivering the response to cb.
func (c CSMS) SetNetworkProfileAsync(ctx context.Context, req messages.SetNetworkProfileRequest, cb func(messages.SetNetworkProfileResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetNetworkProfile, req, cb)
}

// RequestStartTransaction sends a RequestStartTransaction request from the CSMS to the charge point.
func (c CSMS) RequestStartTransaction(ctx context.Context, req messages.RequestStartTransactionRequest) (messages.RequestStartTransactionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.RequestStartTransaction, req)
}

// RequestStartTransactionAsync sends a RequestStartTransaction request without blocking, delivering the response to cb.
func (c CSMS) RequestStartTransactionAsync(ctx context.Context, req messages.RequestStartTransactionRequest, cb func(messages.RequestStartTransactionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.RequestStartTransaction, req, cb)
}

// RequestStopTransaction sends a RequestStopTransaction request from the CSMS to the charge point.
func (c CSMS) RequestStopTransaction(ctx context.Context, req messages.RequestStopTransactionRequest) (messages.RequestStopTransactionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.RequestStopTransaction, req)
}

// RequestStopTransactionAsync sends a RequestStopTransaction request without blocking, delivering the response to cb.
func (c CSMS) RequestStopTransactionAsync(ctx context.Context, req messages.RequestStopTransactionRequest, cb func(messages.RequestStopTransactionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.RequestStopTransaction, req, cb)
}

// UnlockConnector sends a UnlockConnector request from the CSMS to the charge point.
func (c CSMS) UnlockConnector(ctx context.Context, req messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UnlockConnector, req)
}

// UnlockConnectorAsync sends a UnlockConnector request without blocking, delivering the response to cb.
func (c CSMS) UnlockConnectorAsync(ctx context.Context, req messages.UnlockConnectorRequest, cb func(messages.UnlockConnectorResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UnlockConnector, req, cb)
}

// TriggerMessage sends a TriggerMessage request from the CSMS to the charge point.
func (c CSMS) TriggerMessage(ctx context.Context, req messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.TriggerMessage, req)
}

// TriggerMessageAsync sends a TriggerMessage request without blocking, delivering the response to cb.
func (c CSMS) TriggerMessageAsync(ctx context.Context, req messages.TriggerMessageRequest, cb func(messages.TriggerMessageResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.TriggerMessage, req, cb)
}

// ReserveNow sends a ReserveNow request from the CSMS to the charge point.
func (c CSMS) ReserveNow(ctx context.Context, req messages.ReserveNowRequest) (messages.ReserveNowResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ReserveNow, req)
}

// ReserveNowAsync sends a ReserveNow request without blocking, delivering the response to cb.
func (c CSMS) ReserveNowAsync(ctx context.Context, req messages.ReserveNowRequest, cb func(messages.ReserveNowResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ReserveNow, req, cb)
}

// CancelReservation sends a CancelReservation request from the CSMS to the charge point.
func (c CSMS) CancelReservation(ctx context.Context, req messages.CancelReservationRequest) (messages.CancelReservationResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CancelReservation, req)
}

// CancelReservationAsync sends a CancelReservation request without blocking, delivering the response to cb.
func (c CSMS) CancelReservationAsync(ctx context.Context, req messages.CancelReservationRequest, cb func(messages.CancelReservationResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CancelReservation, req, cb)
}

// SetChargingProfile sends a SetChargingProfile request from the CSMS to the charge point.
func (c CSMS) SetChargingProfile(ctx context.Context, req messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetChargingProfile, req)
}

// SetChargingProfileAsync sends a SetChargingProfile request without blocking, delivering the response to cb.
func (c CSMS) SetChargingProfileAsync(ctx context.Context, req messages.SetChargingProfileRequest, cb func(messages.SetChargingProfileResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetChargingProfile, req, cb)
}

// GetChargingProfiles sends a GetChargingProfiles request from the CSMS to the charge point.
func (c CSMS) GetChargingProfiles(ctx context.Context, req messages.GetChargingProfilesRequest) (messages.GetChargingProfilesResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetChargingProfiles, req)
}

// GetChargingProfilesAsync sends a GetChargingProfiles request without blocking, delivering the response to cb.
func (c CSMS) GetChargingProfilesAsync(ctx context.Context, req messages.GetChargingProfilesRequest, cb func(messages.GetChargingProfilesResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetChargingProfiles, req, cb)
}

// ClearChargingProfile sends a ClearChargingProfile request from the CSMS to the charge point.
func (c CSMS) ClearChargingProfile(ctx context.Context, req messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearChargingProfile, req)
}

// ClearChargingProfileAsync sends a ClearChargingProfile request without blocking, delivering the response to cb.
func (c CSMS) ClearChargingProfileAsync(ctx context.Context, req messages.ClearChargingProfileRequest, cb func(messages.ClearChargingProfileResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearChargingProfile, req, cb)
}

// GetCompositeSchedule sends a GetCompositeSchedule request from the CSMS to the charge point.
func (c CSMS) GetCompositeSchedule(ctx context.Context, req messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetCompositeSchedule, req)
}

// GetCompositeScheduleAsync sends a GetCompositeSchedule request without blocking, delivering the response to cb.
func (c CSMS) GetCompositeScheduleAsync(ctx context.Context, req messages.GetCompositeScheduleRequest, cb func(messages.GetCompositeScheduleResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetCompositeSchedule, req, cb)
}

// NotifyAllowedEnergyTransfer sends a NotifyAllowedEnergyTransfer request from the CSMS to the charge point.
func (c CSMS) NotifyAllowedEnergyTransfer(ctx context.Context, req messages.NotifyAllowedEnergyTransferRequest) (messages.NotifyAllowedEnergyTransferResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.NotifyAllowedEnergyTransfer, req)
}

// NotifyAllowedEnergyTransferAsync sends a NotifyAllowedEnergyTransfer request without blocking, delivering the response to cb.
func (c CSMS) NotifyAllowedEnergyTransferAsync(ctx context.Context, req messages.NotifyAllowedEnergyTransferRequest, cb func(messages.NotifyAllowedEnergyTransferResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.NotifyAllowedEnergyTransfer, req, cb)
}

// UsePriorityCharging sends a UsePriorityCharging request from the CSMS to the charge point.
func (c CSMS) UsePriorityCharging(ctx context.Context, req messages.UsePriorityChargingRequest) (messages.UsePriorityChargingResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UsePriorityCharging, req)
}

// UsePriorityChargingAsync sends a UsePriorityCharging request without blocking, delivering the response to cb.
func (c CSMS) UsePriorityChargingAsync(ctx context.Context, req messages.UsePriorityChargingRequest, cb func(messages.UsePriorityChargingResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UsePriorityCharging, req, cb)
}

// AFRRSignal sends a AFRRSignal request from the CSMS to the charge point.
func (c CSMS) AFRRSignal(ctx context.Context, req messages.AFRRSignalRequest) (messages.AFRRSignalResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.AFRRSignal, req)
}

// AFRRSignalAsync sends a AFRRSignal request without blocking, delivering the response to cb.
func (c CSMS) AFRRSignalAsync(ctx context.Context, req messages.AFRRSignalRequest, cb func(messages.AFRRSignalResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.AFRRSignal, req, cb)
}

// UpdateDynamicSchedule sends a UpdateDynamicSchedule request from the CSMS to the charge point.
func (c CSMS) UpdateDynamicSchedule(ctx context.Context, req messages.UpdateDynamicScheduleRequest) (messages.UpdateDynamicScheduleResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UpdateDynamicSchedule, req)
}

// UpdateDynamicScheduleAsync sends a UpdateDynamicSchedule request without blocking, delivering the response to cb.
func (c CSMS) UpdateDynamicScheduleAsync(ctx context.Context, req messages.UpdateDynamicScheduleRequest, cb func(messages.UpdateDynamicScheduleResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UpdateDynamicSchedule, req, cb)
}

// CostUpdated sends a CostUpdated request from the CSMS to the charge point.
func (c CSMS) CostUpdated(ctx context.Context, req messages.CostUpdatedRequest) (messages.CostUpdatedResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CostUpdated, req)
}

// CostUpdatedAsync sends a CostUpdated request without blocking, delivering the response to cb.
func (c CSMS) CostUpdatedAsync(ctx context.Context, req messages.CostUpdatedRequest, cb func(messages.CostUpdatedResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CostUpdated, req, cb)
}

// ChangeTransactionTariff sends a ChangeTransactionTariff request from the CSMS to the charge point.
func (c CSMS) ChangeTransactionTariff(ctx context.Context, req messages.ChangeTransactionTariffRequest) (messages.ChangeTransactionTariffResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ChangeTransactionTariff, req)
}

// ChangeTransactionTariffAsync sends a ChangeTransactionTariff request without blocking, delivering the response to cb.
func (c CSMS) ChangeTransactionTariffAsync(ctx context.Context, req messages.ChangeTransactionTariffRequest, cb func(messages.ChangeTransactionTariffResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ChangeTransactionTariff, req, cb)
}

// ClearTariffs sends a ClearTariffs request from the CSMS to the charge point.
func (c CSMS) ClearTariffs(ctx context.Context, req messages.ClearTariffsRequest) (messages.ClearTariffsResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearTariffs, req)
}

// ClearTariffsAsync sends a ClearTariffs request without blocking, delivering the response to cb.
func (c CSMS) ClearTariffsAsync(ctx context.Context, req messages.ClearTariffsRequest, cb func(messages.ClearTariffsResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearTariffs, req, cb)
}

// GetTariffs sends a GetTariffs request from the CSMS to the charge point.
func (c CSMS) GetTariffs(ctx context.Context, req messages.GetTariffsRequest) (messages.GetTariffsResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetTariffs, req)
}

// GetTariffsAsync sends a GetTariffs request without blocking, delivering the response to cb.
func (c CSMS) GetTariffsAsync(ctx context.Context, req messages.GetTariffsRequest, cb func(messages.GetTariffsResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetTariffs, req, cb)
}

// SetDefaultTariff sends a SetDefaultTariff request from the CSMS to the charge point.
func (c CSMS) SetDefaultTariff(ctx context.Context, req messages.SetDefaultTariffRequest) (messages.SetDefaultTariffResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetDefaultTariff, req)
}

// SetDefaultTariffAsync sends a SetDefaultTariff request without blocking, delivering the response to cb.
func (c CSMS) SetDefaultTariffAsync(ctx context.Context, req messages.SetDefaultTariffRequest, cb func(messages.SetDefaultTariffResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetDefaultTariff, req, cb)
}

// GetTransactionStatus sends a GetTransactionStatus request from the CSMS to the charge point.
func (c CSMS) GetTransactionStatus(ctx context.Context, req messages.GetTransactionStatusRequest) (messages.GetTransactionStatusResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetTransactionStatus, req)
}

// GetTransactionStatusAsync sends a GetTransactionStatus request without blocking, delivering the response to cb.
func (c CSMS) GetTransactionStatusAsync(ctx context.Context, req messages.GetTransactionStatusRequest, cb func(messages.GetTransactionStatusResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetTransactionStatus, req, cb)
}
