// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// Authorize is the OCPP Authorize message (SentByCP).
var Authorize = ocppj.Message[
	messages.AuthorizeRequest,
	messages.AuthorizeResponse,
]{Action: "Authorize", Direction: ocppj.SentByCP}

// ClearCache is the OCPP ClearCache message (SentByCSMS).
var ClearCache = ocppj.Message[
	messages.ClearCacheRequest,
	messages.ClearCacheResponse,
]{Action: "ClearCache", Direction: ocppj.SentByCSMS}

// NotifyWebPaymentStarted is the OCPP NotifyWebPaymentStarted message (SentByCSMS).
var NotifyWebPaymentStarted = ocppj.Message[
	messages.NotifyWebPaymentStartedRequest,
	messages.NotifyWebPaymentStartedResponse,
]{Action: "NotifyWebPaymentStarted", Direction: ocppj.SentByCSMS}

// NotifySettlement is the OCPP NotifySettlement message (SentByCP).
var NotifySettlement = ocppj.Message[
	messages.NotifySettlementRequest,
	messages.NotifySettlementResponse,
]{Action: "NotifySettlement", Direction: ocppj.SentByCP}

// VatNumberValidation is the OCPP VatNumberValidation message (SentByCP).
var VatNumberValidation = ocppj.Message[
	messages.VatNumberValidationRequest,
	messages.VatNumberValidationResponse,
]{Action: "VatNumberValidation", Direction: ocppj.SentByCP}
