// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// StatusNotification is the OCPP StatusNotification message (SentByCP).
var StatusNotification = ocppj.Message[
	messages.StatusNotificationRequest,
	messages.StatusNotificationResponse,
]{Action: "StatusNotification", Direction: ocppj.SentByCP}

// ChangeAvailability is the OCPP ChangeAvailability message (SentByCSMS).
var ChangeAvailability = ocppj.Message[
	messages.ChangeAvailabilityRequest,
	messages.ChangeAvailabilityResponse,
]{Action: "ChangeAvailability", Direction: ocppj.SentByCSMS}
