// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// BatterySwap is the OCPP BatterySwap message (SentByCSMS).
var BatterySwap = ocppj.Message[
	messages.BatterySwapRequest,
	messages.BatterySwapResponse,
]{Action: "BatterySwap", Direction: ocppj.SentByCSMS}

// RequestBatterySwap is the OCPP RequestBatterySwap message (SentByCP).
var RequestBatterySwap = ocppj.Message[
	messages.RequestBatterySwapRequest,
	messages.RequestBatterySwapResponse,
]{Action: "RequestBatterySwap", Direction: ocppj.SentByCP}
