// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// SetDERControl is the OCPP SetDERControl message (SentByCSMS).
var SetDERControl = ocppj.Message[
	messages.SetDERControlRequest,
	messages.SetDERControlResponse,
]{Action: "SetDERControl", Direction: ocppj.SentByCSMS}

// GetDERControl is the OCPP GetDERControl message (SentByCSMS).
var GetDERControl = ocppj.Message[
	messages.GetDERControlRequest,
	messages.GetDERControlResponse,
]{Action: "GetDERControl", Direction: ocppj.SentByCSMS}

// ClearDERControl is the OCPP ClearDERControl message (SentByCSMS).
var ClearDERControl = ocppj.Message[
	messages.ClearDERControlRequest,
	messages.ClearDERControlResponse,
]{Action: "ClearDERControl", Direction: ocppj.SentByCSMS}

// NotifyDERAlarm is the OCPP NotifyDERAlarm message (SentByCP).
var NotifyDERAlarm = ocppj.Message[
	messages.NotifyDERAlarmRequest,
	messages.NotifyDERAlarmResponse,
]{Action: "NotifyDERAlarm", Direction: ocppj.SentByCP}

// NotifyDERStartStop is the OCPP NotifyDERStartStop message (SentByCP).
var NotifyDERStartStop = ocppj.Message[
	messages.NotifyDERStartStopRequest,
	messages.NotifyDERStartStopResponse,
]{Action: "NotifyDERStartStop", Direction: ocppj.SentByCP}

// ReportDERControl is the OCPP ReportDERControl message (SentByCP).
var ReportDERControl = ocppj.Message[
	messages.ReportDERControlRequest,
	messages.ReportDERControlResponse,
]{Action: "ReportDERControl", Direction: ocppj.SentByCP}
