// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// DataTransfer is the OCPP DataTransfer message (SentByCP).
var DataTransfer = ocppj.Message[
	messages.DataTransferRequest,
	messages.DataTransferResponse,
]{Action: "DataTransfer", Direction: ocppj.SentByCP}
