// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// UpdateFirmware is the OCPP UpdateFirmware message (SentByCSMS).
var UpdateFirmware = ocppj.Message[
	messages.UpdateFirmwareRequest,
	messages.UpdateFirmwareResponse,
]{Action: "UpdateFirmware", Direction: ocppj.SentByCSMS}

// FirmwareStatusNotification is the OCPP FirmwareStatusNotification message (SentByCP).
var FirmwareStatusNotification = ocppj.Message[
	messages.FirmwareStatusNotificationRequest,
	messages.FirmwareStatusNotificationResponse,
]{Action: "FirmwareStatusNotification", Direction: ocppj.SentByCP}

// PublishFirmware is the OCPP PublishFirmware message (SentByCSMS).
var PublishFirmware = ocppj.Message[
	messages.PublishFirmwareRequest,
	messages.PublishFirmwareResponse,
]{Action: "PublishFirmware", Direction: ocppj.SentByCSMS}

// PublishFirmwareStatusNotification is the OCPP PublishFirmwareStatusNotification message (SentByCP).
var PublishFirmwareStatusNotification = ocppj.Message[
	messages.PublishFirmwareStatusNotificationRequest,
	messages.PublishFirmwareStatusNotificationResponse,
]{Action: "PublishFirmwareStatusNotification", Direction: ocppj.SentByCP}

// UnpublishFirmware is the OCPP UnpublishFirmware message (SentByCSMS).
var UnpublishFirmware = ocppj.Message[
	messages.UnpublishFirmwareRequest,
	messages.UnpublishFirmwareResponse,
]{Action: "UnpublishFirmware", Direction: ocppj.SentByCSMS}
