// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// SignCertificate is the OCPP SignCertificate message (SentByCP).
var SignCertificate = ocppj.Message[
	messages.SignCertificateRequest,
	messages.SignCertificateResponse,
]{Action: "SignCertificate", Direction: ocppj.SentByCP}

// Get15118EVCertificate is the OCPP Get15118EVCertificate message (SentByCP).
var Get15118EVCertificate = ocppj.Message[
	messages.Get15118EVCertificateRequest,
	messages.Get15118EVCertificateResponse,
]{Action: "Get15118EVCertificate", Direction: ocppj.SentByCP}

// GetCertificateStatus is the OCPP GetCertificateStatus message (SentByCP).
var GetCertificateStatus = ocppj.Message[
	messages.GetCertificateStatusRequest,
	messages.GetCertificateStatusResponse,
]{Action: "GetCertificateStatus", Direction: ocppj.SentByCP}

// GetCertificateChainStatus is the OCPP GetCertificateChainStatus message (SentByCP).
var GetCertificateChainStatus = ocppj.Message[
	messages.GetCertificateChainStatusRequest,
	messages.GetCertificateChainStatusResponse,
]{Action: "GetCertificateChainStatus", Direction: ocppj.SentByCP}

// GetInstalledCertificateIds is the OCPP GetInstalledCertificateIds message (SentByCSMS).
var GetInstalledCertificateIds = ocppj.Message[
	messages.GetInstalledCertificateIdsRequest,
	messages.GetInstalledCertificateIdsResponse,
]{Action: "GetInstalledCertificateIds", Direction: ocppj.SentByCSMS}

// InstallCertificate is the OCPP InstallCertificate message (SentByCSMS).
var InstallCertificate = ocppj.Message[
	messages.InstallCertificateRequest,
	messages.InstallCertificateResponse,
]{Action: "InstallCertificate", Direction: ocppj.SentByCSMS}

// DeleteCertificate is the OCPP DeleteCertificate message (SentByCSMS).
var DeleteCertificate = ocppj.Message[
	messages.DeleteCertificateRequest,
	messages.DeleteCertificateResponse,
]{Action: "DeleteCertificate", Direction: ocppj.SentByCSMS}

// CertificateSigned is the OCPP CertificateSigned message (SentByCSMS).
var CertificateSigned = ocppj.Message[
	messages.CertificateSignedRequest,
	messages.CertificateSignedResponse,
]{Action: "CertificateSigned", Direction: ocppj.SentByCSMS}
