// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// GetLocalListVersion is the OCPP GetLocalListVersion message (SentByCSMS).
var GetLocalListVersion = ocppj.Message[
	messages.GetLocalListVersionRequest,
	messages.GetLocalListVersionResponse,
]{Action: "GetLocalListVersion", Direction: ocppj.SentByCSMS}

// SendLocalList is the OCPP SendLocalList message (SentByCSMS).
var SendLocalList = ocppj.Message[
	messages.SendLocalListRequest,
	messages.SendLocalListResponse,
]{Action: "SendLocalList", Direction: ocppj.SentByCSMS}
