// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// ReserveNow is the OCPP ReserveNow message (SentByCSMS).
var ReserveNow = ocppj.Message[
	messages.ReserveNowRequest,
	messages.ReserveNowResponse,
]{Action: "ReserveNow", Direction: ocppj.SentByCSMS}

// CancelReservation is the OCPP CancelReservation message (SentByCSMS).
var CancelReservation = ocppj.Message[
	messages.CancelReservationRequest,
	messages.CancelReservationResponse,
]{Action: "CancelReservation", Direction: ocppj.SentByCSMS}

// ReservationStatusUpdate is the OCPP ReservationStatusUpdate message (SentByCP).
var ReservationStatusUpdate = ocppj.Message[
	messages.ReservationStatusUpdateRequest,
	messages.ReservationStatusUpdateResponse,
]{Action: "ReservationStatusUpdate", Direction: ocppj.SentByCP}
