// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// SecurityEventNotification is the OCPP SecurityEventNotification message (SentByCP).
var SecurityEventNotification = ocppj.Message[
	messages.SecurityEventNotificationRequest,
	messages.SecurityEventNotificationResponse,
]{Action: "SecurityEventNotification", Direction: ocppj.SentByCP}
