// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// SetChargingProfile is the OCPP SetChargingProfile message (SentByCSMS).
var SetChargingProfile = ocppj.Message[
	messages.SetChargingProfileRequest,
	messages.SetChargingProfileResponse,
]{Action: "SetChargingProfile", Direction: ocppj.SentByCSMS}

// GetChargingProfiles is the OCPP GetChargingProfiles message (SentByCSMS).
var GetChargingProfiles = ocppj.Message[
	messages.GetChargingProfilesRequest,
	messages.GetChargingProfilesResponse,
]{Action: "GetChargingProfiles", Direction: ocppj.SentByCSMS}

// ClearChargingProfile is the OCPP ClearChargingProfile message (SentByCSMS).
var ClearChargingProfile = ocppj.Message[
	messages.ClearChargingProfileRequest,
	messages.ClearChargingProfileResponse,
]{Action: "ClearChargingProfile", Direction: ocppj.SentByCSMS}

// GetCompositeSchedule is the OCPP GetCompositeSchedule message (SentByCSMS).
var GetCompositeSchedule = ocppj.Message[
	messages.GetCompositeScheduleRequest,
	messages.GetCompositeScheduleResponse,
]{Action: "GetCompositeSchedule", Direction: ocppj.SentByCSMS}

// NotifyEVChargingNeeds is the OCPP NotifyEVChargingNeeds message (SentByCP).
var NotifyEVChargingNeeds = ocppj.Message[
	messages.NotifyEVChargingNeedsRequest,
	messages.NotifyEVChargingNeedsResponse,
]{Action: "NotifyEVChargingNeeds", Direction: ocppj.SentByCP}

// NotifyEVChargingSchedule is the OCPP NotifyEVChargingSchedule message (SentByCP).
var NotifyEVChargingSchedule = ocppj.Message[
	messages.NotifyEVChargingScheduleRequest,
	messages.NotifyEVChargingScheduleResponse,
]{Action: "NotifyEVChargingSchedule", Direction: ocppj.SentByCP}

// NotifyChargingLimit is the OCPP NotifyChargingLimit message (SentByCP).
var NotifyChargingLimit = ocppj.Message[
	messages.NotifyChargingLimitRequest,
	messages.NotifyChargingLimitResponse,
]{Action: "NotifyChargingLimit", Direction: ocppj.SentByCP}

// ClearedChargingLimit is the OCPP ClearedChargingLimit message (SentByCP).
var ClearedChargingLimit = ocppj.Message[
	messages.ClearedChargingLimitRequest,
	messages.ClearedChargingLimitResponse,
]{Action: "ClearedChargingLimit", Direction: ocppj.SentByCP}

// ReportChargingProfiles is the OCPP ReportChargingProfiles message (SentByCP).
var ReportChargingProfiles = ocppj.Message[
	messages.ReportChargingProfilesRequest,
	messages.ReportChargingProfilesResponse,
]{Action: "ReportChargingProfiles", Direction: ocppj.SentByCP}

// NotifyAllowedEnergyTransfer is the OCPP NotifyAllowedEnergyTransfer message (SentByCSMS).
var NotifyAllowedEnergyTransfer = ocppj.Message[
	messages.NotifyAllowedEnergyTransferRequest,
	messages.NotifyAllowedEnergyTransferResponse,
]{Action: "NotifyAllowedEnergyTransfer", Direction: ocppj.SentByCSMS}

// UsePriorityCharging is the OCPP UsePriorityCharging message (SentByCSMS).
var UsePriorityCharging = ocppj.Message[
	messages.UsePriorityChargingRequest,
	messages.UsePriorityChargingResponse,
]{Action: "UsePriorityCharging", Direction: ocppj.SentByCSMS}

// NotifyPriorityCharging is the OCPP NotifyPriorityCharging message (SentByCP).
var NotifyPriorityCharging = ocppj.Message[
	messages.NotifyPriorityChargingRequest,
	messages.NotifyPriorityChargingResponse,
]{Action: "NotifyPriorityCharging", Direction: ocppj.SentByCP}

// AFRRSignal is the OCPP AFRRSignal message (SentByCSMS).
var AFRRSignal = ocppj.Message[
	messages.AFRRSignalRequest,
	messages.AFRRSignalResponse,
]{Action: "AFRRSignal", Direction: ocppj.SentByCSMS}

// UpdateDynamicSchedule is the OCPP UpdateDynamicSchedule message (SentByCSMS).
var UpdateDynamicSchedule = ocppj.Message[
	messages.UpdateDynamicScheduleRequest,
	messages.UpdateDynamicScheduleResponse,
]{Action: "UpdateDynamicSchedule", Direction: ocppj.SentByCSMS}

// PullDynamicScheduleUpdate is the OCPP PullDynamicScheduleUpdate message (SentByCP).
var PullDynamicScheduleUpdate = ocppj.Message[
	messages.PullDynamicScheduleUpdateRequest,
	messages.PullDynamicScheduleUpdateResponse,
]{Action: "PullDynamicScheduleUpdate", Direction: ocppj.SentByCP}
