// Code generated by gocpp codegen. DO NOT EDIT.

package profiles

import (
	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/v21/messages"
)

// CostUpdated is the OCPP CostUpdated message (SentByCSMS).
var CostUpdated = ocppj.Message[
	messages.CostUpdatedRequest,
	messages.CostUpdatedResponse,
]{Action: "CostUpdated", Direction: ocppj.SentByCSMS}

// ChangeTransactionTariff is the OCPP ChangeTransactionTariff message (SentByCSMS).
var ChangeTransactionTariff = ocppj.Message[
	messages.ChangeTransactionTariffRequest,
	messages.ChangeTransactionTariffResponse,
]{Action: "ChangeTransactionTariff", Direction: ocppj.SentByCSMS}

// ClearTariffs is the OCPP ClearTariffs message (SentByCSMS).
var ClearTariffs = ocppj.Message[
	messages.ClearTariffsRequest,
	messages.ClearTariffsResponse,
]{Action: "ClearTariffs", Direction: ocppj.SentByCSMS}

// GetTariffs is the OCPP GetTariffs message (SentByCSMS).
var GetTariffs = ocppj.Message[
	messages.GetTariffsRequest,
	messages.GetTariffsResponse,
]{Action: "GetTariffs", Direction: ocppj.SentByCSMS}

// SetDefaultTariff is the OCPP SetDefaultTariff message (SentByCSMS).
var SetDefaultTariff = ocppj.Message[
	messages.SetDefaultTariffRequest,
	messages.SetDefaultTariffResponse,
]{Action: "SetDefaultTariff", Direction: ocppj.SentByCSMS}
