package render

import (
	"strings"
	"testing"

	"github.com/shiv3/gocpp/internal/codegen/ir"
)

func TestRenderMessages(t *testing.T) {
	f := ir.File{
		Version: "v16",
		Package: "messages",
		Enums: []ir.Enum{
			{GoName: "RegistrationStatus", Values: []string{"Accepted", "Pending", "Rejected"}},
		},
		Structs: []ir.Struct{
			{GoName: "BootNotificationRequest", Fields: []ir.Field{
				{GoName: "ChargePointVendor", JSONName: "chargePointVendor", Type: ir.TypeString, Required: true, MaxLength: 20},
				{GoName: "Iccid", JSONName: "iccid", Type: ir.TypeString, Required: false, MaxLength: 20},
			}},
		},
	}
	out, err := Messages(f)
	if err != nil {
		t.Fatalf("Messages() error = %v", err)
	}
	src := string(out)
	assertContains(t, src, "// Code generated by gocpp codegen. DO NOT EDIT.")
	assertContains(t, src, "package messages")
	assertContains(t, src, "type BootNotificationRequest struct")
	assertContains(t, src, "ChargePointVendor string")
	assertContains(t, src, "`json:\"chargePointVendor\" validate:\"required,max=20\"`")
	assertContains(t, src, "Iccid")
	assertContains(t, src, "*string")
	assertContains(t, src, "`json:\"iccid,omitempty\" validate:\"omitempty,max=20\"`")
	assertContains(t, src, "type RegistrationStatus string")
	assertContains(t, src, `RegistrationStatusAccepted RegistrationStatus = "Accepted"`)
	if !strings.HasPrefix(src, "// Code generated") {
		t.Fatalf("source does not start with generated header")
	}
}

func TestRenderProfile(t *testing.T) {
	f := ir.File{
		Version: "v16",
		Messages: []ir.Message{
			{Action: "BootNotification", Direction: "SentByCP", Request: "BootNotificationRequest", Response: "BootNotificationResponse"},
		},
	}
	out, err := Profile(f, "Core")
	if err != nil {
		t.Fatalf("Profile() error = %v", err)
	}
	src := string(out)
	assertContains(t, src, "package profiles")
	assertContains(t, src, "var BootNotification = ocppj.Message[")
	assertContains(t, src, "messages.BootNotificationRequest")
	assertContains(t, src, "messages.BootNotificationResponse")
	assertContains(t, src, "Action: \"BootNotification\"")
	assertContains(t, src, "Direction: ocppj.SentByCP")
}

func TestRenderClient(t *testing.T) {
	msgs := []ir.Message{
		{Action: "BootNotification", Direction: "SentByCP", Request: "BootNotificationRequest", Response: "BootNotificationResponse"},
		{Action: "Reset", Direction: "SentByCSMS", Request: "ResetRequest", Response: "ResetResponse"},
		{Action: "DataTransfer", Direction: "SentByBoth", Request: "DataTransferRequest", Response: "DataTransferResponse"},
	}
	out, err := ClientFile("v16", msgs)
	if err != nil {
		t.Fatalf("ClientFile() error = %v", err)
	}
	src := string(out)

	assertContains(t, src, "// Code generated by gocpp codegen. DO NOT EDIT.")
	assertContains(t, src, "package client")

	// CP wrapper + constructor.
	assertContains(t, src, "type CP struct{ *cp.Client }")
	assertContains(t, src, "func NewCP(c *cp.Client) CP { return CP{c} }")

	// CP sync method: BootNotification (SentByCP) and DataTransfer (SentByBoth).
	assertContains(t, src, "func (c CP) BootNotification(ctx context.Context, req messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {")
	assertContains(t, src, "return cp.Call(ctx, c.Client, profiles.BootNotification, req)")
	assertContains(t, src, "func (c CP) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {")

	// CP async method.
	assertContains(t, src, "func (c CP) BootNotificationAsync(ctx context.Context, req messages.BootNotificationRequest, cb func(messages.BootNotificationResponse, error)) error {")
	assertContains(t, src, "return cp.CallAsync(ctx, c.Client, profiles.BootNotification, req, cb)")

	// Reset is CSMS-only: must not appear as a CP method.
	if strings.Contains(src, "func (c CP) Reset(") {
		t.Fatalf("Reset must not be a CP method:\n%s", src)
	}

	// CSMS wrapper + constructor.
	assertContains(t, src, "type CSMS struct{ *csms.Conn }")
	assertContains(t, src, "func NewCSMS(c *csms.Conn) CSMS { return CSMS{c} }")

	// CSMS sync method: Reset (SentByCSMS) and DataTransfer (SentByBoth).
	assertContains(t, src, "func (c CSMS) Reset(ctx context.Context, req messages.ResetRequest) (messages.ResetResponse, error) {")
	assertContains(t, src, "return csms.Call(ctx, c.Conn, profiles.Reset, req)")
	assertContains(t, src, "func (c CSMS) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {")

	// CSMS async method.
	assertContains(t, src, "func (c CSMS) ResetAsync(ctx context.Context, req messages.ResetRequest, cb func(messages.ResetResponse, error)) error {")
	assertContains(t, src, "return csms.CallAsync(ctx, c.Conn, profiles.Reset, req, cb)")

	// BootNotification is CP-only: must not appear as a CSMS method.
	if strings.Contains(src, "func (c CSMS) BootNotification(") {
		t.Fatalf("BootNotification must not be a CSMS method:\n%s", src)
	}
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Fatalf("source does not contain %q:\n%s", substr, s)
	}
}
