// Package render turns codegen IR into formatted Go source.
package render

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/shiv3/gocpp/internal/codegen/ir"
)

const header = "// Code generated by gocpp codegen. DO NOT EDIT.\n\n"

// Messages renders the message structs and enums for one version into Go source.
func Messages(f ir.File) ([]byte, error) {
	var b strings.Builder
	writeHeader(&b, f.Package)
	writeImports(&b, neededImports(f))
	writeEnums(&b, f.Enums)
	writeStructs(&b, f.Structs)
	return format.Source([]byte(b.String()))
}

// Structs renders only message structs for one version into Go source.
func Structs(f ir.File) ([]byte, error) {
	var b strings.Builder
	writeHeader(&b, f.Package)
	writeImports(&b, neededImports(ir.File{Structs: f.Structs}))
	writeStructs(&b, f.Structs)
	return format.Source([]byte(b.String()))
}

// Enums renders only enums for one version into Go source.
func Enums(f ir.File) ([]byte, error) {
	var b strings.Builder
	writeHeader(&b, f.Package)
	writeEnums(&b, f.Enums)
	return format.Source([]byte(b.String()))
}

// Profile renders the package-level Message vars for one feature profile.
func Profile(f ir.File, profileName string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package profiles\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/core/ocppj")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+f.Version+"/messages")
	b.WriteString(")\n\n")

	for _, m := range f.Messages {
		fmt.Fprintf(&b, "// %s is the OCPP %s message (%s).\n", m.Action, m.Action, m.Direction)
		fmt.Fprintf(&b, "var %s = ocppj.Message[\n\tmessages.%s,\n\tmessages.%s,\n]{Action: %q, Direction: ocppj.%s}\n\n",
			m.Action, m.Request, m.Response, m.Action, m.Direction)
	}
	return format.Source([]byte(b.String()))
}

func writeHeader(b *strings.Builder, pkg string) {
	b.WriteString(header)
	fmt.Fprintf(b, "package %s\n\n", pkg)
}

func writeImports(b *strings.Builder, imports []string) {
	if len(imports) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")
}

func writeEnums(b *strings.Builder, enums []ir.Enum) {
	for _, e := range enums {
		fmt.Fprintf(b, "type %s string\n\nconst (\n", e.GoName)
		for _, v := range e.Values {
			fmt.Fprintf(b, "\t%s%s %s = %q\n", e.GoName, exportEnumValue(v), e.GoName, v)
		}
		b.WriteString(")\n\n")
	}
}

func writeStructs(b *strings.Builder, structs []ir.Struct) {
	for _, s := range structs {
		fmt.Fprintf(b, "type %s struct {\n", s.GoName)
		for _, fld := range s.Fields {
			jsonTag := fld.JSONName
			if !fld.Required {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(b, "\t%s %s `json:%q validate:%q`\n", fld.GoName, fld.GoType(), jsonTag, validateTag(fld))
		}
		b.WriteString("}\n\n")
	}
}

func neededImports(f ir.File) []string {
	var needTime, needDecimal bool
	for _, s := range f.Structs {
		for _, fld := range s.Fields {
			switch fld.Type {
			case ir.TypeDateTime:
				needTime = true
			case ir.TypeNumber:
				needDecimal = true
			}
		}
	}
	var imps []string
	if needDecimal {
		imps = append(imps, "github.com/shopspring/decimal")
	}
	if needTime {
		imps = append(imps, "time")
	}
	return imps
}

func validateTag(f ir.Field) string {
	var parts []string
	if f.Required {
		parts = append(parts, "required")
	} else {
		parts = append(parts, "omitempty")
	}
	if f.MaxLength > 0 {
		parts = append(parts, fmt.Sprintf("max=%d", f.MaxLength))
	}
	return strings.Join(parts, ",")
}

// exportEnumValue turns a wire enum value into a Go const suffix.
func exportEnumValue(v string) string {
	replacer := strings.NewReplacer("-", "", ".", "", " ", "", "_", "")
	v = replacer.Replace(v)
	if v == "" {
		return "Empty"
	}
	return strings.ToUpper(v[:1]) + v[1:]
}
