// Package render turns codegen IR into formatted Go source.
package render

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/shiv3/gocpp/internal/codegen/ir"
)

const header = "// Code generated by gocpp codegen. DO NOT EDIT.\n\n"

// Messages renders the message structs and enums for one version into Go source.
func Messages(f ir.File) ([]byte, error) {
	return renderFile(f, false, false)
}

// MessageFile renders the structs and enums for a single message file.
func MessageFile(pkg string, structs []ir.Struct, enums []ir.Enum, needTime, needDecimal bool) ([]byte, error) {
	return renderFile(ir.File{Package: pkg, Structs: structs, Enums: enums}, needTime, needDecimal)
}

// EnumsFile renders shared enums into one package file.
func EnumsFile(pkg string, enums []ir.Enum) ([]byte, error) {
	return renderFile(ir.File{Package: pkg, Enums: enums}, false, false)
}

// Structs renders only message structs for one version into Go source.
func Structs(f ir.File) ([]byte, error) {
	return renderFile(ir.File{Package: f.Package, Structs: f.Structs}, false, false)
}

// Enums renders only enums for one version into Go source.
func Enums(f ir.File) ([]byte, error) {
	return renderFile(ir.File{Package: f.Package, Enums: f.Enums}, false, false)
}

func renderFile(f ir.File, forceTime, forceDecimal bool) ([]byte, error) {
	var b strings.Builder
	writeHeader(&b, f.Package)
	writeImports(&b, neededImports(f, forceTime, forceDecimal))
	writeEnums(&b, f.Enums)
	writeStructs(&b, f.Structs)
	return format.Source([]byte(b.String()))
}

// Profile renders the package-level Message vars for one feature profile.
func Profile(f ir.File, profileName string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package profiles\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/core/ocppj")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+f.Version+"/messages")
	b.WriteString(")\n\n")

	for _, m := range f.Messages {
		fmt.Fprintf(&b, "// %s is the OCPP %s message (%s).\n", m.Action, m.Action, m.Direction)
		fmt.Fprintf(&b, "var %s = ocppj.Message[\n\tmessages.%s,\n\tmessages.%s,\n]{Action: %q, Direction: ocppj.%s}\n\n",
			m.Action, m.Request, m.Response, m.Action, m.Direction)
	}
	return format.Source([]byte(b.String()))
}

// RegisterFile renders a helper that registers all generated schemas.
func RegisterFile(version string, messages []ir.Message) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package profiles\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/core/schema")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+version+"/schemas")
	b.WriteString(")\n\n")
	b.WriteString("// RegisterSchemas registers all " + version + " request/response schemas.\n")
	b.WriteString("func RegisterSchemas(r *schema.Registry) error {\n")
	b.WriteString("\ttype reg struct{ action, kind, file string }\n")
	b.WriteString("\tfor _, e := range []reg{\n")
	for _, m := range messages {
		requestSchema := m.RequestSchema
		if requestSchema == "" {
			requestSchema = m.Action + ".json"
		}
		responseSchema := m.ResponseSchema
		if responseSchema == "" {
			responseSchema = m.Action + "Response.json"
		}
		fmt.Fprintf(&b, "\t\t{%q, \"request\", %q},\n", m.Action, requestSchema)
		fmt.Fprintf(&b, "\t\t{%q, \"response\", %q},\n", m.Action, responseSchema)
	}
	b.WriteString("\t} {\n")
	fmt.Fprintf(&b, "\t\tif err := r.Register(%q, e.action, e.kind, schemas.FS, e.file); err != nil {\n", versionString(version))
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}

// HandlersFile renders the typed handler interfaces, Unimplemented defaults, and
// one-call registrars (RegisterCP / RegisterCSMS) for one version.
func HandlersFile(version string, messages []ir.Message) ([]byte, error) {
	// cpMsgs: messages a charge point receives (CSMS-initiated or bidirectional).
	// csmsMsgs: messages a CSMS receives (CP-initiated or bidirectional).
	var cpMsgs, csmsMsgs []ir.Message
	for _, m := range messages {
		if m.Direction == "SentByCSMS" || m.Direction == "SentByBoth" {
			cpMsgs = append(cpMsgs, m)
		}
		if m.Direction == "SentByCP" || m.Direction == "SentByBoth" {
			csmsMsgs = append(csmsMsgs, m)
		}
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package handlers\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/core/ocppj")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/cp")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/csms")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+version+"/messages")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+version+"/profiles")
	b.WriteString(")\n\n")

	// ----- Charge-point side -----
	b.WriteString("// CPHandler handles CSMS-initiated messages received by a charge point.\n")
	b.WriteString("type CPHandler interface {\n")
	for _, m := range cpMsgs {
		fmt.Fprintf(&b, "\tOn%s(context.Context, messages.%s) (messages.%s, error)\n", m.Action, m.Request, m.Response)
	}
	b.WriteString("}\n\n")

	b.WriteString("// UnimplementedCPHandler returns a NotSupported CallError for every message.\n")
	b.WriteString("// Embed it to implement only the messages you care about.\n")
	b.WriteString("type UnimplementedCPHandler struct{}\n\n")
	for _, m := range cpMsgs {
		fmt.Fprintf(&b, "func (UnimplementedCPHandler) On%s(context.Context, messages.%s) (messages.%s, error) {\n", m.Action, m.Request, m.Response)
		fmt.Fprintf(&b, "\treturn messages.%s{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, %q, nil)\n", m.Response, m.Action+" not implemented")
		b.WriteString("}\n\n")
	}

	b.WriteString("// RegisterCP registers every CSMS->CP handler from h on the client.\n")
	b.WriteString("func RegisterCP(c *cp.Client, h CPHandler) error {\n")
	for _, m := range cpMsgs {
		fmt.Fprintf(&b, "\tif err := cp.On(c, profiles.%s, h.On%s); err != nil {\n\t\treturn err\n\t}\n", m.Action, m.Action)
	}
	b.WriteString("\treturn nil\n}\n\n")

	// ----- CSMS side -----
	b.WriteString("// CSMSHandler handles CP-initiated messages received by a CSMS.\n")
	b.WriteString("type CSMSHandler interface {\n")
	for _, m := range csmsMsgs {
		fmt.Fprintf(&b, "\tOn%s(context.Context, *csms.Conn, messages.%s) (messages.%s, error)\n", m.Action, m.Request, m.Response)
	}
	b.WriteString("}\n\n")

	b.WriteString("// UnimplementedCSMSHandler returns a NotSupported CallError for every message.\n")
	b.WriteString("// Embed it to implement only the messages you care about.\n")
	b.WriteString("type UnimplementedCSMSHandler struct{}\n\n")
	for _, m := range csmsMsgs {
		fmt.Fprintf(&b, "func (UnimplementedCSMSHandler) On%s(context.Context, *csms.Conn, messages.%s) (messages.%s, error) {\n", m.Action, m.Request, m.Response)
		fmt.Fprintf(&b, "\treturn messages.%s{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, %q, nil)\n", m.Response, m.Action+" not implemented")
		b.WriteString("}\n\n")
	}

	b.WriteString("// RegisterCSMS registers every CP->CSMS handler from h on the server.\n")
	b.WriteString("func RegisterCSMS(s *csms.Server, h CSMSHandler) error {\n")
	for _, m := range csmsMsgs {
		fmt.Fprintf(&b, "\tif err := csms.On(s, profiles.%s, h.On%s); err != nil {\n\t\treturn err\n\t}\n", m.Action, m.Action)
	}
	b.WriteString("\treturn nil\n}\n")

	return format.Source([]byte(b.String()))
}

// CallsFile renders typed send helpers for one version: CP<Action> wraps
// cp.Call for charge-point-sendable messages, CSMS<Action> wraps csms.Call for
// CSMS-sendable messages. Bidirectional messages (DataTransfer) get both.
func CallsFile(version string, messages []ir.Message) ([]byte, error) {
	var cpSend, csmsSend []ir.Message
	for _, m := range messages {
		if m.Direction == "SentByCP" || m.Direction == "SentByBoth" {
			cpSend = append(cpSend, m)
		}
		if m.Direction == "SentByCSMS" || m.Direction == "SentByBoth" {
			csmsSend = append(csmsSend, m)
		}
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package calls\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", "context")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/cp")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/csms")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+version+"/messages")
	fmt.Fprintf(&b, "\t%q\n", "github.com/shiv3/gocpp/"+version+"/profiles")
	b.WriteString(")\n\n")

	for _, m := range cpSend {
		fmt.Fprintf(&b, "// CP%s sends a %s request from the charge point to the CSMS.\n", m.Action, m.Action)
		fmt.Fprintf(&b, "func CP%s(ctx context.Context, c *cp.Client, req messages.%s) (messages.%s, error) {\n", m.Action, m.Request, m.Response)
		fmt.Fprintf(&b, "\treturn cp.Call(ctx, c, profiles.%s, req)\n}\n\n", m.Action)
	}
	for _, m := range csmsSend {
		fmt.Fprintf(&b, "// CSMS%s sends a %s request from the CSMS to a connected charge point.\n", m.Action, m.Action)
		fmt.Fprintf(&b, "func CSMS%s(ctx context.Context, conn *csms.Conn, req messages.%s) (messages.%s, error) {\n", m.Action, m.Request, m.Response)
		fmt.Fprintf(&b, "\treturn csms.Call(ctx, conn, profiles.%s, req)\n}\n\n", m.Action)
	}

	return format.Source([]byte(b.String()))
}

func versionString(version string) string {
	switch version {
	case "v16":
		return "1.6"
	case "v201":
		return "2.0.1"
	case "v21":
		return "2.1"
	default:
		return strings.TrimPrefix(version, "v")
	}
}

func writeHeader(b *strings.Builder, pkg string) {
	b.WriteString(header)
	fmt.Fprintf(b, "package %s\n\n", pkg)
}

func writeImports(b *strings.Builder, imports []string) {
	if len(imports) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")
}

func writeEnums(b *strings.Builder, enums []ir.Enum) {
	for _, e := range enums {
		fmt.Fprintf(b, "type %s string\n\nconst (\n", e.GoName)
		consts := make([]string, 0, len(e.Values))
		for _, v := range e.Values {
			name := e.GoName + exportEnumValue(v)
			consts = append(consts, name)
			fmt.Fprintf(b, "\t%s %s = %q\n", name, e.GoName, v)
		}
		b.WriteString(")\n\n")
		fmt.Fprintf(b, "// Valid reports whether e is a defined %s value.\n", e.GoName)
		fmt.Fprintf(b, "func (e %s) Valid() bool {\n", e.GoName)
		b.WriteString("\tswitch e {\n")
		fmt.Fprintf(b, "\tcase %s:\n", strings.Join(consts, ", "))
		b.WriteString("\t\treturn true\n")
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}
}

func writeStructs(b *strings.Builder, structs []ir.Struct) {
	for _, s := range structs {
		fmt.Fprintf(b, "type %s struct {\n", s.GoName)
		for _, fld := range s.Fields {
			jsonTag := fld.JSONName
			if !fld.Required {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(b, "\t%s %s `json:%q validate:%q`\n", fld.GoName, fld.GoType(), jsonTag, validateTag(fld))
		}
		b.WriteString("}\n\n")
	}
}

func neededImports(f ir.File, forceTime, forceDecimal bool) []string {
	needTime, needDecimal := forceTime, forceDecimal
	for _, s := range f.Structs {
		for _, fld := range s.Fields {
			switch fld.Type {
			case ir.TypeDateTime:
				needTime = true
			case ir.TypeNumber:
				needDecimal = true
			}
		}
	}
	var imps []string
	if needDecimal {
		imps = append(imps, "github.com/shopspring/decimal")
	}
	if needTime {
		imps = append(imps, "time")
	}
	return imps
}

func validateTag(f ir.Field) string {
	var parts []string
	if f.Required {
		parts = append(parts, "required")
	} else {
		parts = append(parts, "omitempty")
	}
	if f.MaxLength > 0 {
		parts = append(parts, fmt.Sprintf("max=%d", f.MaxLength))
	}
	return strings.Join(parts, ",")
}

// exportEnumValue turns a wire enum value into a Go const suffix.
func exportEnumValue(v string) string {
	replacer := strings.NewReplacer("-", "", ".", "", " ", "", "_", "")
	v = replacer.Replace(v)
	if v == "" {
		return "Empty"
	}
	return strings.ToUpper(v[:1]) + v[1:]
}
