package render

import (
	"strings"
	"testing"

	"github.com/shiv3/gocpp/internal/codegen/ir"
)

func TestRenderMessages(t *testing.T) {
	f := ir.File{
		Version: "v16",
		Package: "messages",
		Enums: []ir.Enum{
			{GoName: "RegistrationStatus", Values: []string{"Accepted", "Pending", "Rejected"}},
		},
		Structs: []ir.Struct{
			{GoName: "BootNotificationRequest", Fields: []ir.Field{
				{GoName: "ChargePointVendor", JSONName: "chargePointVendor", Type: ir.TypeString, Required: true, MaxLength: 20},
				{GoName: "Iccid", JSONName: "iccid", Type: ir.TypeString, Required: false, MaxLength: 20},
			}},
		},
	}
	out, err := Messages(f)
	if err != nil {
		t.Fatalf("Messages() error = %v", err)
	}
	src := string(out)
	assertContains(t, src, "// Code generated by gocpp codegen. DO NOT EDIT.")
	assertContains(t, src, "package messages")
	assertContains(t, src, "type BootNotificationRequest struct")
	assertContains(t, src, "ChargePointVendor string")
	assertContains(t, src, "`json:\"chargePointVendor\" validate:\"required,max=20\"`")
	assertContains(t, src, "Iccid")
	assertContains(t, src, "*string")
	assertContains(t, src, "`json:\"iccid,omitempty\" validate:\"omitempty,max=20\"`")
	assertContains(t, src, "type RegistrationStatus string")
	assertContains(t, src, `RegistrationStatusAccepted RegistrationStatus = "Accepted"`)
	if !strings.HasPrefix(src, "// Code generated") {
		t.Fatalf("source does not start with generated header")
	}
}

func TestRenderProfile(t *testing.T) {
	f := ir.File{
		Version: "v16",
		Messages: []ir.Message{
			{Action: "BootNotification", Direction: "SentByCP", Request: "BootNotificationRequest", Response: "BootNotificationResponse"},
		},
	}
	out, err := Profile(f, "Core")
	if err != nil {
		t.Fatalf("Profile() error = %v", err)
	}
	src := string(out)
	assertContains(t, src, "package profiles")
	assertContains(t, src, "var BootNotification = ocppj.Message[")
	assertContains(t, src, "messages.BootNotificationRequest")
	assertContains(t, src, "messages.BootNotificationResponse")
	assertContains(t, src, "Action: \"BootNotification\"")
	assertContains(t, src, "Direction: ocppj.SentByCP")
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Fatalf("source does not contain %q:\n%s", substr, s)
	}
}
