// Code generated by gocpp codegen. DO NOT EDIT.

package calls

import (
	"context"

	"github.com/shiv3/gocpp/cp"
	"github.com/shiv3/gocpp/csms"
	"github.com/shiv3/gocpp/v16/messages"
	"github.com/shiv3/gocpp/v16/profiles"
)

// CPAuthorize sends a Authorize request from the charge point to the CSMS.
func CPAuthorize(ctx context.Context, c *cp.Client, req messages.AuthorizeRequest) (messages.AuthorizeResponse, error) {
	return cp.Call(ctx, c, profiles.Authorize, req)
}

// CPBootNotification sends a BootNotification request from the charge point to the CSMS.
func CPBootNotification(ctx context.Context, c *cp.Client, req messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.BootNotification, req)
}

// CPDataTransfer sends a DataTransfer request from the charge point to the CSMS.
func CPDataTransfer(ctx context.Context, c *cp.Client, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return cp.Call(ctx, c, profiles.DataTransfer, req)
}

// CPHeartbeat sends a Heartbeat request from the charge point to the CSMS.
func CPHeartbeat(ctx context.Context, c *cp.Client, req messages.HeartbeatRequest) (messages.HeartbeatResponse, error) {
	return cp.Call(ctx, c, profiles.Heartbeat, req)
}

// CPMeterValues sends a MeterValues request from the charge point to the CSMS.
func CPMeterValues(ctx context.Context, c *cp.Client, req messages.MeterValuesRequest) (messages.MeterValuesResponse, error) {
	return cp.Call(ctx, c, profiles.MeterValues, req)
}

// CPStartTransaction sends a StartTransaction request from the charge point to the CSMS.
func CPStartTransaction(ctx context.Context, c *cp.Client, req messages.StartTransactionRequest) (messages.StartTransactionResponse, error) {
	return cp.Call(ctx, c, profiles.StartTransaction, req)
}

// CPStatusNotification sends a StatusNotification request from the charge point to the CSMS.
func CPStatusNotification(ctx context.Context, c *cp.Client, req messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.StatusNotification, req)
}

// CPStopTransaction sends a StopTransaction request from the charge point to the CSMS.
func CPStopTransaction(ctx context.Context, c *cp.Client, req messages.StopTransactionRequest) (messages.StopTransactionResponse, error) {
	return cp.Call(ctx, c, profiles.StopTransaction, req)
}

// CPDiagnosticsStatusNotification sends a DiagnosticsStatusNotification request from the charge point to the CSMS.
func CPDiagnosticsStatusNotification(ctx context.Context, c *cp.Client, req messages.DiagnosticsStatusNotificationRequest) (messages.DiagnosticsStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.DiagnosticsStatusNotification, req)
}

// CPFirmwareStatusNotification sends a FirmwareStatusNotification request from the charge point to the CSMS.
func CPFirmwareStatusNotification(ctx context.Context, c *cp.Client, req messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.FirmwareStatusNotification, req)
}

// CPLogStatusNotification sends a LogStatusNotification request from the charge point to the CSMS.
func CPLogStatusNotification(ctx context.Context, c *cp.Client, req messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.LogStatusNotification, req)
}

// CPSecurityEventNotification sends a SecurityEventNotification request from the charge point to the CSMS.
func CPSecurityEventNotification(ctx context.Context, c *cp.Client, req messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.SecurityEventNotification, req)
}

// CPSignCertificate sends a SignCertificate request from the charge point to the CSMS.
func CPSignCertificate(ctx context.Context, c *cp.Client, req messages.SignCertificateRequest) (messages.SignCertificateResponse, error) {
	return cp.Call(ctx, c, profiles.SignCertificate, req)
}

// CPSignedFirmwareStatusNotification sends a SignedFirmwareStatusNotification request from the charge point to the CSMS.
func CPSignedFirmwareStatusNotification(ctx context.Context, c *cp.Client, req messages.SignedFirmwareStatusNotificationRequest) (messages.SignedFirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c, profiles.SignedFirmwareStatusNotification, req)
}

// CSMSChangeAvailability sends a ChangeAvailability request from the CSMS to a connected charge point.
func CSMSChangeAvailability(ctx context.Context, conn *csms.Conn, req messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error) {
	return csms.Call(ctx, conn, profiles.ChangeAvailability, req)
}

// CSMSChangeConfiguration sends a ChangeConfiguration request from the CSMS to a connected charge point.
func CSMSChangeConfiguration(ctx context.Context, conn *csms.Conn, req messages.ChangeConfigurationRequest) (messages.ChangeConfigurationResponse, error) {
	return csms.Call(ctx, conn, profiles.ChangeConfiguration, req)
}

// CSMSClearCache sends a ClearCache request from the CSMS to a connected charge point.
func CSMSClearCache(ctx context.Context, conn *csms.Conn, req messages.ClearCacheRequest) (messages.ClearCacheResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearCache, req)
}

// CSMSDataTransfer sends a DataTransfer request from the CSMS to a connected charge point.
func CSMSDataTransfer(ctx context.Context, conn *csms.Conn, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return csms.Call(ctx, conn, profiles.DataTransfer, req)
}

// CSMSGetConfiguration sends a GetConfiguration request from the CSMS to a connected charge point.
func CSMSGetConfiguration(ctx context.Context, conn *csms.Conn, req messages.GetConfigurationRequest) (messages.GetConfigurationResponse, error) {
	return csms.Call(ctx, conn, profiles.GetConfiguration, req)
}

// CSMSRemoteStartTransaction sends a RemoteStartTransaction request from the CSMS to a connected charge point.
func CSMSRemoteStartTransaction(ctx context.Context, conn *csms.Conn, req messages.RemoteStartTransactionRequest) (messages.RemoteStartTransactionResponse, error) {
	return csms.Call(ctx, conn, profiles.RemoteStartTransaction, req)
}

// CSMSRemoteStopTransaction sends a RemoteStopTransaction request from the CSMS to a connected charge point.
func CSMSRemoteStopTransaction(ctx context.Context, conn *csms.Conn, req messages.RemoteStopTransactionRequest) (messages.RemoteStopTransactionResponse, error) {
	return csms.Call(ctx, conn, profiles.RemoteStopTransaction, req)
}

// CSMSReset sends a Reset request from the CSMS to a connected charge point.
func CSMSReset(ctx context.Context, conn *csms.Conn, req messages.ResetRequest) (messages.ResetResponse, error) {
	return csms.Call(ctx, conn, profiles.Reset, req)
}

// CSMSUnlockConnector sends a UnlockConnector request from the CSMS to a connected charge point.
func CSMSUnlockConnector(ctx context.Context, conn *csms.Conn, req messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error) {
	return csms.Call(ctx, conn, profiles.UnlockConnector, req)
}

// CSMSGetDiagnostics sends a GetDiagnostics request from the CSMS to a connected charge point.
func CSMSGetDiagnostics(ctx context.Context, conn *csms.Conn, req messages.GetDiagnosticsRequest) (messages.GetDiagnosticsResponse, error) {
	return csms.Call(ctx, conn, profiles.GetDiagnostics, req)
}

// CSMSUpdateFirmware sends a UpdateFirmware request from the CSMS to a connected charge point.
func CSMSUpdateFirmware(ctx context.Context, conn *csms.Conn, req messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error) {
	return csms.Call(ctx, conn, profiles.UpdateFirmware, req)
}

// CSMSGetLocalListVersion sends a GetLocalListVersion request from the CSMS to a connected charge point.
func CSMSGetLocalListVersion(ctx context.Context, conn *csms.Conn, req messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error) {
	return csms.Call(ctx, conn, profiles.GetLocalListVersion, req)
}

// CSMSSendLocalList sends a SendLocalList request from the CSMS to a connected charge point.
func CSMSSendLocalList(ctx context.Context, conn *csms.Conn, req messages.SendLocalListRequest) (messages.SendLocalListResponse, error) {
	return csms.Call(ctx, conn, profiles.SendLocalList, req)
}

// CSMSTriggerMessage sends a TriggerMessage request from the CSMS to a connected charge point.
func CSMSTriggerMessage(ctx context.Context, conn *csms.Conn, req messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error) {
	return csms.Call(ctx, conn, profiles.TriggerMessage, req)
}

// CSMSCancelReservation sends a CancelReservation request from the CSMS to a connected charge point.
func CSMSCancelReservation(ctx context.Context, conn *csms.Conn, req messages.CancelReservationRequest) (messages.CancelReservationResponse, error) {
	return csms.Call(ctx, conn, profiles.CancelReservation, req)
}

// CSMSReserveNow sends a ReserveNow request from the CSMS to a connected charge point.
func CSMSReserveNow(ctx context.Context, conn *csms.Conn, req messages.ReserveNowRequest) (messages.ReserveNowResponse, error) {
	return csms.Call(ctx, conn, profiles.ReserveNow, req)
}

// CSMSCertificateSigned sends a CertificateSigned request from the CSMS to a connected charge point.
func CSMSCertificateSigned(ctx context.Context, conn *csms.Conn, req messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error) {
	return csms.Call(ctx, conn, profiles.CertificateSigned, req)
}

// CSMSDeleteCertificate sends a DeleteCertificate request from the CSMS to a connected charge point.
func CSMSDeleteCertificate(ctx context.Context, conn *csms.Conn, req messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error) {
	return csms.Call(ctx, conn, profiles.DeleteCertificate, req)
}

// CSMSExtendedTriggerMessage sends a ExtendedTriggerMessage request from the CSMS to a connected charge point.
func CSMSExtendedTriggerMessage(ctx context.Context, conn *csms.Conn, req messages.ExtendedTriggerMessageRequest) (messages.ExtendedTriggerMessageResponse, error) {
	return csms.Call(ctx, conn, profiles.ExtendedTriggerMessage, req)
}

// CSMSGetInstalledCertificateIds sends a GetInstalledCertificateIds request from the CSMS to a connected charge point.
func CSMSGetInstalledCertificateIds(ctx context.Context, conn *csms.Conn, req messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error) {
	return csms.Call(ctx, conn, profiles.GetInstalledCertificateIds, req)
}

// CSMSGetLog sends a GetLog request from the CSMS to a connected charge point.
func CSMSGetLog(ctx context.Context, conn *csms.Conn, req messages.GetLogRequest) (messages.GetLogResponse, error) {
	return csms.Call(ctx, conn, profiles.GetLog, req)
}

// CSMSInstallCertificate sends a InstallCertificate request from the CSMS to a connected charge point.
func CSMSInstallCertificate(ctx context.Context, conn *csms.Conn, req messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error) {
	return csms.Call(ctx, conn, profiles.InstallCertificate, req)
}

// CSMSSignedUpdateFirmware sends a SignedUpdateFirmware request from the CSMS to a connected charge point.
func CSMSSignedUpdateFirmware(ctx context.Context, conn *csms.Conn, req messages.SignedUpdateFirmwareRequest) (messages.SignedUpdateFirmwareResponse, error) {
	return csms.Call(ctx, conn, profiles.SignedUpdateFirmware, req)
}

// CSMSClearChargingProfile sends a ClearChargingProfile request from the CSMS to a connected charge point.
func CSMSClearChargingProfile(ctx context.Context, conn *csms.Conn, req messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error) {
	return csms.Call(ctx, conn, profiles.ClearChargingProfile, req)
}

// CSMSGetCompositeSchedule sends a GetCompositeSchedule request from the CSMS to a connected charge point.
func CSMSGetCompositeSchedule(ctx context.Context, conn *csms.Conn, req messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error) {
	return csms.Call(ctx, conn, profiles.GetCompositeSchedule, req)
}

// CSMSSetChargingProfile sends a SetChargingProfile request from the CSMS to a connected charge point.
func CSMSSetChargingProfile(ctx context.Context, conn *csms.Conn, req messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error) {
	return csms.Call(ctx, conn, profiles.SetChargingProfile, req)
}
