// Code generated by gocpp codegen. DO NOT EDIT.

package client

import (
	"context"

	"github.com/shiv3/gocpp/cp"
	"github.com/shiv3/gocpp/csms"
	"github.com/shiv3/gocpp/v16/messages"
	"github.com/shiv3/gocpp/v16/profiles"
)

// CP wraps *cp.Client with typed send methods for messages a charge point
// sends to the CSMS.
type CP struct{ *cp.Client }

// NewCP wraps c so its CP->CSMS messages can be sent as methods.
func NewCP(c *cp.Client) CP { return CP{c} }

// Authorize sends a Authorize request from the charge point to the CSMS.
func (c CP) Authorize(ctx context.Context, req messages.AuthorizeRequest) (messages.AuthorizeResponse, error) {
	return cp.Call(ctx, c.Client, profiles.Authorize, req)
}

// AuthorizeAsync sends a Authorize request without blocking, delivering the response to cb.
func (c CP) AuthorizeAsync(ctx context.Context, req messages.AuthorizeRequest, cb func(messages.AuthorizeResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.Authorize, req, cb)
}

// BootNotification sends a BootNotification request from the charge point to the CSMS.
func (c CP) BootNotification(ctx context.Context, req messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.BootNotification, req)
}

// BootNotificationAsync sends a BootNotification request without blocking, delivering the response to cb.
func (c CP) BootNotificationAsync(ctx context.Context, req messages.BootNotificationRequest, cb func(messages.BootNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.BootNotification, req, cb)
}

// DataTransfer sends a DataTransfer request from the charge point to the CSMS.
func (c CP) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return cp.Call(ctx, c.Client, profiles.DataTransfer, req)
}

// DataTransferAsync sends a DataTransfer request without blocking, delivering the response to cb.
func (c CP) DataTransferAsync(ctx context.Context, req messages.DataTransferRequest, cb func(messages.DataTransferResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.DataTransfer, req, cb)
}

// Heartbeat sends a Heartbeat request from the charge point to the CSMS.
func (c CP) Heartbeat(ctx context.Context, req messages.HeartbeatRequest) (messages.HeartbeatResponse, error) {
	return cp.Call(ctx, c.Client, profiles.Heartbeat, req)
}

// HeartbeatAsync sends a Heartbeat request without blocking, delivering the response to cb.
func (c CP) HeartbeatAsync(ctx context.Context, req messages.HeartbeatRequest, cb func(messages.HeartbeatResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.Heartbeat, req, cb)
}

// MeterValues sends a MeterValues request from the charge point to the CSMS.
func (c CP) MeterValues(ctx context.Context, req messages.MeterValuesRequest) (messages.MeterValuesResponse, error) {
	return cp.Call(ctx, c.Client, profiles.MeterValues, req)
}

// MeterValuesAsync sends a MeterValues request without blocking, delivering the response to cb.
func (c CP) MeterValuesAsync(ctx context.Context, req messages.MeterValuesRequest, cb func(messages.MeterValuesResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.MeterValues, req, cb)
}

// StartTransaction sends a StartTransaction request from the charge point to the CSMS.
func (c CP) StartTransaction(ctx context.Context, req messages.StartTransactionRequest) (messages.StartTransactionResponse, error) {
	return cp.Call(ctx, c.Client, profiles.StartTransaction, req)
}

// StartTransactionAsync sends a StartTransaction request without blocking, delivering the response to cb.
func (c CP) StartTransactionAsync(ctx context.Context, req messages.StartTransactionRequest, cb func(messages.StartTransactionResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.StartTransaction, req, cb)
}

// StatusNotification sends a StatusNotification request from the charge point to the CSMS.
func (c CP) StatusNotification(ctx context.Context, req messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.StatusNotification, req)
}

// StatusNotificationAsync sends a StatusNotification request without blocking, delivering the response to cb.
func (c CP) StatusNotificationAsync(ctx context.Context, req messages.StatusNotificationRequest, cb func(messages.StatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.StatusNotification, req, cb)
}

// StopTransaction sends a StopTransaction request from the charge point to the CSMS.
func (c CP) StopTransaction(ctx context.Context, req messages.StopTransactionRequest) (messages.StopTransactionResponse, error) {
	return cp.Call(ctx, c.Client, profiles.StopTransaction, req)
}

// StopTransactionAsync sends a StopTransaction request without blocking, delivering the response to cb.
func (c CP) StopTransactionAsync(ctx context.Context, req messages.StopTransactionRequest, cb func(messages.StopTransactionResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.StopTransaction, req, cb)
}

// DiagnosticsStatusNotification sends a DiagnosticsStatusNotification request from the charge point to the CSMS.
func (c CP) DiagnosticsStatusNotification(ctx context.Context, req messages.DiagnosticsStatusNotificationRequest) (messages.DiagnosticsStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.DiagnosticsStatusNotification, req)
}

// DiagnosticsStatusNotificationAsync sends a DiagnosticsStatusNotification request without blocking, delivering the response to cb.
func (c CP) DiagnosticsStatusNotificationAsync(ctx context.Context, req messages.DiagnosticsStatusNotificationRequest, cb func(messages.DiagnosticsStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.DiagnosticsStatusNotification, req, cb)
}

// FirmwareStatusNotification sends a FirmwareStatusNotification request from the charge point to the CSMS.
func (c CP) FirmwareStatusNotification(ctx context.Context, req messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.FirmwareStatusNotification, req)
}

// FirmwareStatusNotificationAsync sends a FirmwareStatusNotification request without blocking, delivering the response to cb.
func (c CP) FirmwareStatusNotificationAsync(ctx context.Context, req messages.FirmwareStatusNotificationRequest, cb func(messages.FirmwareStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.FirmwareStatusNotification, req, cb)
}

// LogStatusNotification sends a LogStatusNotification request from the charge point to the CSMS.
func (c CP) LogStatusNotification(ctx context.Context, req messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.LogStatusNotification, req)
}

// LogStatusNotificationAsync sends a LogStatusNotification request without blocking, delivering the response to cb.
func (c CP) LogStatusNotificationAsync(ctx context.Context, req messages.LogStatusNotificationRequest, cb func(messages.LogStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.LogStatusNotification, req, cb)
}

// SecurityEventNotification sends a SecurityEventNotification request from the charge point to the CSMS.
func (c CP) SecurityEventNotification(ctx context.Context, req messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.SecurityEventNotification, req)
}

// SecurityEventNotificationAsync sends a SecurityEventNotification request without blocking, delivering the response to cb.
func (c CP) SecurityEventNotificationAsync(ctx context.Context, req messages.SecurityEventNotificationRequest, cb func(messages.SecurityEventNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.SecurityEventNotification, req, cb)
}

// SignCertificate sends a SignCertificate request from the charge point to the CSMS.
func (c CP) SignCertificate(ctx context.Context, req messages.SignCertificateRequest) (messages.SignCertificateResponse, error) {
	return cp.Call(ctx, c.Client, profiles.SignCertificate, req)
}

// SignCertificateAsync sends a SignCertificate request without blocking, delivering the response to cb.
func (c CP) SignCertificateAsync(ctx context.Context, req messages.SignCertificateRequest, cb func(messages.SignCertificateResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.SignCertificate, req, cb)
}

// SignedFirmwareStatusNotification sends a SignedFirmwareStatusNotification request from the charge point to the CSMS.
func (c CP) SignedFirmwareStatusNotification(ctx context.Context, req messages.SignedFirmwareStatusNotificationRequest) (messages.SignedFirmwareStatusNotificationResponse, error) {
	return cp.Call(ctx, c.Client, profiles.SignedFirmwareStatusNotification, req)
}

// SignedFirmwareStatusNotificationAsync sends a SignedFirmwareStatusNotification request without blocking, delivering the response to cb.
func (c CP) SignedFirmwareStatusNotificationAsync(ctx context.Context, req messages.SignedFirmwareStatusNotificationRequest, cb func(messages.SignedFirmwareStatusNotificationResponse, error)) error {
	return cp.CallAsync(ctx, c.Client, profiles.SignedFirmwareStatusNotification, req, cb)
}

// CSMS wraps *csms.Conn with typed send methods for messages a CSMS sends to
// a connected charge point.
type CSMS struct{ *csms.Conn }

// NewCSMS wraps c so its CSMS->CP messages can be sent as methods.
func NewCSMS(c *csms.Conn) CSMS { return CSMS{c} }

// ChangeAvailability sends a ChangeAvailability request from the CSMS to the charge point.
func (c CSMS) ChangeAvailability(ctx context.Context, req messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ChangeAvailability, req)
}

// ChangeAvailabilityAsync sends a ChangeAvailability request without blocking, delivering the response to cb.
func (c CSMS) ChangeAvailabilityAsync(ctx context.Context, req messages.ChangeAvailabilityRequest, cb func(messages.ChangeAvailabilityResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ChangeAvailability, req, cb)
}

// ChangeConfiguration sends a ChangeConfiguration request from the CSMS to the charge point.
func (c CSMS) ChangeConfiguration(ctx context.Context, req messages.ChangeConfigurationRequest) (messages.ChangeConfigurationResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ChangeConfiguration, req)
}

// ChangeConfigurationAsync sends a ChangeConfiguration request without blocking, delivering the response to cb.
func (c CSMS) ChangeConfigurationAsync(ctx context.Context, req messages.ChangeConfigurationRequest, cb func(messages.ChangeConfigurationResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ChangeConfiguration, req, cb)
}

// ClearCache sends a ClearCache request from the CSMS to the charge point.
func (c CSMS) ClearCache(ctx context.Context, req messages.ClearCacheRequest) (messages.ClearCacheResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearCache, req)
}

// ClearCacheAsync sends a ClearCache request without blocking, delivering the response to cb.
func (c CSMS) ClearCacheAsync(ctx context.Context, req messages.ClearCacheRequest, cb func(messages.ClearCacheResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearCache, req, cb)
}

// DataTransfer sends a DataTransfer request from the CSMS to the charge point.
func (c CSMS) DataTransfer(ctx context.Context, req messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.DataTransfer, req)
}

// DataTransferAsync sends a DataTransfer request without blocking, delivering the response to cb.
func (c CSMS) DataTransferAsync(ctx context.Context, req messages.DataTransferRequest, cb func(messages.DataTransferResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.DataTransfer, req, cb)
}

// GetConfiguration sends a GetConfiguration request from the CSMS to the charge point.
func (c CSMS) GetConfiguration(ctx context.Context, req messages.GetConfigurationRequest) (messages.GetConfigurationResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetConfiguration, req)
}

// GetConfigurationAsync sends a GetConfiguration request without blocking, delivering the response to cb.
func (c CSMS) GetConfigurationAsync(ctx context.Context, req messages.GetConfigurationRequest, cb func(messages.GetConfigurationResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetConfiguration, req, cb)
}

// RemoteStartTransaction sends a RemoteStartTransaction request from the CSMS to the charge point.
func (c CSMS) RemoteStartTransaction(ctx context.Context, req messages.RemoteStartTransactionRequest) (messages.RemoteStartTransactionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.RemoteStartTransaction, req)
}

// RemoteStartTransactionAsync sends a RemoteStartTransaction request without blocking, delivering the response to cb.
func (c CSMS) RemoteStartTransactionAsync(ctx context.Context, req messages.RemoteStartTransactionRequest, cb func(messages.RemoteStartTransactionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.RemoteStartTransaction, req, cb)
}

// RemoteStopTransaction sends a RemoteStopTransaction request from the CSMS to the charge point.
func (c CSMS) RemoteStopTransaction(ctx context.Context, req messages.RemoteStopTransactionRequest) (messages.RemoteStopTransactionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.RemoteStopTransaction, req)
}

// RemoteStopTransactionAsync sends a RemoteStopTransaction request without blocking, delivering the response to cb.
func (c CSMS) RemoteStopTransactionAsync(ctx context.Context, req messages.RemoteStopTransactionRequest, cb func(messages.RemoteStopTransactionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.RemoteStopTransaction, req, cb)
}

// Reset sends a Reset request from the CSMS to the charge point.
func (c CSMS) Reset(ctx context.Context, req messages.ResetRequest) (messages.ResetResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.Reset, req)
}

// ResetAsync sends a Reset request without blocking, delivering the response to cb.
func (c CSMS) ResetAsync(ctx context.Context, req messages.ResetRequest, cb func(messages.ResetResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.Reset, req, cb)
}

// UnlockConnector sends a UnlockConnector request from the CSMS to the charge point.
func (c CSMS) UnlockConnector(ctx context.Context, req messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UnlockConnector, req)
}

// UnlockConnectorAsync sends a UnlockConnector request without blocking, delivering the response to cb.
func (c CSMS) UnlockConnectorAsync(ctx context.Context, req messages.UnlockConnectorRequest, cb func(messages.UnlockConnectorResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UnlockConnector, req, cb)
}

// GetDiagnostics sends a GetDiagnostics request from the CSMS to the charge point.
func (c CSMS) GetDiagnostics(ctx context.Context, req messages.GetDiagnosticsRequest) (messages.GetDiagnosticsResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetDiagnostics, req)
}

// GetDiagnosticsAsync sends a GetDiagnostics request without blocking, delivering the response to cb.
func (c CSMS) GetDiagnosticsAsync(ctx context.Context, req messages.GetDiagnosticsRequest, cb func(messages.GetDiagnosticsResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetDiagnostics, req, cb)
}

// UpdateFirmware sends a UpdateFirmware request from the CSMS to the charge point.
func (c CSMS) UpdateFirmware(ctx context.Context, req messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.UpdateFirmware, req)
}

// UpdateFirmwareAsync sends a UpdateFirmware request without blocking, delivering the response to cb.
func (c CSMS) UpdateFirmwareAsync(ctx context.Context, req messages.UpdateFirmwareRequest, cb func(messages.UpdateFirmwareResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.UpdateFirmware, req, cb)
}

// GetLocalListVersion sends a GetLocalListVersion request from the CSMS to the charge point.
func (c CSMS) GetLocalListVersion(ctx context.Context, req messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetLocalListVersion, req)
}

// GetLocalListVersionAsync sends a GetLocalListVersion request without blocking, delivering the response to cb.
func (c CSMS) GetLocalListVersionAsync(ctx context.Context, req messages.GetLocalListVersionRequest, cb func(messages.GetLocalListVersionResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetLocalListVersion, req, cb)
}

// SendLocalList sends a SendLocalList request from the CSMS to the charge point.
func (c CSMS) SendLocalList(ctx context.Context, req messages.SendLocalListRequest) (messages.SendLocalListResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SendLocalList, req)
}

// SendLocalListAsync sends a SendLocalList request without blocking, delivering the response to cb.
func (c CSMS) SendLocalListAsync(ctx context.Context, req messages.SendLocalListRequest, cb func(messages.SendLocalListResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SendLocalList, req, cb)
}

// TriggerMessage sends a TriggerMessage request from the CSMS to the charge point.
func (c CSMS) TriggerMessage(ctx context.Context, req messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.TriggerMessage, req)
}

// TriggerMessageAsync sends a TriggerMessage request without blocking, delivering the response to cb.
func (c CSMS) TriggerMessageAsync(ctx context.Context, req messages.TriggerMessageRequest, cb func(messages.TriggerMessageResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.TriggerMessage, req, cb)
}

// CancelReservation sends a CancelReservation request from the CSMS to the charge point.
func (c CSMS) CancelReservation(ctx context.Context, req messages.CancelReservationRequest) (messages.CancelReservationResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CancelReservation, req)
}

// CancelReservationAsync sends a CancelReservation request without blocking, delivering the response to cb.
func (c CSMS) CancelReservationAsync(ctx context.Context, req messages.CancelReservationRequest, cb func(messages.CancelReservationResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CancelReservation, req, cb)
}

// ReserveNow sends a ReserveNow request from the CSMS to the charge point.
func (c CSMS) ReserveNow(ctx context.Context, req messages.ReserveNowRequest) (messages.ReserveNowResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ReserveNow, req)
}

// ReserveNowAsync sends a ReserveNow request without blocking, delivering the response to cb.
func (c CSMS) ReserveNowAsync(ctx context.Context, req messages.ReserveNowRequest, cb func(messages.ReserveNowResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ReserveNow, req, cb)
}

// CertificateSigned sends a CertificateSigned request from the CSMS to the charge point.
func (c CSMS) CertificateSigned(ctx context.Context, req messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.CertificateSigned, req)
}

// CertificateSignedAsync sends a CertificateSigned request without blocking, delivering the response to cb.
func (c CSMS) CertificateSignedAsync(ctx context.Context, req messages.CertificateSignedRequest, cb func(messages.CertificateSignedResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.CertificateSigned, req, cb)
}

// DeleteCertificate sends a DeleteCertificate request from the CSMS to the charge point.
func (c CSMS) DeleteCertificate(ctx context.Context, req messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.DeleteCertificate, req)
}

// DeleteCertificateAsync sends a DeleteCertificate request without blocking, delivering the response to cb.
func (c CSMS) DeleteCertificateAsync(ctx context.Context, req messages.DeleteCertificateRequest, cb func(messages.DeleteCertificateResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.DeleteCertificate, req, cb)
}

// ExtendedTriggerMessage sends a ExtendedTriggerMessage request from the CSMS to the charge point.
func (c CSMS) ExtendedTriggerMessage(ctx context.Context, req messages.ExtendedTriggerMessageRequest) (messages.ExtendedTriggerMessageResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ExtendedTriggerMessage, req)
}

// ExtendedTriggerMessageAsync sends a ExtendedTriggerMessage request without blocking, delivering the response to cb.
func (c CSMS) ExtendedTriggerMessageAsync(ctx context.Context, req messages.ExtendedTriggerMessageRequest, cb func(messages.ExtendedTriggerMessageResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ExtendedTriggerMessage, req, cb)
}

// GetInstalledCertificateIds sends a GetInstalledCertificateIds request from the CSMS to the charge point.
func (c CSMS) GetInstalledCertificateIds(ctx context.Context, req messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetInstalledCertificateIds, req)
}

// GetInstalledCertificateIdsAsync sends a GetInstalledCertificateIds request without blocking, delivering the response to cb.
func (c CSMS) GetInstalledCertificateIdsAsync(ctx context.Context, req messages.GetInstalledCertificateIdsRequest, cb func(messages.GetInstalledCertificateIdsResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetInstalledCertificateIds, req, cb)
}

// GetLog sends a GetLog request from the CSMS to the charge point.
func (c CSMS) GetLog(ctx context.Context, req messages.GetLogRequest) (messages.GetLogResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetLog, req)
}

// GetLogAsync sends a GetLog request without blocking, delivering the response to cb.
func (c CSMS) GetLogAsync(ctx context.Context, req messages.GetLogRequest, cb func(messages.GetLogResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetLog, req, cb)
}

// InstallCertificate sends a InstallCertificate request from the CSMS to the charge point.
func (c CSMS) InstallCertificate(ctx context.Context, req messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.InstallCertificate, req)
}

// InstallCertificateAsync sends a InstallCertificate request without blocking, delivering the response to cb.
func (c CSMS) InstallCertificateAsync(ctx context.Context, req messages.InstallCertificateRequest, cb func(messages.InstallCertificateResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.InstallCertificate, req, cb)
}

// SignedUpdateFirmware sends a SignedUpdateFirmware request from the CSMS to the charge point.
func (c CSMS) SignedUpdateFirmware(ctx context.Context, req messages.SignedUpdateFirmwareRequest) (messages.SignedUpdateFirmwareResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SignedUpdateFirmware, req)
}

// SignedUpdateFirmwareAsync sends a SignedUpdateFirmware request without blocking, delivering the response to cb.
func (c CSMS) SignedUpdateFirmwareAsync(ctx context.Context, req messages.SignedUpdateFirmwareRequest, cb func(messages.SignedUpdateFirmwareResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SignedUpdateFirmware, req, cb)
}

// ClearChargingProfile sends a ClearChargingProfile request from the CSMS to the charge point.
func (c CSMS) ClearChargingProfile(ctx context.Context, req messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.ClearChargingProfile, req)
}

// ClearChargingProfileAsync sends a ClearChargingProfile request without blocking, delivering the response to cb.
func (c CSMS) ClearChargingProfileAsync(ctx context.Context, req messages.ClearChargingProfileRequest, cb func(messages.ClearChargingProfileResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.ClearChargingProfile, req, cb)
}

// GetCompositeSchedule sends a GetCompositeSchedule request from the CSMS to the charge point.
func (c CSMS) GetCompositeSchedule(ctx context.Context, req messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.GetCompositeSchedule, req)
}

// GetCompositeScheduleAsync sends a GetCompositeSchedule request without blocking, delivering the response to cb.
func (c CSMS) GetCompositeScheduleAsync(ctx context.Context, req messages.GetCompositeScheduleRequest, cb func(messages.GetCompositeScheduleResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.GetCompositeSchedule, req, cb)
}

// SetChargingProfile sends a SetChargingProfile request from the CSMS to the charge point.
func (c CSMS) SetChargingProfile(ctx context.Context, req messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error) {
	return csms.Call(ctx, c.Conn, profiles.SetChargingProfile, req)
}

// SetChargingProfileAsync sends a SetChargingProfile request without blocking, delivering the response to cb.
func (c CSMS) SetChargingProfileAsync(ctx context.Context, req messages.SetChargingProfileRequest, cb func(messages.SetChargingProfileResponse, error)) error {
	return csms.CallAsync(ctx, c.Conn, profiles.SetChargingProfile, req, cb)
}
