// Code generated by gocpp codegen. DO NOT EDIT.

package handlers

import (
	"context"

	"github.com/shiv3/gocpp/core/ocppj"
	"github.com/shiv3/gocpp/cp"
	"github.com/shiv3/gocpp/csms"
	"github.com/shiv3/gocpp/v201/messages"
	"github.com/shiv3/gocpp/v201/profiles"
)

// CPHandler handles CSMS-initiated messages received by a charge point.
type CPHandler interface {
	OnClearCache(context.Context, messages.ClearCacheRequest) (messages.ClearCacheResponse, error)
	OnChangeAvailability(context.Context, messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error)
	OnDataTransfer(context.Context, messages.DataTransferRequest) (messages.DataTransferResponse, error)
	OnGetMonitoringReport(context.Context, messages.GetMonitoringReportRequest) (messages.GetMonitoringReportResponse, error)
	OnSetMonitoringBase(context.Context, messages.SetMonitoringBaseRequest) (messages.SetMonitoringBaseResponse, error)
	OnSetVariableMonitoring(context.Context, messages.SetVariableMonitoringRequest) (messages.SetVariableMonitoringResponse, error)
	OnClearVariableMonitoring(context.Context, messages.ClearVariableMonitoringRequest) (messages.ClearVariableMonitoringResponse, error)
	OnSetMonitoringLevel(context.Context, messages.SetMonitoringLevelRequest) (messages.SetMonitoringLevelResponse, error)
	OnGetLog(context.Context, messages.GetLogRequest) (messages.GetLogResponse, error)
	OnCustomerInformation(context.Context, messages.CustomerInformationRequest) (messages.CustomerInformationResponse, error)
	OnSetDisplayMessage(context.Context, messages.SetDisplayMessageRequest) (messages.SetDisplayMessageResponse, error)
	OnGetDisplayMessages(context.Context, messages.GetDisplayMessagesRequest) (messages.GetDisplayMessagesResponse, error)
	OnClearDisplayMessage(context.Context, messages.ClearDisplayMessageRequest) (messages.ClearDisplayMessageResponse, error)
	OnUpdateFirmware(context.Context, messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error)
	OnPublishFirmware(context.Context, messages.PublishFirmwareRequest) (messages.PublishFirmwareResponse, error)
	OnUnpublishFirmware(context.Context, messages.UnpublishFirmwareRequest) (messages.UnpublishFirmwareResponse, error)
	OnGetInstalledCertificateIds(context.Context, messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error)
	OnInstallCertificate(context.Context, messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error)
	OnDeleteCertificate(context.Context, messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error)
	OnCertificateSigned(context.Context, messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error)
	OnGetLocalListVersion(context.Context, messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error)
	OnSendLocalList(context.Context, messages.SendLocalListRequest) (messages.SendLocalListResponse, error)
	OnGetBaseReport(context.Context, messages.GetBaseReportRequest) (messages.GetBaseReportResponse, error)
	OnGetReport(context.Context, messages.GetReportRequest) (messages.GetReportResponse, error)
	OnGetVariables(context.Context, messages.GetVariablesRequest) (messages.GetVariablesResponse, error)
	OnSetVariables(context.Context, messages.SetVariablesRequest) (messages.SetVariablesResponse, error)
	OnReset(context.Context, messages.ResetRequest) (messages.ResetResponse, error)
	OnSetNetworkProfile(context.Context, messages.SetNetworkProfileRequest) (messages.SetNetworkProfileResponse, error)
	OnRequestStartTransaction(context.Context, messages.RequestStartTransactionRequest) (messages.RequestStartTransactionResponse, error)
	OnRequestStopTransaction(context.Context, messages.RequestStopTransactionRequest) (messages.RequestStopTransactionResponse, error)
	OnUnlockConnector(context.Context, messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error)
	OnTriggerMessage(context.Context, messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error)
	OnReserveNow(context.Context, messages.ReserveNowRequest) (messages.ReserveNowResponse, error)
	OnCancelReservation(context.Context, messages.CancelReservationRequest) (messages.CancelReservationResponse, error)
	OnSetChargingProfile(context.Context, messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error)
	OnGetChargingProfiles(context.Context, messages.GetChargingProfilesRequest) (messages.GetChargingProfilesResponse, error)
	OnClearChargingProfile(context.Context, messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error)
	OnGetCompositeSchedule(context.Context, messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error)
	OnCostUpdated(context.Context, messages.CostUpdatedRequest) (messages.CostUpdatedResponse, error)
	OnGetTransactionStatus(context.Context, messages.GetTransactionStatusRequest) (messages.GetTransactionStatusResponse, error)
}

// UnimplementedCPHandler returns a NotSupported CallError for every message.
// Embed it to implement only the messages you care about.
type UnimplementedCPHandler struct{}

func (UnimplementedCPHandler) OnClearCache(context.Context, messages.ClearCacheRequest) (messages.ClearCacheResponse, error) {
	return messages.ClearCacheResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ClearCache not implemented", nil)
}

func (UnimplementedCPHandler) OnChangeAvailability(context.Context, messages.ChangeAvailabilityRequest) (messages.ChangeAvailabilityResponse, error) {
	return messages.ChangeAvailabilityResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ChangeAvailability not implemented", nil)
}

func (UnimplementedCPHandler) OnDataTransfer(context.Context, messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return messages.DataTransferResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "DataTransfer not implemented", nil)
}

func (UnimplementedCPHandler) OnGetMonitoringReport(context.Context, messages.GetMonitoringReportRequest) (messages.GetMonitoringReportResponse, error) {
	return messages.GetMonitoringReportResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetMonitoringReport not implemented", nil)
}

func (UnimplementedCPHandler) OnSetMonitoringBase(context.Context, messages.SetMonitoringBaseRequest) (messages.SetMonitoringBaseResponse, error) {
	return messages.SetMonitoringBaseResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetMonitoringBase not implemented", nil)
}

func (UnimplementedCPHandler) OnSetVariableMonitoring(context.Context, messages.SetVariableMonitoringRequest) (messages.SetVariableMonitoringResponse, error) {
	return messages.SetVariableMonitoringResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetVariableMonitoring not implemented", nil)
}

func (UnimplementedCPHandler) OnClearVariableMonitoring(context.Context, messages.ClearVariableMonitoringRequest) (messages.ClearVariableMonitoringResponse, error) {
	return messages.ClearVariableMonitoringResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ClearVariableMonitoring not implemented", nil)
}

func (UnimplementedCPHandler) OnSetMonitoringLevel(context.Context, messages.SetMonitoringLevelRequest) (messages.SetMonitoringLevelResponse, error) {
	return messages.SetMonitoringLevelResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetMonitoringLevel not implemented", nil)
}

func (UnimplementedCPHandler) OnGetLog(context.Context, messages.GetLogRequest) (messages.GetLogResponse, error) {
	return messages.GetLogResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetLog not implemented", nil)
}

func (UnimplementedCPHandler) OnCustomerInformation(context.Context, messages.CustomerInformationRequest) (messages.CustomerInformationResponse, error) {
	return messages.CustomerInformationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "CustomerInformation not implemented", nil)
}

func (UnimplementedCPHandler) OnSetDisplayMessage(context.Context, messages.SetDisplayMessageRequest) (messages.SetDisplayMessageResponse, error) {
	return messages.SetDisplayMessageResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetDisplayMessage not implemented", nil)
}

func (UnimplementedCPHandler) OnGetDisplayMessages(context.Context, messages.GetDisplayMessagesRequest) (messages.GetDisplayMessagesResponse, error) {
	return messages.GetDisplayMessagesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetDisplayMessages not implemented", nil)
}

func (UnimplementedCPHandler) OnClearDisplayMessage(context.Context, messages.ClearDisplayMessageRequest) (messages.ClearDisplayMessageResponse, error) {
	return messages.ClearDisplayMessageResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ClearDisplayMessage not implemented", nil)
}

func (UnimplementedCPHandler) OnUpdateFirmware(context.Context, messages.UpdateFirmwareRequest) (messages.UpdateFirmwareResponse, error) {
	return messages.UpdateFirmwareResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "UpdateFirmware not implemented", nil)
}

func (UnimplementedCPHandler) OnPublishFirmware(context.Context, messages.PublishFirmwareRequest) (messages.PublishFirmwareResponse, error) {
	return messages.PublishFirmwareResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "PublishFirmware not implemented", nil)
}

func (UnimplementedCPHandler) OnUnpublishFirmware(context.Context, messages.UnpublishFirmwareRequest) (messages.UnpublishFirmwareResponse, error) {
	return messages.UnpublishFirmwareResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "UnpublishFirmware not implemented", nil)
}

func (UnimplementedCPHandler) OnGetInstalledCertificateIds(context.Context, messages.GetInstalledCertificateIdsRequest) (messages.GetInstalledCertificateIdsResponse, error) {
	return messages.GetInstalledCertificateIdsResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetInstalledCertificateIds not implemented", nil)
}

func (UnimplementedCPHandler) OnInstallCertificate(context.Context, messages.InstallCertificateRequest) (messages.InstallCertificateResponse, error) {
	return messages.InstallCertificateResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "InstallCertificate not implemented", nil)
}

func (UnimplementedCPHandler) OnDeleteCertificate(context.Context, messages.DeleteCertificateRequest) (messages.DeleteCertificateResponse, error) {
	return messages.DeleteCertificateResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "DeleteCertificate not implemented", nil)
}

func (UnimplementedCPHandler) OnCertificateSigned(context.Context, messages.CertificateSignedRequest) (messages.CertificateSignedResponse, error) {
	return messages.CertificateSignedResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "CertificateSigned not implemented", nil)
}

func (UnimplementedCPHandler) OnGetLocalListVersion(context.Context, messages.GetLocalListVersionRequest) (messages.GetLocalListVersionResponse, error) {
	return messages.GetLocalListVersionResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetLocalListVersion not implemented", nil)
}

func (UnimplementedCPHandler) OnSendLocalList(context.Context, messages.SendLocalListRequest) (messages.SendLocalListResponse, error) {
	return messages.SendLocalListResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SendLocalList not implemented", nil)
}

func (UnimplementedCPHandler) OnGetBaseReport(context.Context, messages.GetBaseReportRequest) (messages.GetBaseReportResponse, error) {
	return messages.GetBaseReportResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetBaseReport not implemented", nil)
}

func (UnimplementedCPHandler) OnGetReport(context.Context, messages.GetReportRequest) (messages.GetReportResponse, error) {
	return messages.GetReportResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetReport not implemented", nil)
}

func (UnimplementedCPHandler) OnGetVariables(context.Context, messages.GetVariablesRequest) (messages.GetVariablesResponse, error) {
	return messages.GetVariablesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetVariables not implemented", nil)
}

func (UnimplementedCPHandler) OnSetVariables(context.Context, messages.SetVariablesRequest) (messages.SetVariablesResponse, error) {
	return messages.SetVariablesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetVariables not implemented", nil)
}

func (UnimplementedCPHandler) OnReset(context.Context, messages.ResetRequest) (messages.ResetResponse, error) {
	return messages.ResetResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "Reset not implemented", nil)
}

func (UnimplementedCPHandler) OnSetNetworkProfile(context.Context, messages.SetNetworkProfileRequest) (messages.SetNetworkProfileResponse, error) {
	return messages.SetNetworkProfileResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetNetworkProfile not implemented", nil)
}

func (UnimplementedCPHandler) OnRequestStartTransaction(context.Context, messages.RequestStartTransactionRequest) (messages.RequestStartTransactionResponse, error) {
	return messages.RequestStartTransactionResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "RequestStartTransaction not implemented", nil)
}

func (UnimplementedCPHandler) OnRequestStopTransaction(context.Context, messages.RequestStopTransactionRequest) (messages.RequestStopTransactionResponse, error) {
	return messages.RequestStopTransactionResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "RequestStopTransaction not implemented", nil)
}

func (UnimplementedCPHandler) OnUnlockConnector(context.Context, messages.UnlockConnectorRequest) (messages.UnlockConnectorResponse, error) {
	return messages.UnlockConnectorResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "UnlockConnector not implemented", nil)
}

func (UnimplementedCPHandler) OnTriggerMessage(context.Context, messages.TriggerMessageRequest) (messages.TriggerMessageResponse, error) {
	return messages.TriggerMessageResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "TriggerMessage not implemented", nil)
}

func (UnimplementedCPHandler) OnReserveNow(context.Context, messages.ReserveNowRequest) (messages.ReserveNowResponse, error) {
	return messages.ReserveNowResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ReserveNow not implemented", nil)
}

func (UnimplementedCPHandler) OnCancelReservation(context.Context, messages.CancelReservationRequest) (messages.CancelReservationResponse, error) {
	return messages.CancelReservationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "CancelReservation not implemented", nil)
}

func (UnimplementedCPHandler) OnSetChargingProfile(context.Context, messages.SetChargingProfileRequest) (messages.SetChargingProfileResponse, error) {
	return messages.SetChargingProfileResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SetChargingProfile not implemented", nil)
}

func (UnimplementedCPHandler) OnGetChargingProfiles(context.Context, messages.GetChargingProfilesRequest) (messages.GetChargingProfilesResponse, error) {
	return messages.GetChargingProfilesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetChargingProfiles not implemented", nil)
}

func (UnimplementedCPHandler) OnClearChargingProfile(context.Context, messages.ClearChargingProfileRequest) (messages.ClearChargingProfileResponse, error) {
	return messages.ClearChargingProfileResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ClearChargingProfile not implemented", nil)
}

func (UnimplementedCPHandler) OnGetCompositeSchedule(context.Context, messages.GetCompositeScheduleRequest) (messages.GetCompositeScheduleResponse, error) {
	return messages.GetCompositeScheduleResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetCompositeSchedule not implemented", nil)
}

func (UnimplementedCPHandler) OnCostUpdated(context.Context, messages.CostUpdatedRequest) (messages.CostUpdatedResponse, error) {
	return messages.CostUpdatedResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "CostUpdated not implemented", nil)
}

func (UnimplementedCPHandler) OnGetTransactionStatus(context.Context, messages.GetTransactionStatusRequest) (messages.GetTransactionStatusResponse, error) {
	return messages.GetTransactionStatusResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetTransactionStatus not implemented", nil)
}

// RegisterCP registers every CSMS->CP handler from h on the client.
func RegisterCP(c *cp.Client, h CPHandler) error {
	if err := cp.On(c, profiles.ClearCache, h.OnClearCache); err != nil {
		return err
	}
	if err := cp.On(c, profiles.ChangeAvailability, h.OnChangeAvailability); err != nil {
		return err
	}
	if err := cp.On(c, profiles.DataTransfer, h.OnDataTransfer); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetMonitoringReport, h.OnGetMonitoringReport); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetMonitoringBase, h.OnSetMonitoringBase); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetVariableMonitoring, h.OnSetVariableMonitoring); err != nil {
		return err
	}
	if err := cp.On(c, profiles.ClearVariableMonitoring, h.OnClearVariableMonitoring); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetMonitoringLevel, h.OnSetMonitoringLevel); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetLog, h.OnGetLog); err != nil {
		return err
	}
	if err := cp.On(c, profiles.CustomerInformation, h.OnCustomerInformation); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetDisplayMessage, h.OnSetDisplayMessage); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetDisplayMessages, h.OnGetDisplayMessages); err != nil {
		return err
	}
	if err := cp.On(c, profiles.ClearDisplayMessage, h.OnClearDisplayMessage); err != nil {
		return err
	}
	if err := cp.On(c, profiles.UpdateFirmware, h.OnUpdateFirmware); err != nil {
		return err
	}
	if err := cp.On(c, profiles.PublishFirmware, h.OnPublishFirmware); err != nil {
		return err
	}
	if err := cp.On(c, profiles.UnpublishFirmware, h.OnUnpublishFirmware); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetInstalledCertificateIds, h.OnGetInstalledCertificateIds); err != nil {
		return err
	}
	if err := cp.On(c, profiles.InstallCertificate, h.OnInstallCertificate); err != nil {
		return err
	}
	if err := cp.On(c, profiles.DeleteCertificate, h.OnDeleteCertificate); err != nil {
		return err
	}
	if err := cp.On(c, profiles.CertificateSigned, h.OnCertificateSigned); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetLocalListVersion, h.OnGetLocalListVersion); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SendLocalList, h.OnSendLocalList); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetBaseReport, h.OnGetBaseReport); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetReport, h.OnGetReport); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetVariables, h.OnGetVariables); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetVariables, h.OnSetVariables); err != nil {
		return err
	}
	if err := cp.On(c, profiles.Reset, h.OnReset); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetNetworkProfile, h.OnSetNetworkProfile); err != nil {
		return err
	}
	if err := cp.On(c, profiles.RequestStartTransaction, h.OnRequestStartTransaction); err != nil {
		return err
	}
	if err := cp.On(c, profiles.RequestStopTransaction, h.OnRequestStopTransaction); err != nil {
		return err
	}
	if err := cp.On(c, profiles.UnlockConnector, h.OnUnlockConnector); err != nil {
		return err
	}
	if err := cp.On(c, profiles.TriggerMessage, h.OnTriggerMessage); err != nil {
		return err
	}
	if err := cp.On(c, profiles.ReserveNow, h.OnReserveNow); err != nil {
		return err
	}
	if err := cp.On(c, profiles.CancelReservation, h.OnCancelReservation); err != nil {
		return err
	}
	if err := cp.On(c, profiles.SetChargingProfile, h.OnSetChargingProfile); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetChargingProfiles, h.OnGetChargingProfiles); err != nil {
		return err
	}
	if err := cp.On(c, profiles.ClearChargingProfile, h.OnClearChargingProfile); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetCompositeSchedule, h.OnGetCompositeSchedule); err != nil {
		return err
	}
	if err := cp.On(c, profiles.CostUpdated, h.OnCostUpdated); err != nil {
		return err
	}
	if err := cp.On(c, profiles.GetTransactionStatus, h.OnGetTransactionStatus); err != nil {
		return err
	}
	return nil
}

// CSMSHandler handles CP-initiated messages received by a CSMS.
type CSMSHandler interface {
	OnAuthorize(context.Context, *csms.Conn, messages.AuthorizeRequest) (messages.AuthorizeResponse, error)
	OnStatusNotification(context.Context, *csms.Conn, messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error)
	OnDataTransfer(context.Context, *csms.Conn, messages.DataTransferRequest) (messages.DataTransferResponse, error)
	OnNotifyEvent(context.Context, *csms.Conn, messages.NotifyEventRequest) (messages.NotifyEventResponse, error)
	OnNotifyMonitoringReport(context.Context, *csms.Conn, messages.NotifyMonitoringReportRequest) (messages.NotifyMonitoringReportResponse, error)
	OnLogStatusNotification(context.Context, *csms.Conn, messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error)
	OnNotifyCustomerInformation(context.Context, *csms.Conn, messages.NotifyCustomerInformationRequest) (messages.NotifyCustomerInformationResponse, error)
	OnNotifyDisplayMessages(context.Context, *csms.Conn, messages.NotifyDisplayMessagesRequest) (messages.NotifyDisplayMessagesResponse, error)
	OnFirmwareStatusNotification(context.Context, *csms.Conn, messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error)
	OnPublishFirmwareStatusNotification(context.Context, *csms.Conn, messages.PublishFirmwareStatusNotificationRequest) (messages.PublishFirmwareStatusNotificationResponse, error)
	OnSignCertificate(context.Context, *csms.Conn, messages.SignCertificateRequest) (messages.SignCertificateResponse, error)
	OnGet15118EVCertificate(context.Context, *csms.Conn, messages.Get15118EVCertificateRequest) (messages.Get15118EVCertificateResponse, error)
	OnGetCertificateStatus(context.Context, *csms.Conn, messages.GetCertificateStatusRequest) (messages.GetCertificateStatusResponse, error)
	OnMeterValues(context.Context, *csms.Conn, messages.MeterValuesRequest) (messages.MeterValuesResponse, error)
	OnBootNotification(context.Context, *csms.Conn, messages.BootNotificationRequest) (messages.BootNotificationResponse, error)
	OnHeartbeat(context.Context, *csms.Conn, messages.HeartbeatRequest) (messages.HeartbeatResponse, error)
	OnNotifyReport(context.Context, *csms.Conn, messages.NotifyReportRequest) (messages.NotifyReportResponse, error)
	OnReservationStatusUpdate(context.Context, *csms.Conn, messages.ReservationStatusUpdateRequest) (messages.ReservationStatusUpdateResponse, error)
	OnSecurityEventNotification(context.Context, *csms.Conn, messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error)
	OnNotifyEVChargingNeeds(context.Context, *csms.Conn, messages.NotifyEVChargingNeedsRequest) (messages.NotifyEVChargingNeedsResponse, error)
	OnNotifyEVChargingSchedule(context.Context, *csms.Conn, messages.NotifyEVChargingScheduleRequest) (messages.NotifyEVChargingScheduleResponse, error)
	OnNotifyChargingLimit(context.Context, *csms.Conn, messages.NotifyChargingLimitRequest) (messages.NotifyChargingLimitResponse, error)
	OnClearedChargingLimit(context.Context, *csms.Conn, messages.ClearedChargingLimitRequest) (messages.ClearedChargingLimitResponse, error)
	OnReportChargingProfiles(context.Context, *csms.Conn, messages.ReportChargingProfilesRequest) (messages.ReportChargingProfilesResponse, error)
	OnTransactionEvent(context.Context, *csms.Conn, messages.TransactionEventRequest) (messages.TransactionEventResponse, error)
}

// UnimplementedCSMSHandler returns a NotSupported CallError for every message.
// Embed it to implement only the messages you care about.
type UnimplementedCSMSHandler struct{}

func (UnimplementedCSMSHandler) OnAuthorize(context.Context, *csms.Conn, messages.AuthorizeRequest) (messages.AuthorizeResponse, error) {
	return messages.AuthorizeResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "Authorize not implemented", nil)
}

func (UnimplementedCSMSHandler) OnStatusNotification(context.Context, *csms.Conn, messages.StatusNotificationRequest) (messages.StatusNotificationResponse, error) {
	return messages.StatusNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "StatusNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnDataTransfer(context.Context, *csms.Conn, messages.DataTransferRequest) (messages.DataTransferResponse, error) {
	return messages.DataTransferResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "DataTransfer not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyEvent(context.Context, *csms.Conn, messages.NotifyEventRequest) (messages.NotifyEventResponse, error) {
	return messages.NotifyEventResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyEvent not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyMonitoringReport(context.Context, *csms.Conn, messages.NotifyMonitoringReportRequest) (messages.NotifyMonitoringReportResponse, error) {
	return messages.NotifyMonitoringReportResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyMonitoringReport not implemented", nil)
}

func (UnimplementedCSMSHandler) OnLogStatusNotification(context.Context, *csms.Conn, messages.LogStatusNotificationRequest) (messages.LogStatusNotificationResponse, error) {
	return messages.LogStatusNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "LogStatusNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyCustomerInformation(context.Context, *csms.Conn, messages.NotifyCustomerInformationRequest) (messages.NotifyCustomerInformationResponse, error) {
	return messages.NotifyCustomerInformationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyCustomerInformation not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyDisplayMessages(context.Context, *csms.Conn, messages.NotifyDisplayMessagesRequest) (messages.NotifyDisplayMessagesResponse, error) {
	return messages.NotifyDisplayMessagesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyDisplayMessages not implemented", nil)
}

func (UnimplementedCSMSHandler) OnFirmwareStatusNotification(context.Context, *csms.Conn, messages.FirmwareStatusNotificationRequest) (messages.FirmwareStatusNotificationResponse, error) {
	return messages.FirmwareStatusNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "FirmwareStatusNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnPublishFirmwareStatusNotification(context.Context, *csms.Conn, messages.PublishFirmwareStatusNotificationRequest) (messages.PublishFirmwareStatusNotificationResponse, error) {
	return messages.PublishFirmwareStatusNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "PublishFirmwareStatusNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnSignCertificate(context.Context, *csms.Conn, messages.SignCertificateRequest) (messages.SignCertificateResponse, error) {
	return messages.SignCertificateResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SignCertificate not implemented", nil)
}

func (UnimplementedCSMSHandler) OnGet15118EVCertificate(context.Context, *csms.Conn, messages.Get15118EVCertificateRequest) (messages.Get15118EVCertificateResponse, error) {
	return messages.Get15118EVCertificateResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "Get15118EVCertificate not implemented", nil)
}

func (UnimplementedCSMSHandler) OnGetCertificateStatus(context.Context, *csms.Conn, messages.GetCertificateStatusRequest) (messages.GetCertificateStatusResponse, error) {
	return messages.GetCertificateStatusResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "GetCertificateStatus not implemented", nil)
}

func (UnimplementedCSMSHandler) OnMeterValues(context.Context, *csms.Conn, messages.MeterValuesRequest) (messages.MeterValuesResponse, error) {
	return messages.MeterValuesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "MeterValues not implemented", nil)
}

func (UnimplementedCSMSHandler) OnBootNotification(context.Context, *csms.Conn, messages.BootNotificationRequest) (messages.BootNotificationResponse, error) {
	return messages.BootNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "BootNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnHeartbeat(context.Context, *csms.Conn, messages.HeartbeatRequest) (messages.HeartbeatResponse, error) {
	return messages.HeartbeatResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "Heartbeat not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyReport(context.Context, *csms.Conn, messages.NotifyReportRequest) (messages.NotifyReportResponse, error) {
	return messages.NotifyReportResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyReport not implemented", nil)
}

func (UnimplementedCSMSHandler) OnReservationStatusUpdate(context.Context, *csms.Conn, messages.ReservationStatusUpdateRequest) (messages.ReservationStatusUpdateResponse, error) {
	return messages.ReservationStatusUpdateResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ReservationStatusUpdate not implemented", nil)
}

func (UnimplementedCSMSHandler) OnSecurityEventNotification(context.Context, *csms.Conn, messages.SecurityEventNotificationRequest) (messages.SecurityEventNotificationResponse, error) {
	return messages.SecurityEventNotificationResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "SecurityEventNotification not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyEVChargingNeeds(context.Context, *csms.Conn, messages.NotifyEVChargingNeedsRequest) (messages.NotifyEVChargingNeedsResponse, error) {
	return messages.NotifyEVChargingNeedsResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyEVChargingNeeds not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyEVChargingSchedule(context.Context, *csms.Conn, messages.NotifyEVChargingScheduleRequest) (messages.NotifyEVChargingScheduleResponse, error) {
	return messages.NotifyEVChargingScheduleResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyEVChargingSchedule not implemented", nil)
}

func (UnimplementedCSMSHandler) OnNotifyChargingLimit(context.Context, *csms.Conn, messages.NotifyChargingLimitRequest) (messages.NotifyChargingLimitResponse, error) {
	return messages.NotifyChargingLimitResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "NotifyChargingLimit not implemented", nil)
}

func (UnimplementedCSMSHandler) OnClearedChargingLimit(context.Context, *csms.Conn, messages.ClearedChargingLimitRequest) (messages.ClearedChargingLimitResponse, error) {
	return messages.ClearedChargingLimitResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ClearedChargingLimit not implemented", nil)
}

func (UnimplementedCSMSHandler) OnReportChargingProfiles(context.Context, *csms.Conn, messages.ReportChargingProfilesRequest) (messages.ReportChargingProfilesResponse, error) {
	return messages.ReportChargingProfilesResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "ReportChargingProfiles not implemented", nil)
}

func (UnimplementedCSMSHandler) OnTransactionEvent(context.Context, *csms.Conn, messages.TransactionEventRequest) (messages.TransactionEventResponse, error) {
	return messages.TransactionEventResponse{}, ocppj.NewCallError(ocppj.ErrorCodeNotSupported, "TransactionEvent not implemented", nil)
}

// RegisterCSMS registers every CP->CSMS handler from h on the server.
func RegisterCSMS(s *csms.Server, h CSMSHandler) error {
	if err := csms.On(s, profiles.Authorize, h.OnAuthorize); err != nil {
		return err
	}
	if err := csms.On(s, profiles.StatusNotification, h.OnStatusNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.DataTransfer, h.OnDataTransfer); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyEvent, h.OnNotifyEvent); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyMonitoringReport, h.OnNotifyMonitoringReport); err != nil {
		return err
	}
	if err := csms.On(s, profiles.LogStatusNotification, h.OnLogStatusNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyCustomerInformation, h.OnNotifyCustomerInformation); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyDisplayMessages, h.OnNotifyDisplayMessages); err != nil {
		return err
	}
	if err := csms.On(s, profiles.FirmwareStatusNotification, h.OnFirmwareStatusNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.PublishFirmwareStatusNotification, h.OnPublishFirmwareStatusNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.SignCertificate, h.OnSignCertificate); err != nil {
		return err
	}
	if err := csms.On(s, profiles.Get15118EVCertificate, h.OnGet15118EVCertificate); err != nil {
		return err
	}
	if err := csms.On(s, profiles.GetCertificateStatus, h.OnGetCertificateStatus); err != nil {
		return err
	}
	if err := csms.On(s, profiles.MeterValues, h.OnMeterValues); err != nil {
		return err
	}
	if err := csms.On(s, profiles.BootNotification, h.OnBootNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.Heartbeat, h.OnHeartbeat); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyReport, h.OnNotifyReport); err != nil {
		return err
	}
	if err := csms.On(s, profiles.ReservationStatusUpdate, h.OnReservationStatusUpdate); err != nil {
		return err
	}
	if err := csms.On(s, profiles.SecurityEventNotification, h.OnSecurityEventNotification); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyEVChargingNeeds, h.OnNotifyEVChargingNeeds); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyEVChargingSchedule, h.OnNotifyEVChargingSchedule); err != nil {
		return err
	}
	if err := csms.On(s, profiles.NotifyChargingLimit, h.OnNotifyChargingLimit); err != nil {
		return err
	}
	if err := csms.On(s, profiles.ClearedChargingLimit, h.OnClearedChargingLimit); err != nil {
		return err
	}
	if err := csms.On(s, profiles.ReportChargingProfiles, h.OnReportChargingProfiles); err != nil {
		return err
	}
	if err := csms.On(s, profiles.TransactionEvent, h.OnTransactionEvent); err != nil {
		return err
	}
	return nil
}
